### ISSUE TITLE
Generators

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#1]
Make sure that model generators work: https://forum.javascriptmvc.com/#Topic/32525000001714003

**Comment by daffl** [comment]
That post is over a year old an talks about JMVC 3.3. I'm not sure what I'm supposed to do with this?

**Comment by justinbmeyer** [comment]
Once you have the model generators tested, please close this issue.

**Comment by justinbmeyer** [comment]
Check if there's weird input.
