### ISSUE TITLE
donejs add app broken

### ISSUE THREAD

**Issue by frank-dspeed** [donejs/donejs#1008]
__How often can you reproduce it?__ 

- [ x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__
donejs add app should produce a application where donejs build and calling production.html work

__Steps to reproduce:__

1. donejs add app my-app
2. cd my-app && donejs build
3. http-server
4. Browser point to localhost:8080/production.html

__Expected results:__
Should show Hello world in production :)

__Actual results:__
Browser did not show it loads only the steal.production.js nothing more 
it trys to load /dist/js.js wich don't exists build creates /dist/bundels/my-app/index.js
```
Starting up http-server, serving ./
Available on:
  http://127.0.0.1:8080
  http://192.168.0.17:8080
  http://172.17.0.1:8080
  http://172.19.0.1:8080
Hit CTRL-C to stop the server
[Wed Aug 09 2017 14:25:05 GMT+0100 (WEST)] "GET /dist/js.js" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36 OPR/46.0.2597.57"
[Wed Aug 09 2017 14:25:05 GMT+0100 (WEST)] "GET /dist/js.js" Error (404): "Not found"
```

__Environment:__

| Software                | Version
| ------------------ | -------
| donejs -V               |  1.0.1
| node -v                  | 6.11.1
| npm -v                   | 3.10.10
| Browser                 | Chrome 59
| Operating system | Ubuntu

**Comment by matthewp** [comment]
Hm, working on Mac, maybe a Ubuntu thing. Will try out a VM.

**Comment by frank-dspeed** [comment]
@matthewp i don't think its a ubuntu thing only for your info moving production.html to dist and changing path to ./steal.production.js works.

**Comment by frank-dspeed** [comment]
can be closed i think it was some kind of node_modules mix up latest versions that never happend again
