### ISSUE TITLE
The CLI should warn if passed invalid arguments

### ISSUE THREAD

**Issue by imaustink** [donejs/donejs#1021]
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__
Running invalid commands exits without any warning. In my opion, this should at least output help.

__Steps to reproduce:__
Run `donejs app add some-app`.

![donejs-cli-no-error](https://user-images.githubusercontent.com/6282922/30550905-b2ece868-9c4d-11e7-9af7-febaa8db6bc7.gif)

__Expected results:__
The CLI logs a warning or help.

__Actual results:__
The CLI exits silently.

__Environment:__

| Software                | Version
| ------------------ | -------
| donejs -V               | `1.0.1`
| node -v                  | `8.4.0`
| npm -v                   | `5.3.0`
| Operating system | `Mac OS 10.12.6`

**Comment by matthewp** [comment]
Hey @imaustink, sorry for taking so long to reply. So, what donejs actually does it defer to donejs-cli. donejs-cli will look in `node_modules/.bin/` and then package.json's `.scripts`, for, in this case `app`. So the fact that it doesn't warn when it finds something is something we can (hopefully) fix in donejs-cli. Going to move this issue there.

**Comment by matthewp** [comment]
Issue moved to [donejs/cli #96](https://github.com/donejs/cli/issues/96) via [**ZenHub**](https://www.zenhub.com/)
