### ISSUE TITLE
Website generation is broken

### ISSUE THREAD

**Issue by leoj3n** [donejs/donejs#1032]
![image](https://user-images.githubusercontent.com/990216/31042812-d567850c-a575-11e7-8de8-8582ef3dc1e2.png)

Because of PR merge #1030.

**Comment by leoj3n** [comment]
Reverting to before that and the generation works:

![image](https://user-images.githubusercontent.com/990216/31042844-9d15db12-a576-11e7-839c-9c18658c4424.png)

Probably has something to do with the Steal 1.X upgrade in `bit-docs-generate-html`.

**Comment by matthewp** [comment]
Not sure when this stopped happening but doesn't appear to be a problem any more.

**Comment by leoj3n** [comment]
@matthewp This stopped because you reverted the PR that caused it (#1033). So, technically this PR is still not merged (and should probably be re-submitted as a new PR).

However, I've since figure out why that PR broke generation in the first place.

It's because the `bit-docs-donejs-theme` doesn't use [the default layout template](https://bit-docs.github.io/bit-docs-website/bit-docs-generate-html/site/default/templates/layout.mustache.html).

Therefore, the `bit-docs-donejs-theme` steal path needs to be updated here:

https://github.com/donejs/bit-docs-donejs-theme/blob/master/templates/layout.mustache#L222-L241

To match the path in the default `layout.mustache` here:

https://github.com/bit-docs/bit-docs-generate-html/blob/master/site/default/templates/layout.mustache#L22-L37

Aside: I'm not so sure that the `src="./static/node_modules/steal/steal.js"` path in the current default `layout.mustache` for `{{#if devBuild}}` is valid. May be a separate issue.
EDIT: I think it should probably be changed to `src="./static/steal.js"` (though really not sure).

UPDATE: Fixing the path to steal solves a 404, but still the generation is broken 😒 Think the whole `bit-docs-donejs-theme` project needs to be updated to use latest CanJS and such.
