### ISSUE TITLE
can-zone seems to be swallowing errors.

### ISSUE THREAD

**Issue by marshallswain** [donejs/donejs#1036]
When I make a mistake in my code, like adding a getter that references a variable that doesn't exist, yet, the zone plugin swallows the error and gives no indication of the problem.  I only discover the error when I step into the code and it goes to the error handler for can zone.

To test this out, generate a new app, open `app.js` and create a new attribute that references an undeclared variable.

**Comment by matthewp** [comment]
```js
import DefineMap from 'can-define/map/';
import route from 'can-route';
import 'can-route-pushstate';

const AppViewModel = DefineMap.extend({
  message: {
    value: 'Hello World!',
    serialize: false
  },
  title: {
    value: 'attr-test-app',
    serialize: false
  },
  get foo() {
    return bar;
  }
});

export default AppViewModel;
```

When I start up the app I get:

```
ReferenceError: bar is not defined
    at DefineMap.get foo (file:/Users/matthew/dev/attr-test-app/src/app.js!eval:24:18)
```

And ditto in the browser.  If this happens after the browser is already loaded (live-reload), I get the same error in the console. What am I doing differently?

**Comment by marshallswain** [comment]
I've seen this happen on three projects, now.  In my personal project, I had a Session model that I was using in the page without having imported it, first.  Nothing would happen.  No error at all.  Then I put in a breakpoint and stepped in and it went into some can-zone error handler.  Similar errors have occurred on both of my current client projects.  In another scenario, there was an error with trying to add attributes to a sealed DefineMap instance.  No error appeared in the console until we setup the project to use `app.js` as the entry point (in place of index.stache) and effectively side-stepped the SSR server and done-autorender.  At that point multiple errors starting showing up, including the "property cannot be added because the instance is not extendable" error, whatever the exact wording is, I don't remember.

**Comment by chasenlehara** [comment]
@Xitstrategies mentioned having this same/similar issue: https://gitter.im/canjs/canjs?at=59e912a1b20c64242923ac83

**Comment by marshallswain** [comment]
I believe @justinbmeyer was able to reproduce a similar issue with @bgando.

**Comment by matthewp** [comment]
No, I believe the issue she had was because of using socket.io-client rather than steal-socket.io.

**Comment by matthewp** [comment]
Does this happen in dev? I'm thinking about adding a timeout and debug information to done-autorender when in dev mode. That would have hopefully surfaced this problem.

**Comment by m-mujica** [comment]
tried a few things and could not replicate, will leave open in case anyone has a breaking example I could use.

**Comment by matthewp** [comment]
Let's close for now until we get something reproducible, this has sat long enough.
