### ISSUE TITLE
New apps shouldn’t have warnings

### ISSUE THREAD

**Issue by chasenlehara** [donejs/donejs#1041]
When a user generates a new app, there should be no warnings in the browser console, e.g. https://github.com/stealjs/steal/issues/1285

Could we add a test that checks whether a newly-generated app has any warnings?

**Comment by matthewp** [comment]
I will fix the steal issue as part of my current sprint.

**Comment by matthewp** [comment]
So in a 2.0-pre app we still get this:

<img width="460" alt="screen shot 2018-01-18 at 12 35 05 pm" src="https://user-images.githubusercontent.com/361671/35112432-043b2e10-fc4c-11e7-8f2b-eb7a8736cb99.png">

Not sure what to do about this one.

**Comment by matthewp** [comment]
Blocked by https://github.com/canjs/can-reflect/issues/96

**Comment by matthewp** [comment]
Newest release of donejs@pre doesn't have any warnings now:

![screen shot 2018-02-09 at 8 55 25 am](https://user-images.githubusercontent.com/361671/36030956-276bd02e-0d77-11e8-9e05-d9dd83fc998d.png)
