### ISSUE TITLE
guides link broken

### ISSUE THREAD

**Issue by moschel** [donejs/donejs#105]
If you click "Guides" at the top it bring up a 404: http://donejs.com/guides.html

That should be an overview of guides or not clickable

**Comment by matthewp** [comment]
@James0x57 the Guides link probably shouldn't be clickable if it's just a dropdown now. Change it to an div maybe?

**Comment by daffl** [comment]
There needs to be a guides overview page I just didn't make one yet. We should explain what is going on and what each guide is for (esp. since there will be more eventually anyway).

**Comment by matthewp** [comment]
This link is still not working.

**Comment by matthewp** [comment]
The link just needs to be capitalized, should be http://donejs.com/Guides.html

**Comment by daffl** [comment]
We should probably keep it open until @James0x57 added the styling for that page and I updated it with the final version.

**Comment by James0x57** [comment]
As soon as I merge in PR 135 we'll have a place to style that page specifically. I put a couple little things in there just to make it work, plus added the links in the guides parent page for now. ( to actually link to the other guides in the mean time )

I also addressed the problem of having to add classes to that shared one but made sure it didn't step on home page or this new guides page.

This page will need a designer's love and they'll need an idea of what the content here will look like.
