### ISSUE TITLE
Live Reload does not update code in Dev Tools source

### ISSUE THREAD

**Issue by Sinjhin** [donejs/donejs#1055]
__How often can you reproduce it?__ 

- [X] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__
When you are debugging code using Chrome Dev Tools' source tab and have live reload enabled it will not show the new code after changes. This is especially noticeable when putting in `debugger` statements.

__Steps to reproduce:__
- With a new donejs generated app, open app.js in the dev tools
- Add some new code to the AppViewModel (in this case a setter with a debugger)
```js
const AppViewModel = DefineMap.extend({
  message: {
    value: 'Hello World!',
    serialize: false,
    set(val) {
      console.log("This shows up");
      //this debugger gets hit
      debugger;
      return val;
    }
  },
  title: {
    value: 'live-reload-test-01',
    serialize: false
  }
});
```
- The new code is not present and the debugger highlights the wrong line
<img width="319" alt="screen shot 2017-11-10 at 11 44 01 am" src="https://user-images.githubusercontent.com/1085104/32671352-b3a56850-c60c-11e7-9072-d73f5e047fdc.png">
- You have to reload the page completely

1. Include a JS Bin (or equivalent) link if possible
2. Detail the exact steps taken to produce the problem
3. Include a gif if possible; you can use LICEcap to make a gif: http://www.cockos.com/licecap/

__Expected results:__
The source shows correctly after a change and live reload in the Dev Tools

__Actual results:__
The new code changes do not show in the Dev Tools and the wrong line is highlighted when a debugger is hit

__Environment:__

| Software                | Version
| ------------------ | -------
| donejs -V               | 1.1.0-beta.0
| node -v                  | v8.8.1
| npm -v                   | 5.5.1
| Browser                 | Chrome 62.0.3202.75 (Official Build) (64-bit)
| Operating system | MacOS 10.12.6

**Comment by matthewp** [comment]
I think this is only true of ES modules, because of source maps.

**Comment by chasenlehara** [comment]
Related issue: https://github.com/stealjs/steal-tools/issues/832

**Comment by matthewp** [comment]
Is it? I think that issue doesn't require live-reload.

**Comment by chasenlehara** [comment]
Sure, but it’s the “same” issue in that source maps aren’t working in ES modules, right? I’d kind of expect https://github.com/stealjs/steal-tools/issues/832 to be fixed before we could fix this one.

[I left that comment because I wanted to be able to find both issues easier from each other. 😊]

**Comment by matthewp** [comment]
No, source maps do work for ES modules in general, they don't work in one particular scenario though.

**Comment by matthewp** [comment]
Here's the underlying Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=438251 . Going to close as we can't do anything on our end to fix it.
