### ISSUE TITLE
PR: Unikernel Support

### ISSUE THREAD

**Issue by frank-dspeed** [donejs/donejs#1058]
This informs you about my upcoming PR for unikernel support for DoneJS Applications

## Short info about unikernel
Its Compiling a DoneJS Application into a Unikernel Application with direct HyperVisor support.
That means simply we abstract Linux Away :+1:  this is needed for some performance gains in production and allows us better to run on custom network stacks that are none standart like the Microsoft Azur one based on Risc Processors

## First Release Support
- NodeOS
- Capsan aka OSv
- docker library/node:*

## Secund Release
- Rumpkernel Support
- Rumpkernel Building guide

- https://github.com/at-nikolaus/donejs-unikernel

**Comment by matthewp** [comment]
I find this difficult to believe.

**Comment by frank-dspeed** [comment]
@matthewp its simply supplying a extra compilation step like done-nw 
done-unikernel

unikernels as virtual machines on OpenStack, VirtualBox, QEMU, AWS, vSphere, ukvm, and Xen. Unikernel incorporates work from the Rumprun, OSv, IncludeOS, and MirageOS projects

**Comment by frank-dspeed** [comment]
@matthewp google about it nodejs unikernel or look into moby/linuxkit which is even a prestate of unikernel containers maybe that is of interrest for you but on the long run we want to encapsulate OS + Software and run it without additions. We call that Unikernel its simply something you can directly boot.

**Comment by frank-dspeed** [comment]
## Motivation for this is
- The Raise and Fall of the Operating System => http://www.fixup.fi/misc/usenix-login-2015/login_oct15_02_kantee.pdf

**Comment by justinbmeyer** [comment]
@frank-dspeed cool ... do you have plans to run an app in one of those environments?

**Comment by frank-dspeed** [comment]
@justinbmeyer yes sure i do that always i was one of dockers first adopters i am much into devops and deployments i will run for example custom vending machines and ATM's with that. As Also pos systems and other Hardware Based Terminals that Offer User Input.

**Comment by frank-dspeed** [comment]
@justinbmeyer its a general fit for every Company desktop that needs to run a single application or for single application servers. That means This Will also be the final ChromeOS when we simply have a unikernel Chrome version

**Comment by frank-dspeed** [comment]
A Later future vision is to have a WebApplication including remote web Applications as Components so you have all apps in place on custom desktops

**Comment by matthewp** [comment]
Closing this as there is no proposed change to DoneJS. Let us know if you build something like this though. Thanks.
