### ISSUE TITLE
Regression loading Bootstrap & jQuery

### ISSUE THREAD

**Issue by chasenlehara** [donejs/donejs#1059]
__Steps to reproduce:__

1. Clone https://github.com/riescorp/jquery-fail
2. `npm install && donejs develop`
3. Load http://localhost:8080/ in your browser

__Expected results:__

Page would load without errors.

__Actual results:__

SSR error in the console:

```
jQuery is not defined
file:/Library/WebServer/Documents/GitHub/jquery-fail/node_modules/bootstrap/js/transition.js:59
}(jQuery);
```

__Notes:__

If I pin these three dependencies to exact versions and reinstall all modules, it starts working correctly:

```
    "done-serve": "1.4.0",
    "done-ssr": "1.1.5",
    "done-ssr-middleware": "1.1.0",
```

**Comment by matthewp** [comment]
I'm looking into it.

**Comment by matthewp** [comment]
Underlying issue: https://github.com/donejs/done-ssr/issues/434

**Comment by matthewp** [comment]
Fixed by https://github.com/donejs/done-ssr/releases/tag/v1.3.1
