### ISSUE TITLE
The new console warnings have a huge amount of false positives

### ISSUE THREAD

**Issue by tracer99** [donejs/donejs#1062]
__How often can you reproduce it?__ 

- [ X ] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__
The console warnings are drowning us in useless errors like:

` title="" is deprecated. Use title:from="''" instead`

Thousands of lines of warnings for every prop that is not a stache binding.

Note, that the above is a custom tag and not a standard HTML tag.

__Environment:__

| Software                | Version
| ------------------ | -------
| donejs -V               | 1.1.0
| node -v                  | 8.4.0
| npm -v                   | 5.5.1
| Browser                 | 
| Operating system | Ubuntu 14.04.5 LTS

**Comment by matthewp** [comment]
@justinbmeyer @chasenlehara @phillipskevin Anyway we can check to see if the ViewModel contains the property before we give this warning? Multiple people have complained about it being too verbose.

**Comment by phillipskevin** [comment]
Perhaps we should just remove this warning for now until we find a better solution.

**Comment by chasenlehara** [comment]
@tracer99 & @jeroencornelissen, as of [can-stache-bindings 3.11.9](https://github.com/canjs/can-stache-bindings/releases/tag/v3.11.9), the warning should only appear when that property is defined in your viewmodel, so I don’t think there will be any false positives. Please let me know if you’re still seeing any false positives. 🙂
