### ISSUE TITLE
Chat Guide updates for CanJS 4.0

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#1065]
- `route()` should be `route.register()`
   ```js
   route('/{page}', { page: 'home' });
   ```
- use `default` instead of value on:
  ```js
    message: {
    value: 'Hello World!',
    serialize: false
  },
  title: {
    value: 'donejs-chat',
    serialize: false
  }
  ```
- Prompt yes / no? ![donejs-chat_ _node_ _node____nvm_versions_node_v8_5_0_bin_donejs_add_supermodel_message_ _93x48](https://user-images.githubusercontent.com/78602/35016669-4d66f3a8-fadf-11e7-8b2f-20238b45138e.png)

**Comment by justinbmeyer** [comment]
- ![donejs-chat_ _node_ _node____nvm_versions_node_v8_5_0_bin_donejs_add_cordova_1_ _93x25](https://user-images.githubusercontent.com/78602/35061234-3ac93272-fb86-11e7-8abd-60a596432ef7.png) We should show the previously configured URL as the default.

**Comment by justinbmeyer** [comment]
- use `~/` for generated names instead of `donejs-chat/`.  Soooo many people used other names and then tried cut and pasting the code which didn't work.

**Comment by justinbmeyer** [comment]
- Is `git` needed?  Does install work w/o git?

**Comment by matthewp** [comment]
Git dep issue: https://github.com/donejs/done-ssr/issues/493

**Comment by matthewp** [comment]
These issues have all been resolved.
