### ISSUE TITLE
DoneJS Chat real-time not working in FF

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#1066]
The real-time behavior of donejs@pre doesn't seem to work in Firefox.

**Comment by justinbmeyer** [comment]
looks like it might be event handlers .. investigating ...

**Comment by justinbmeyer** [comment]
![donejs-chat](https://user-images.githubusercontent.com/78602/35017159-434379f8-fae1-11e7-85ef-f7763b1ac78d.png)

**Comment by justinbmeyer** [comment]
seems like a problem caused by `can-view-callbacks`. `processImport` is called with the wrong arguments `tagHandler(node, tagName, {})` ... no where do I see `tagName` as being passed?

**Comment by justinbmeyer** [comment]
Ok, so this seems like it is caused by one minor problem, and potentially a larger one.  

The small problem is that `can-view-callbacks` calls with the wrong arguments as mentioned in the previous comment.

The larger problem is that SSR-rendered elements should __not__ be mounted via the  "automount" behavior.

Lets say I have a `my-element` custom element registered via `can-component`:

```js
// my-element.js
Component.extend({
  tag: "my-element",
  view: `hello world`
});
```

If I use this component in the DoneJS app's `index.stache`, it will be server side rendered:

```js
<body>
  <my-element>hello world</my-element>
</body>
```

The problem that occurs is that when the application is loading, `my-element.js` will be re-executed and registered with `can-view-callbacks`.  This will call `renderTagsInDocument` and try to mount `<my-element>`.

We need to stop this from happening.  Here's some options:


## `<html class='done-ssr-static'>`

DoneJS could server-side render with some signal on the HTML saying this is "SSR-ed" html.  `can-view-callbacks` would ignore elements "already in the page" if they are in this sort of HTML.    This is something I've wanted for DoneJS already, the ability to conditionally style the SSR-ed page.

Alternatives might be a `can-automount="false"` attribute on the body or document.  

## Make people call something in can-view-callbacks

We could have people turn-on automount like:

```js
Component.extend({ ... })

Component.extend({ ... })

can.viewCallbacks.mountExistingElements()
```

DoneJS would call this after it has re-attached.

I don't like this b/c it complicates CanJS's setup.

**Comment by justinbmeyer** [comment]
In case it's not clear.  Stache needs to do the mounting.  If had had a CanJS stache template like:

```js
<outer-el>
  <inner-el foo:bind="bar"></inner-el>
</outer-el>
```

This might result in something SSR-ed like:

```js
<outer-el>
   <div><from-outer-template foo:bind="bar"/></div>
    <form><inner-el foo:bind="bar"></inner-el></form>
</outer-el>
```

This can not be "element" mounted.  It needs to be mounted by stache to have the right bindings and such.

**Comment by matthewp** [comment]
We add a data attribute when incremental rendering as a way to configure reattachment. `<html data-incrementally-rendered>`: https://github.com/donejs/done-ssr/blob/2919952f2166cec5b2582b8ff648e57e7a5a2b0c/zones/push-mutations/reattach.js#L72

So I think adding something similar for this usecase makes sense. I think it would be better if can-view-callbacks did this itself. It could detect that it is being SSRed and add the attribute. `<html data-can-automount="false">` lgtm.

**Comment by matthewp** [comment]
Alternatively it wouldn't be too bad if this were done in the canjs zone plugin in done-ssr: https://github.com/donejs/done-ssr/tree/master/zones/canjs

I don't prefer this though, because ideally it would be nice if done-ssr could no longer depend on canjs so that in the future it wouldn't need to ever upgrade when canjs has a major version bump. There are already only a few things that it does with canjs.

**Comment by justinbmeyer** [comment]
Yeah, sounds good. Can you make this change?

**Comment by matthewp** [comment]
Yeah, just trying to decide how best it is to detect when to add this configuration. Doing a `isNode` check feels slightly wrong to me. But then I can't think of a better way.

**Comment by matthewp** [comment]
It *might* make sense for done-autorender to do the setting. It is the thing that knows that it doesn't want the automount behavior.

**Comment by matthewp** [comment]
I think I'm going to do it that way for now, have done-autorender add the attribute and can-view-callbacks use it.

**Comment by matthewp** [comment]
Part 1/2: https://github.com/donejs/autorender/pull/109

**Comment by matthewp** [comment]
Part 2/2: https://github.com/canjs/can-view-callbacks/pull/80
