### ISSUE TITLE
DoneJS.com Features -> SSR -> Media request

### ISSUE THREAD

**Issue by James0x57** [donejs/donejs#107]
Hey Atom,

could you please provide a simple image for use here:
http://donejs.com/Features.html#section=section_ServerSideRendered

The image we're after is a loaded donejs app icon and a spinner to show an app is still loading, with "vs" in between them.
Like here:
http://donejs.com/index.html#performance
2nd browser image down on both sides of the graph, where it says "60ms", have it say "vs" and do any other changes as you see fit.
The idea is to quickly show a finished donejs page that's been rendered on the server vs one that was delivered and then fetches more information.

Please let me know if there are any questions, might be easier for me to show on screenhero again if needed. Thanks!
//James

**Comment by atomgroomdesign** [comment]
![donejs-server-render-diagram](https://cloud.githubusercontent.com/assets/5687712/10339084/347c0f2c-6ccf-11e5-844e-e7627094df04.png)

**Comment by James0x57** [comment]
Cheers sir! Added to the page, will be live in a sec
