### ISSUE TITLE
Including can-debug in dev mode

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#1074]
There's some interest in seeing this, I would like to discuss what that looks like from a user's perspective. How will they be using this?

**Comment by matthewp** [comment]
Adding it to the donejs 2 release, provided we can figure out the use-case. If not it can wait for a minor release (as it's not breaking).

**Comment by matthewp** [comment]
@justinbmeyer @phillipskevin You both commented about this in another issue. What is the *goal* for this feature? Are we including it for the sake of it being on `window.can`?

Should we include a bigger debugging guide in donejs for this some how? I'm thinking that when you launch the app for the first time it includes a message in the console that tells you about `window.can` and maybe points to some documentation.

**Comment by phillipskevin** [comment]
The goal I had in mind was setting up `window.can`, yes.

**Comment by matthewp** [comment]
Let's go with using steal-conditional if possible.

**Comment by matthewp** [comment]
@m-mujica This will be yours when you finish the generator stuff. I think trying for using steal-conditional would be nice. You'd have to update generator-donejs to include steal-conditional in the configDependencies and donejs/cli's package.json.donejs deps to include it there as well.

**Comment by m-mujica** [comment]
- https://github.com/donejs/cli/pull/99
- https://github.com/donejs/generator-donejs/pull/278

![screen shot 2018-02-15 at 4 23 59 pm](https://user-images.githubusercontent.com/724877/36286482-36de950a-126d-11e8-9306-10bb2c5fc06e.png)

(I also tried the built version and it works as expected)

**Comment by matthewp** [comment]
@m-mujica do any of the guides need to be updated (the code samples) to reflect this change? I would think the app.js' would, right?
