### ISSUE TITLE
donejs upgrade shouldn't modify images

### ISSUE THREAD

**Issue by phillipskevin** [donejs/donejs#1091]
Right now, `donejs upgrade` passes `**/*.*` to  `can-migrate`.

If you have images in your project, they all get modified:
![image](https://user-images.githubusercontent.com/5851984/37175218-79a6a70c-22de-11e8-9594-32217be2cd62.png)

We should restrict the file types that are passed to `can-migrate`.

**Comment by matthewp** [comment]
blah, that sort of makes the whole thing less flexible, but I guess since we know can-migrate only deals with JavaScript and stache, we can restrict to those extensions.

**Comment by phillipskevin** [comment]
I'll try to figure out which codemods are modifying the images. Maybe we can fix this in `can-migrate` instead.

**Comment by phillipskevin** [comment]
This is fixed by https://github.com/canjs/can-migrate/releases/tag/v2.1.8 which prevents unchanged files from being written.
