### ISSUE TITLE
donejs upgrade should update known ecosystem packages too

### ISSUE THREAD

**Issue by chasenlehara** [donejs/donejs#1092]
After running `donejs upgrade` in my project, I expected packages such as `can-connect-feathers@4` to be updated/installed for me.

**Comment by matthewp** [comment]
That would be cool. I wonder how we could make it work though? How it upgrades the core ones is by looking at donejs-cli/package.json 's donejs.dependencies/devDependencies fields.

**Comment by matthewp** [comment]
This was fixed in donejs 3.1.0.
