### ISSUE TITLE
SSR Rendering HTML Error

### ISSUE THREAD

**Issue by green3g** [donejs/donejs#1099]
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__

Running into this error during ssr:
TypeError: attrValue.replace is not a function
html-serializer.js:26
- feathers\node_modules\can-simple-dom\dist\cjs\simple-dom\html-serializer.js:26:22

Okay. attrValue is the number 10 and stepping up to HTMLSerializer.attr, the attr.name is value in this case causing the crash. Its happening in a component template that looks like this:
```html
            <div class="input-group">
                <span class="input-group-addon">Per page:</span>
                <select el:value:bind="perPage" class="form-select">
                    {{#each perPageOptions}}
                        <option value="{{.}}">{{.}}</option>
                    {{/each}}
                </select>
              </div>
```
`perPage` is 10, and its bound to the select element value.

Donejs process crashes when this happens. It looks like its trying to escape the number 10, and treating it like a string. 
 
![image](https://files.gitter.im/donejs/donejs/99jB/1.PNG)

![image](https://files.gitter.im/donejs/donejs/oge5/image.png)

__Expected results:__

Donejs should not crash when rendering this component. 

__Environment:__

| Software                | Version
| ------------------ | -------
| donejs -V               | 2.1.0
| node -v                  | 8.9.4
| npm -v                   | 5.8
| Browser                 | All
| Operating system | Windows

**Comment by matthewp** [comment]
Probably the bug is that `value` is saved as a number, attributes should always be strings.

**Comment by matthewp** [comment]
https://github.com/canjs/can-simple-dom/blob/90b26787597472b153d8cd0df9973d85e7b428b1/lib/simple-dom/document/element.js#L51

I think this should be converting the attribute `value` to a string. Might changing this locally in your node_modules and see if that fixes it?

**Comment by green3g** [comment]
Yup, adding 
```javascript
Element.prototype._setAttribute = function (_name, value) {
    value += ''
    var attributes = this.attributes;
//...
``` 
does it

**Comment by matthewp** [comment]
awesome, can you submit an issue in can-simple-dom then?
