### ISSUE TITLE
Production.css and base64 images urls gets errenous url

### ISSUE THREAD

**Issue by stefannygard** [donejs/donejs#11]
When building app a production css is generated. Jmvc adds some magic to this process, e.g. updating urls in the css etc. When using base64 encoded images in css (as shown below) there is a problem.

My css
a { background-image: url("data:image/png;base64,iV...ggg=="); }

Production css becomes
a { background-image: url("../data:image/png;base64,iV...ggg==");  }

Problem
"NetworkError: 404 Not Found ..."
the url should not be changed when handling css base64 image urls.

**Comment by justinbmeyer** [comment]
this should be reported in steal

**Comment by stefannygard** [comment]
issue is now reported in steal
