### ISSUE TITLE
Fix: NPM Issues caused by testee

### ISSUE THREAD

**Issue by frank-dspeed** [donejs/donejs#1110]
node latest +
npm latest +

-------
# from 0.7 current
npm install --save-dev testee@0.8.1 
# testee needs to get updated see https://github.com/bitovi/testee/issues/177

**Comment by frank-dspeed** [comment]
npm install --save-dev testee@0.8.1 from 0.7 current

**Comment by matthewp** [comment]
Please file this against donejs/cli. If you want to make a PR, do it to the major branch.  https://github.com/donejs/cli/blob/5d26882238ebe1f16196d19ef90011f3dd26349d/package.json#L76

**Comment by frank-dspeed** [comment]
I think individual packages will need updates and PR's for testee i will even need to replace unmaintained packages from daffl

**Comment by chasenlehara** [comment]
Closing this because it seems like https://github.com/bitovi/testee/issues/177 is more specific. @frank-dspeed please feel free to reopen with more info if I’m misunderstanding this issue.
