### ISSUE TITLE
Reconciling http2' encryption requirement with easy local development

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#1111]
DoneJS 3 plans to have http2 be used by default, as it makes incremental rendering better. However, http2 requires an encrypted connection, so a certificate must be provided by the web server.

For local development you can create a self-signed certificate, but the browser will give you an ugly message when you try to navigate to your page:

<img width="1054" alt="screen shot 2018-09-04 at 12 49 05 pm" src="https://user-images.githubusercontent.com/361671/45045478-1a92ef00-b041-11e8-9836-52be98e546e2.png">

In the above case you can bypass this by clicking __advanced__ and then __proceed to localhost__. Firefox and Safari have similar warning messages.

This is a pretty bad user experience for a number of reasons. I think it's unacceptable that we expect users to deal with this.

-----

This issue aims to come up with a solution that lets us have a good dev experience. Here are some of the possible solutions, but there might be more that I haven't thought.

* Provide an SSL cert for local development with donejs. We could register a real certificate that would be recognized by browsers. 

  Big problem here is that you can't register a certificate for localhost. So we would have to ask the users to edit their `/etc/hosts` file in order to forward requests from `donejs.whatever` to localhost.

  We could possibly do that in generators, but would need the user to provide their sudo password.
* Make incremental rendering work with http/1. The equivalent of PUSH for http/1 is the [link preload](https://w3c.github.io/preload/) tag. We could add a link to the rendering instructions which the browser would start download right away. Compared to PUSH it would be 1 extra roundtrip. But likely still faster than traditional SSR.

  We could discourage people from using HTTP/1 with incremental rendering in production.

**Comment by matthewp** [comment]
I'm heavily leaning towards allowing HTTP1 to be used with incremental rendering via https://github.com/donejs/done-ssr/issues/582

**Comment by frank-dspeed** [comment]
@matthewp maybe we should simply write into the guides how to set a Chrome flag to ignore certificate warnings for localhost.

go to: chrome://flags/#allow-insecure-localhost in your browser and done

**Comment by frank-dspeed** [comment]
@matthewp and if we then additional supply pre generated ssl certs thats totall okay i think

**Comment by matthewp** [comment]
For 3.0 we are just going to default to http/1 with `<link preload>` to speed up fetching of the IR instructions. H2 is supported if you pass `--cert` and `--key` though.
