### ISSUE TITLE
Problems with styles / less on a basic donejs project

### ISSUE THREAD

**Issue by nriesco** [donejs/donejs#1113]
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__

Creating a basic donejs app will result in a strange behaviour while running it on develop mode (`donejs develop`).

**IMPORTANT NOTE:** I managed to make it work by commenting in `index.stache` this line: `<can-import from="~/styles.less" />`.

Also if I add a component, say myComponent.component then it will also fail.

__Steps to reproduce:__

1. `npm install -g donejs@2.1.1`
2. `donejs add app`
3. `donejs develop`
4. open http://localhost:8080

__Expected results:__

Show "Hello World!"

__Actual results:__

Shows "Hello World!" for a few seconds then there is a blank screen.

__Environment:__

| Software                | Version
| ------------------ | -------
| donejs -V               |  2.1.0
| node -v                  |  v8.11.1
| npm -v                   | 6.4.0
| Browser                 | Version 69.0.3497.100 (Official Build) (64-bit)
| Operating system | OSX Mojave

**Comment by matthewp** [comment]
Thanks, will check this out soon...

**Comment by nriesco** [comment]
[Screen Recording 2018-09-29 at 2.35.46 PM.mov.zip](https://github.com/donejs/donejs/files/2431134/Screen.Recording.2018-09-29.at.2.35.46.PM.mov.zip)

This is how the issue looks like

**Comment by nriesco** [comment]
if you take a look at the video, it will fail not when styles.less loads but when `/node_modules/can-component/package.json` loads

**Comment by matthewp** [comment]
I see that too now. Really strange. Investigating....

**Comment by matthewp** [comment]
Something is injecting 
<img width="439" alt="screen shot 2018-09-30 at 4 13 59 pm" src="https://user-images.githubusercontent.com/361671/46262195-d5d96700-c4cb-11e8-9f69-379413c886ea.png">

Trying to figure out where that is coming from...

**Comment by matthewp** [comment]
Less is the cause here. We recently updated less. I think we brought in some weird behavior by doing that. Looking into a solution.

**Comment by matthewp** [comment]
Looks like we can enforce async mode and it won't do this. Can't see a downside to going async anyways, so I'll try that.

**Comment by matthewp** [comment]
Should be fixed by steal-less 1.3.3. I'm confirming now...

**Comment by matthewp** [comment]
Looks good with a new app now. Thanks for reporting!

**Comment by nriesco** [comment]
Working fine now, thanks @matthewp
