### ISSUE TITLE
Problems with routing based on the quick start guide

### ISSUE THREAD

**Issue by nriesco** [donejs/donejs#1114]
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__

I have issues creating a basic project and adding basic routing. I followed the guides but couln't make it work. I created a small video showing the error, but routes work only I cannot read the `page` value within the stache file.

I included a project that has a video showing the error: [https://github.com/riescorp/donejs-test2](https://github.com/riescorp/donejs-test2) the video: [https://github.com/riescorp/donejs-test2/blob/master/sampleError.mov](https://github.com/riescorp/donejs-test2/blob/master/sampleError.mov)

__Steps to reproduce:__

1. `npm install -g donejs@2.1.1`
2. `donejs add app donejs-test2 --yes`
3. `donejs develop`
4. open http://localhost:8080

__Expected results:__

After clicking on the links the `Selected page:` should show `one`, `two`, or `three`

__Actual results:__

Instead it will only update the url but it will not change whatever is in `{{page}}` within the `index.stache`, only works after reloading the page

__Environment:__

| Software                | Version
| ------------------ | -------
| donejs -V               |  2.1.0
| node -v                  |  v8.11.1
| npm -v                   | 6.4.0
| Browser                 | Version 69.0.3497.100 (Official Build) (64-bit)
| Operating system | OSX Mojave

**Comment by matthewp** [comment]
So this is working when you use `localhost:8080/development.html` which uses the hash based routing. Maybe something with can-route-pushstate. Investigating.

**Comment by matthewp** [comment]
@justinbmeyer I'm thinking this might be related to the fix you did here: https://github.com/canjs/can-route-pushstate/commit/1896603972ef31705635fe986ef31a4a75eeac49

This probably needs a 4.x release, right?

**Comment by matthewp** [comment]
I can probably cherry-pick that commit into a 4.x branch.

**Comment by matthewp** [comment]
Working on a release now...

**Comment by matthewp** [comment]
Ok, confirmed this fixes it. Upgrading to can-route-pushstate 4.1.2 fixes the problem. Thanks for reporting!

**Comment by nriesco** [comment]
Back to normal, thanks again @matthewp
