### ISSUE TITLE
Fix the CanJS documentation link

### ISSUE THREAD

**Issue by chasenlehara** [donejs/donejs#1130]
The “finding open issues” section has links to GitHub issue searches for various labels. The link for the CanJS documentation issues is going to a search for “design” issues instead of “documentation”.

Here’s that page in the repo: https://github.com/donejs/donejs/blob/master/docs/guides/contributing.md

Additionally, it would be good to double check the other links, in case there are more mistakes like that. 😊

**Comment by mary-tkachenko** [comment]
@chasenlehara I am fixing CanJS documentation link

**Comment by matthewp** [comment]
Thanks you.
