### ISSUE TITLE
Place My Order Pass (3)

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#1139]
- [ ] We should remove some of the space under the expand icon.
     ![image](https://user-images.githubusercontent.com/78602/49748447-4a1e4c80-fc6b-11e8-848b-298aec17b15f.png) __p3__
- [ ] https://github.com/donejs/donejs/issues/533 __p2__
- [x] warning about link-preload in chrome __p2__
- [ ] We should probably point people at CanJS's debugging guide / tools
- [ ] Upon adding `place-my-order-assets`, you see ![image](https://user-images.githubusercontent.com/78602/49761529-ffadc780-fc8c-11e8-835d-d4e60c76439c.png)
- [ ] Might be worth showing handling error `pageComponent` error condition.
- [x] `<h1>The <strong>{{this.routeData.page}}</strong> page</h1>` needs to be removed on https://donejs.com/place-my-order.html#switch-between-components. __P1__
- [ ] We should name the model types `const Restaurant = DefineMap.extend({`. __P2__
- [ ] Should we rename `restaurants` to `restaurantPromise` ?
   ```js
    restaurants: {
      default() {
        return Restaurant.getList({});
      }
    },
    ```
- [x] Live reload did not seem to when you finish: https://donejs.com/place-my-order.html#add-data-to-the-page __P1__
- [ ] Change `What is the property name of the id?` to `What is the identity property name?` __P3__
- [ ] Add a `copy` button to examples. __P2__
- [ ] Do we need to export the VM? `export const ViewModel = RestaurantList.ViewModel;`
- [ ] No need to get queryLogic on the connection, you can pass the Model type. __P2__
    ```js
    const store = fixture.store([...], State);
    ```
- [ ] Live reload on http://localhost:8080/src/pages/restaurant/list/test.html doesn't remove old test __P2__
- [x] Upon completing https://donejs.com/place-my-order.html#write-the-template you see many ![image](https://user-images.githubusercontent.com/78602/49776627-5b467800-fcc2-11e8-9f03-a2f27bcec6c5.png) - __P1__ ... this is because the request is made like `City.getList({ state });`.  Maybe we should not create a super model but a `can-rest-model`.  Or we need to change the server.
- [ ] We should figure out some way of dealing with this.  I thought execution order can be controlled a bit?  __P2__
    ```html
    <script type="steal-module">
    import "place-my-order-assets";
    import "~/models/fixtures/";
    
    steal.import("~/pages/restaurant/list/");
    </script>
    ```
    Maybe it's possible to use `main` to import the fixtures?  Maybe we should even just do:

    ```js
    document.body.appendChild( stache(`<pmo-restaurant-list/>` ) )
    ```
- [ ] Why are canjs packages imported: `import RoutePushstate from 'can-route-pushstate';`?  __P2__
- [x] Forgot to import `Restaurant` at https://donejs.com/place-my-order.html#create-additional-components . ![image](https://user-images.githubusercontent.com/78602/49813782-d7c27080-fd2d-11e8-83bb-fd4ada7c751a.png) _P1_
- [x] `'#': Item` should be in the prototype.  __P1__:
   ```js
   const ItemsList = DefineList.extend({
     '#': Item
   }, {
     ...
   });
   ```
- [ ] https://donejs.com/place-my-order.html#bundling-assets We should tell people to change `build.js`. Also, the starting build looks like:
   ```js
   const stealTools = require("steal-tools");
   
   let buildPromise = stealTools.build({}, {
     bundleAssets: true
   });
   ```
   The guide shows it having `config: __dirname + "/package.json!npm"`

- [x] Cordova build doesn't seem like it can load data: 
       ![image](https://user-images.githubusercontent.com/78602/49819099-27a73480-fd3a-11e8-99f7-f04b598d4a8f.png) __P1__

- [x] Add electron is breaking (node@v8.9.4 npm@5.6.0) __P2__ Fixed by upgrading to `npm@6.5.0`

    > MacBook-Pro-2:place-my-order justin$ donejs add electron@2
    > Installing donejs-electron@2
    > npm ERR! path /Users/justin/dev/place-my-order/node_modules/npm/node_modules/ansistyles
    > npm ERR! code ENOENT
    > npm ERR! errno -2
    > npm ERR! syscall rename
    > npm ERR! enoent ENOENT: no such file or directory, rename '/Users/justin/dev/place-my-order/node_modules/npm/node_modules/ansistyles' -> '/Users/justin/dev/place-my-order/node_modules/npm/node_modules/.ansistyles.DELETE'
    > npm ERR! enoent This is related to npm not being able to find a file.

- [x] Electron seems to load no data like Cordova __P1__

**Comment by justinbmeyer** [comment]
## Steal improvement:

I created _pages/order/new/new.js_ with:

```js
import { DefineMap, DefineList, superModel } from 'can';
import loader from '@loader';

import { DefineMap, DefineList, superModel } from 'can';
import loader from '@loader';

const Item = DefineMap.extend({
  seal: false
}, {
  price: 'number'
});

const ItemsList = DefineList.extend({
  '#': Item,
  has: function(item) {
    return this.indexOf(item) !== -1;
  },

  toggle: function(item) {
    var index = this.indexOf(item);

    if (index !== -1) {
      this.splice(index, 1);
    } else {
      this.push(item);
    }
  }
});

const Order = DefineMap.extend({
  seal: false
}, {
  '_id': {
    type: 'any',
    identity: true
  },
  name: 'string',
  address: 'string',
  phone: 'string',
  restaurant: 'string',

  status: {
    default: 'new'
  },
  items: {
    Default: ItemsList
  },
  get total() {
    let total = 0.0;
    this.items.forEach(item =>
        total += parseFloat(item.price));
    return total.toFixed(2);
  },
  markAs(status) {
    this.status = status;
    this.save();
  }
});


Order.connection = superModel({
  url: loader.serviceBaseURL + '/api/orders',
  Map: Order,
  List: Order.List,
  name: 'order'
});

export default Order;
```

There's no indication of the file that it's in:

![image](https://user-images.githubusercontent.com/78602/49817052-da749400-fd34-11e8-994e-5c859e4e0ad6.png)

**Comment by matthewp** [comment]
@justinbmeyer can you push your PMO where I can take a look. Need that in order to figure out your cordova / electron issues.

**Comment by matthewp** [comment]
Never mind, I was able to recreate and no what's happening.

**Comment by matthewp** [comment]
Cordova and Electron issues were caused by a server problem on place-my-order.com. That's been resolved now, see below:

![natives](https://user-images.githubusercontent.com/361671/49963074-ffa80480-fee4-11e8-9fbd-b483850748b1.gif)

**Comment by matthewp** [comment]
* https://github.com/donejs/donejs/issues/1141
* https://github.com/donejs/donejs/issues/1142
* https://github.com/donejs/generator-donejs/issues/299
* https://github.com/donejs/generator-donejs/issues/300
* https://github.com/donejs/donejs/issues/1143
* https://github.com/donejs/donejs/issues/1144
* https://github.com/donejs/donejs/issues/1145
* https://github.com/donejs/donejs/issues/1146
* https://github.com/donejs/donejs/issues/1147
* https://github.com/donejs/donejs/issues/1148
* https://github.com/stealjs/steal/issues/1487

**Comment by matthewp** [comment]
A bug when using Electron/cordova. https://github.com/donejs/donejs/issues/1149

**Comment by matthewp** [comment]
#1149 is fixed.

**Comment by matthewp** [comment]
Closing as the remaining issues have been moved into their own issues.
