### ISSUE TITLE
Write JS for HomePage Section Nav Feature

### ISSUE THREAD

**Issue by atomgroomdesign** [donejs/donejs#117]
I need a dev to write some JS for the DoneJS.com home page.  This is for viewports smaller than 768px. 

Branch:
https://github.com/donejs/donejs/tree/homepage-section-nav

Overall Goal:
As the user scrolls up the view port and reaches the end of the `hero` div, the three buttons should morph into a navigation.  Here's a screenshot of that:

![screen shot 2015-09-30 at 1 43 47 pm](https://cloud.githubusercontent.com/assets/5687712/10203072/a6f64a8c-6779-11e5-8ca9-e52e4963833b.png)

Details:
1. Apply the class `fixed` to this div https://github.com/donejs/donejs/blob/homepage-section-nav/docs/donejs.mustache#L8

2. Apply the class `condensed` For each overview button:
https://github.com/donejs/donejs/blob/homepage-section-nav/docs/donejs.mustache#L9
https://github.com/donejs/donejs/blob/homepage-section-nav/docs/donejs.mustache#L12
https://github.com/donejs/donejs/blob/homepage-section-nav/docs/donejs.mustache#L15

3. Apply the class `active` For each overview button, as it becomes active
https://github.com/donejs/donejs/blob/homepage-section-nav/docs/donejs.mustache#L9
https://github.com/donejs/donejs/blob/homepage-section-nav/docs/donejs.mustache#L12
https://github.com/donejs/donejs/blob/homepage-section-nav/docs/donejs.mustache#L15

4. All of the CSS and Animation is already completed for this, once the classes are applied they will take affect.

5. IF the button is clicked when it is in the fixed menu position, it should have the class `active` applied to it - the tap will anchor down to that section.

6. IF the user scrolls down to that section, then the menu button should change and add the `active` state as it scrolls into the view.

7. IF any of the other buttons have an active state when a new one is applied, then remove that class accordingly.

8. If the user scrolls back up to the page, the fixed section menu should morph back into the static button state, by removing the `fixed` and `condensed` classes from the markup.

**Comment by James0x57** [comment]
Hey Atom,

This is all set on this branch:
https://github.com/donejs/donejs/commit/da10eea5f845f8e3c50e3f1070eb12f384a281f1

I'm also going to hijack the scroll jumps so they go to the correct position and animate there, per our convo.

Please let me know when you're happy with the design tweaks you're looking into, I'll commit my scroll jumps after I pull your tweaks, and we'll get 'er live!

Thanks!
//James
