### ISSUE TITLE
adding a component with same name as app

### ISSUE THREAD

**Issue by JaneOri** [donejs/donejs#1175]
__How often can you reproduce it?__ 

- [x ] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__ / __Steps to reproduce:__ / __Actual results:__
donejs v 3.1.0 
just started a new project
creating my first component with the same name as the app:
`donejs add component components/project-name project-name` -> component created directly in src/* (`src/project-name.js`,` src/project-name.html`, etc)
`donejs add component components/project-name/project-name project-name` -> component created directly in src/* (`src/project-name.js`,` src/project-name.html`, etc)
`donejs add component components/project-name/ project-name` -> component created in src/components/project-name/* but all the files are nameless (`.js`, `.html`, etc)

__Expected results:__

component should have been created in the components folder. If the component has a different name than the app, it works as expected.

__Environment:__

| Software                | Version
| ------------------ | -------
| donejs -V               |  3.1.0 (why isn't it -v?)
| node -v                  |  8.9.3
| npm -v                   | 6.9.0
| Browser                 | N/A
| Operating system | Windows 10

**Comment by cherifGsoul** [comment]
@James0x57 it is fixed https://github.com/donejs/generator-donejs/releases/tag/v3.3.0
