### ISSUE TITLE
plugin generator support scoped projects

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#1176]
The plugin generator should support namespaces.  Giving a plugin name of `@bitovi/snapshot-test` makes a package of `bitovi-snapshot-test`.

Also, when a scoped name is provided, the generator should ask if it is public or private.  If public, ` npm publish --access public` should be used.

**Comment by justinbmeyer** [comment]
This works: 

```
donejs add plugin some-name
```

This doesn't:

```
donejs add plugin @bitovi/some-name
```

**Comment by justinbmeyer** [comment]
Work should be done here: https://github.com/donejs/generator-donejs

**Comment by Mattchewone** [comment]
This is fixed in `generator-donejs` and `donejs`.
