### ISSUE TITLE
In production, home.js loads when I go to the messages page.

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#118]
![donejs-chat](https://cloud.githubusercontent.com/assets/78602/10385467/0b5f4906-6e0f-11e5-8dd7-8870cbe23db0.png)

**Comment by matthewp** [comment]
This is because of https://github.com/stealjs/steal-tools/issues/298, it's fixed but not released in a pre.

**Comment by matthewp** [comment]
So that's fixed now:

<img width="1357" alt="screen shot 2015-10-09 at 9 13 14 am" src="https://cloud.githubusercontent.com/assets/361671/10394554/0c239336-6e66-11e5-9db4-dbf6598c9941.png">

However as you can see home.css is loaded, so there's another bug.

**Comment by matthewp** [comment]
## Issues
- [x] - https://github.com/canjs/can-ssr/issues/74

**Comment by matthewp** [comment]
Fixed and verified on chat.donejs.com:

<img width="1366" alt="screen shot 2015-10-14 at 1 30 17 pm" src="https://cloud.githubusercontent.com/assets/361671/10492038/bad0f35a-7277-11e5-85fa-fc084c638af6.png">
