### ISSUE TITLE
donejs add app hangs when creating new app with node 10.16.0 on Windows 10

### ISSUE THREAD

**Issue by mikeebowen** [donejs/donejs#1183]
__How often can you reproduce it?__ 

- [ x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__

With node 10.16.0, npm 6.9.0 and donejs 3.2.0 if you run `donejs add app my-new-app` the cli runs until you answer the questions about your app (`? Project name`,  `? Project main folder` etc.) until it gets to `? NPM version used 6` where it just hangs and never completes creating the new app. After terminating the process the folder for the app is created containing a package-lock.json and node_modules, but nothing else.

If you use ` donejs add app my-new-app --yes`  then the new app is successfully created. Using node 8.x also fixes the issue.

__Steps to reproduce:__
Open terminal (I tried PowerShell and Windows terminal both had the same behavior)
Enter `donejs add app my-app-name`

1. Include a JS Bin (or equivalent) link if possible
2. Detail the exact steps taken to produce the problem
3. Include a gif if possible; you can use LICEcap to make a gif: http://www.cockos.com/licecap/

__Expected results:__
Expected the app to be created

__Actual results:__
donejs CLI hangs on  `? NPM version used 6` line and never finshes

__Environment:__

| Software                | Version
| ------------------ | -------
| donejs -V               | 3.2.0
| node -v                  | 10.16.0
| npm -v                   | 6.9.0
| Browser                 | n/a
| Operating system | Windows 10 Pro v 1803

**Comment by mikeebowen** [comment]
I found the same issue occurs when running `donejs add component my-component` with node 10.

**Comment by chasenlehara** [comment]
Thanks for filling this issue @mikeebowen!

@cherifGsoul, I think this issue is specific to Windows 10.

I’ve opened some PRs to add Node 10 to our AppVeyor config:

- https://github.com/donejs/cli/pull/119/files
- https://github.com/donejs/generator-donejs/pull/306/files
- https://github.com/donejs/donejs/pull/1182/files

You can push fixes to those PRs. I _think_ it’d be good to fix the generator-donejs build first, then the main donejs build.

**Comment by cherifGsoul** [comment]
This might be related to Node v10 on MS Windows 10 in general, as discussed in the yeoman generator [issue](https://github.com/yeoman/generator/issues/1098)
The quick work around for now is to [cygwin](https://www.cygwin.com/) (I tested and works perfectly).

**Comment by cherifGsoul** [comment]
This is fixed in `donejs-cli` [3.2.1](https://github.com/donejs/cli/releases/tag/v3.2.1) .
Run: `npm i -g donejs` to update `donejs`.
cc @mikeebowen
