### ISSUE TITLE
Write JS for Guides Responsive Nav

### ISSUE THREAD

**Issue by atomgroomdesign** [donejs/donejs#119]
Please create a new branch and create the Javascript for this feature.  It is designed for viewports smaller than 768px wide.

### Visual of States:
![screen shot 2015-09-30 at 4 49 21 pm](https://cloud.githubusercontent.com/assets/5687712/10207643/4476e794-6793-11e5-9dbd-a628ea571d0c.png)

### Title Bar Spec:

1. As the user scrolls the viewport upward or downward, the section title and subtitle should update accordingly.
2. If the subtitle is not yet available, only the title should appear
3. When the title and subtitle update, they should animate  similar to this animation that @mickmcgrath13 wrote: http://jsbin.com/nebulu/edit?html,js,output
4. Title bar should be fixed under the main site header at all times.

### Guide Menu Spec:

1. If the user taps or clicks the menu icon, the menu should open and appear as an overlay-like dropdown menu (not push the content down).
2. The current section accordion should be open (js dev to use classes for designer to anchor from with less.)
3. The current section accordion heading should have the - icon to indicate that it is open (js dev to use classes for designer to anchor from with less.)
4. The current subsection title should be highlighted as active with the > icon to the left (js dev to use classes for designer to anchor from with less.)
5. If the user clicks a closed accordion heading, the open accordion should close and the clicked heading should open.
6. If the user clicks on a subsection title, the page behind the overlay should scroll to that point, but the menu should remain open for the user to close.
7. If the user clicks the close icon, the menu should close and reset state to show the open menu with current location.
8. If the menu subsection items are longer, the page body should not scroll and instead the menu subsection overflow should.

**Comment by James0x57** [comment]
Hey @atomgroomdesign, branch mobile-menu is up with my changes and ready to be styled.

If you choose to do the css, please do not flatten it. The files are organized, separated, and explicitly set up to keep the outside body class wrapper. It prevents stepping on other work and makes it clear where to find styles, which is all necessary for preventing tech-debt in the future.

If you want me to do the css, no problem, I can make it look like your mockup above.
