### ISSUE TITLE
semicolons not visible

### ISSUE THREAD

**Issue by moschel** [donejs/donejs#119]
In Usability and Maintainable, the semicolons aren't visible with the background, which causes separate features to look like they're one big phrase. For example, "Supports All Browsers, even IE8; Real time Connected;" just ends up looking like Supports All Browsers, even IE8 Real time Connected" - all one nonsensical phrase.

![2015-10-09_0017](https://cloud.githubusercontent.com/assets/22180/10386300/2e4414c2-6e1b-11e5-8b88-8aa49bf6c456.png)

**Comment by moschel** [comment]
you already had a PR for this :)

**Comment by atomgroom** [comment]
Ah, thank you for closing. I didn't see this issue. It's _done_ :)
