### ISSUE TITLE
Create a better error message for when package.json has an error in it.

### ISSUE THREAD

**Issue by mjstahl** [donejs/donejs#14]
If you create an error in your `package.json` (i.e. add a comma where it doesn't belong) and then try and run a donejs command.  You get the following error message:

`No local package.json found. Please run "donejs init"` 

This is only true when the file cannot be found.  But the user can inspect their filesystem and see the file is there, but may not understand (based on our error message) that their file has an error in it.

**Comment by daffl** [comment]
I think this can be closed. Not sure if it should throw an error but now when the `package.json` has an error it just can't run any of the commands that are loaded dynamically (`scripts`, `.bin/`).
