### ISSUE TITLE
Generating namespaced controller does not work properly

### ISSUE THREAD

**Issue by anvio** [donejs/donejs#14]
Given an application named
"Test"

The following command:
./js jquery/generate/controller Test.Controller.Test 

does not create a file called "test_controller.js" in test/controllers/ as described in the documentation.
Instead it creates a directory "test " in test/controllers/ containing another directory "views" and these files: funcunit.html, test_test.js, test.html, test.js.
Works with 3.05 but not in 3.1

Did I miss something that has changed in the latest version?

**Comment by daffl** [comment]
This is not an issue it is a change in organizing applications (read the latest guide to that here: http://edge.javascriptmvc.com/docs.html#!organizing) starting at version 3.1 and fully implemented in 3.2 which will be relased shortly.

There is not really a controllers folder anymore, each plugin (like a controller) has it's own directory with it's own views subfolder. I think the 3.1 generator didn't work properly as it mixed both the structures up, but the current master should do it properly and generate test/controllers/test and test/controllers/test/views.

**Comment by anvio** [comment]
Thanks for the explanation!
