### ISSUE TITLE
modlet graphic

### ISSUE THREAD

**Issue by moschel** [donejs/donejs#148]
I need some help making a graphic showing the modlet pattern. It should show the two alternatives for organizing files, maybe with a header for each (By Type and By Module).

**Comment by atomgroom** [comment]
@moschel Here's my first iteration on this design. Please let me know your thoughts.

![donejs-modlet](https://cloud.githubusercontent.com/assets/5687712/10459400/fdf6cf76-7194-11e5-9327-9e43424d4003.png)

**Comment by moschel** [comment]
looks good, let's integrate it

**Comment by justinbmeyer** [comment]
Should tabs be open to sorta show apples to apples?

**Comment by atomgroom** [comment]
@justinbmeyer That's not a bad idea either.  Here's what that looks like. Please let me know what you and @moschel would like to go with.

![donejs-modlet-v3](https://cloud.githubusercontent.com/assets/5687712/10465079/a8539144-71b2-11e5-931b-b5233cd5bd6c.png)

**Comment by moschel** [comment]
Sure, let's go with that, but remove the cart folder one so its apples to apples.
