### ISSUE TITLE
header colors

### ISSUE THREAD

**Issue by moschel** [donejs/donejs#153]
IMO the h4 and h5s are kinda drab with a black font. I'd vote for making these match the h3 font color, or giving them another color so they stand out better.

![2015-10-11_1402](https://cloud.githubusercontent.com/assets/22180/10418443/ed16b196-7020-11e5-8ac9-a84066fb71eb.png)

**Comment by moschel** [comment]
Actually, this is weird. Locally the h4 and h5s do have the same color as h3s. Its just on donejs.com that they don't. This implies there's something weird going on with CSS in production, or my setup is messed up somehow.

**Comment by moschel** [comment]
Looking back at this, it looks like they used to be the same as the h3 color, and this was recently changed to black. Was this intentional?

**Comment by atomgroom** [comment]
Hi @Moschel

It was an intentional change. The link colors are also blue, so in many sections the headings looked like clickable links, that are not. So, we adjusted them as they are now.
