### ISSUE TITLE
broken sidebar

### ISSUE THREAD

**Issue by moschel** [donejs/donejs#158]
It looks like one of my recent commits broke the sidebar. However, its not broken for me locally on latest master, so I'm not sure how to fix it.

![2015-10-11_2351](https://cloud.githubusercontent.com/assets/22180/10421709/11b46b0e-7073-11e5-8e53-0af11aa058e5.png)

**Comment by moschel** [comment]
Even weirder, the sidebar in the guides is not expanding like it usually does. Though this, too, works fine locally for me.

![2015-10-11_2353](https://cloud.githubusercontent.com/assets/22180/10421714/4a4600ae-7073-11e5-95e9-49d0ecd2f3c2.png)

**Comment by atomgroom** [comment]
This was resolved by @James0x57 today.
