### ISSUE TITLE
DoneJS on windows

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#162]
lets make sure it's working again before release.  A comment from an assumed windows user:

> I had a quick look at done-js.  Quite a couple for technologies included there.  I couldn’t get it working though.  Installed OK, but when initializing I had some error.  I think it had to do with node-gyp (same thing for can-compile).  Now I have had it with node-gyp.  I spent hours trying all kinds of solution to no avail.  So I am not going to bother any further.

I think we need some good instructions about how to get `node-gyp` running easily.

**Comment by matthewp** [comment]
node-gyp errors can happen with optionalDependencies, but those are optional and don't mean installation has failed.  I think sometimes users see these errors and think it means the install failed but that's not the case.

Probably the first step would be to catalog all of the native modules we are using and see if there is a non-native alternative (I think there might be one for `ws` used for websockets in steal-tools live-reload).

Secondly we should run through the guide in Windows just to make sure there are no problems the tests are not catching.

**Comment by matthewp** [comment]
I think I'm going to reuse the guide on steal-tools, it's probably what is needed: http://stealjs.com/docs/guides.ContributingWindows.html

**Comment by matthewp** [comment]
I think the issue the user ran into is `donejs develop` not starting because of a bug in can-serve.  Going to fix that first with a test.

**Comment by matthewp** [comment]
## Issues
- [x] - https://github.com/canjs/can-ssr/issues/77
- [ ] - https://github.com/donejs/donejs/issues/212
- [x] - https://github.com/donejs/donejs/pull/211
- [x] - https://github.com/donejs/deploy/pull/34
- [x] - https://github.com/donejs/donejs/pull/214
- [x] - https://github.com/donejs/css/pull/27

**Comment by matthewp** [comment]
Fixed the donejs develop issue:

![win](https://cloud.githubusercontent.com/assets/361671/10498305/be5e26fc-7298-11e5-85e0-8fa17bbd1e20.gif)

Going to try and get through the entire guide.

**Comment by matthewp** [comment]
- [x] - Update the guide when talking about production to properly set the NODE_ENV on windows: http://stackoverflow.com/questions/9249830/how-can-i-set-node-env-production-in-windows
- [x] - Update the guide to make the NW.js section platform agnostic. To run: `.\build\donejs-chat\win32\donejs-chat.exe`
- [x] - Figure out what to do about the Cordova section. Do we switch this entire section to Android?
