### ISSUE TITLE
Homepage - Menu Animation Triggers

### ISSUE THREAD

**Issue by atomgroomdesign** [donejs/donejs#163]
On iOS Safari, if you use small tap and pulls to scroll up / down the page - the collapsed menu for each section re-triggers and re-animates for each tap.  Please remove these click / tap events so they don't do this.

![donejs-ios-menu](https://cloud.githubusercontent.com/assets/5687712/10297791/50b27fc4-6b9d-11e5-9aa6-56e6b3ac37ba.gif)

**Comment by justinbmeyer** [comment]
This was something I was trying to describe last week.  Thanks for creating an issue.

**Comment by atomgroomdesign** [comment]
Yep! You found the bug originally, I only captured it in action. :smile:
