### ISSUE TITLE
"donejs generate" should create files based on "npm prefix" not the current directory

### ISSUE THREAD

**Issue by mjstahl** [donejs/donejs#17]
When going through the guide, `cd` into the `src` directory and do:

`donejs generate component home.component`

This will give you the following error:

`Cannot find module 'yeoman-environment'`

Therefore any generate commands should start from the `npm prefix` directory and not the current directory.

**Comment by daffl** [comment]
Makes sense (we're assuming you're running commands from the root level). I'm wondering if there is a way to find that out. Just go up paths until you find a `package.json`?

**Comment by mjstahl** [comment]
You could definitely do that! 

I figured it would be easier to just call `npm prefix`.  I realize there is a performance implication, but it is a command so it won't be running often enough to warrant concerns about executing an extra process.

**Comment by mjstahl** [comment]
Based on:
https://github.com/donejs/donejs/blob/master/bin/donejs#L12

Root is currently `cwd()` I believe this is where we could make this change... whatever that change is.

**Comment by daffl** [comment]
I briefly looked into this but couldn't seem to find a way to use it programatically. So the only option I can think of would be to run `npm prefix` in `process.cwd()` and get the output folder.
