### ISSUE TITLE
Quick Start Guide: NW  Build Issues

### ISSUE THREAD

**Issue by BigAB** [donejs/donejs#176]
When I was running through the quick start guide I had some issue with the NW Build:

In the **Desktop and mobile apps** section, under NW
### 1. 
> For the desktop build we first have to install the build tools:
> ```
>  npm install steal-nw --save-dev
> ```

..results in a npm warning:

```
$ npm install steal-nw --save-dev

npm WARN deprecated node-webkit-builder@1.0.13: WARNING: This module has been renamed to nw-builder. Install using nw-builder instead, node-webkit-builder will no longer be updated.
```

So I assume we should switch to nw-builder. (?)

### 2. 
When actually running the NW app, the chat page was just blank, and I was unsure how to debug that further.

![nw-app-issue](https://cloud.githubusercontent.com/assets/76821/10322046/28dfd2e8-6c39-11e5-96d2-50bb5b876e90.gif)

**Comment by daffl** [comment]
This was because of https://github.com/bitovi/canjs/pull/1975. CanJS 2.3.0-beta.2 should fix it.

**Comment by daffl** [comment]
Can you submit a PR changing https://github.com/stealjs/steal-nw/blob/master/package.json#L25 to the correct dependency? /cc @matthewp

**Comment by daffl** [comment]
Fixed and verified.
