### ISSUE TITLE
UL still not right

### ISSUE THREAD

**Issue by moschel** [donejs/donejs#176]
@atomgroomdesign after your change, the ULs are TOO spaced out. Do you agree this looks strange?

![2015-10-13_0125](https://cloud.githubusercontent.com/assets/22180/10447372/7c08eb3e-7149-11e5-8d3e-f114c4a2fbb6.png)

**Comment by atomgroom** [comment]
@moschel I can see that you think they are too spaced out.  Although, I don't think they look strange -- I did design them to be this way as I felt that the spacing and margin was equal, balanced and flowed nicely when reading the page.

Here's a sample from Smashing Magazine, where they follow a similar pattern with spacing:
![screen shot 2015-10-13 at 8 12 27 am](https://cloud.githubusercontent.com/assets/5687712/10455674/3dd32828-7182-11e5-9246-f7574f43c510.png)

And another from A List Apart:
![screen shot 2015-10-13 at 8 13 40 am](https://cloud.githubusercontent.com/assets/5687712/10455698/64cc9a54-7182-11e5-8f41-3985ec19fa7a.png)

Please consider and if you still want them to be tighter I can go back and take care of it.

**Comment by moschel** [comment]
Ok you convinced me.
