### ISSUE TITLE
On the web link

### ISSUE THREAD

**Issue by moschel** [donejs/donejs#178]
On the homepage, I propose having the On the Web menu lead to a dropdown that has 1) place-my-order.com and 2) download source

Right now there's no easy way to get to place-my-order.com from the homepage, and I'd expect On the Web to take me there.

**Comment by justinbmeyer** [comment]
This is a bug.  It's supposed to take you to the site.  cc @matthewp @James0x57

**Comment by moschel** [comment]
I'll fix it, I've got some other small changes locally
