### ISSUE TITLE
forum link

### ISSUE THREAD

**Issue by moschel** [donejs/donejs#178]
@justinbmeyer do you have a preferred Forum in mind for DoneJS? The Forum link under Help is currently a broken link.

![2015-10-13_0130](https://cloud.githubusercontent.com/assets/22180/10447440/066b4eb6-714a-11e5-96d2-eece607a442a.png)

**Comment by moschel** [comment]
Decided to use another forum after launch (can't remember the name)

**Comment by justinbmeyer** [comment]
discourse
