### ISSUE TITLE
Help and Github links

### ISSUE THREAD

**Issue by moschel** [donejs/donejs#179]
Right now, the only way to find the help or github links is on the bottom of the homepage. Feature, guides, etc pages don't have any way to find those.

2 thoughts on this....

1) We could add a Community link at the top, and have a designed community page with those links instead of being in the homepage. That way its always accessible. We could also include a link to meetups.

2) I like Ember's footer. It has the social media icons and a copyright notice that links back to their company. I wonder if we should do something similar.

![2015-10-13_0136](https://cloud.githubusercontent.com/assets/22180/10447539/eb25327e-714a-11e5-8256-d99b3b13ee27.png)

@justinbmeyer any thoughts?

**Comment by moschel** [comment]
@justinbmeyer agreed with this in standup today. Not a top priority, but should get this stuff fixed.

**Comment by atomgroom** [comment]
@moschel @justinbmeyer Here's a footer redesign option.  Please let me know what you think, I can get this done pretty quick.

![screen shot 2015-10-19 at 1 51 41 pm](https://cloud.githubusercontent.com/assets/5687712/10587837/b54a58e6-7668-11e5-9fa6-35667c1106f4.png)

**Comment by atomgroom** [comment]
Also, on the community landing page, we need to add the MeetUp links by city too.

**Comment by moschel** [comment]
footer looks good to me
