### ISSUE TITLE
Quick Start Guide: Cordova build bit-tabs content disappearing

### ISSUE THREAD

**Issue by BigAB** [donejs/donejs#179]
So I was going through the **quick start guide** and discovered a few issues.

In the **Desktop and mobile apps > Cordova** section, when I build the app, and go to the homepage, when I switch back and forth on the **tabs** the content disappears.

This does not happen on the web or NW version, just the Cordova iPhone build (I did not check any other mobile build).

It happens on the simulator:
![bit-tabs-issue-simulator](https://cloud.githubusercontent.com/assets/76821/10322483/223a8aee-6c3b-11e5-88c3-9c7f593a2b26.gif)

and the actual device:
![bit-tabs-issue](https://cloud.githubusercontent.com/assets/76821/10322494/2b913516-6c3b-11e5-9a53-df879ea1e22e.gif)

**Comment by daffl** [comment]
Also tracked here: https://github.com/donejs/chat/issues/4
I'm wondering if it is this CSS:

```css
bit-panel {
  display: block;
  padding: 10px;

  &:empty {
    display: none;
  }
}
```

**Comment by daffl** [comment]
This could be fixed with the change with https://github.com/donejs/chat/commit/7ac1c21344901363dad93b345d3a301489a22d7d and updated in the documentation via https://github.com/donejs/donejs/commit/81b67568e2c3f469695b3f52e38bd83b2f73b686.
