### ISSUE TITLE
AMD support

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#18]
Create a steal/amd plugin that supports AMD modules ontop of steal's API.

http://wiki.commonjs.org/wiki/Modules/AsynchronousDefinition

Things to think about:
- steal currently does not support cycles.  Is this supported in AMD / CommonJS?

**Comment by polgfred** [comment]
https://github.com/amdjs/amdjs-api/wiki/AMD is the official doc.

**Comment by ev45ive** [comment]
https://forum.javascriptmvc.com/#Topic/32525000001044065 - thoughts on Steal/AMD

**Problems:**
- $.Class() - register new Classes in global scope or return in module exports?
- How to pass dependencies from module to Classes inside? by defaults object?
- How not to "bloat" code with AMD and not confuse less advanced users
- How to decouple module contents from rest of app for reusability (possibly decouple from AMD implementation at all?)
- Have I missed something?

**Comment by daffl** [comment]
DoneJS repository migration.
