### ISSUE TITLE
node build vs donejs build

### ISSUE THREAD

**Issue by moschel** [donejs/donejs#181]
I noticed that in several places throughout the guides, there's instructions to run `donejs build` and in other places, it says to run `node build`.

Very possible this is a stupid question, but is that right? Or is it always supposed to be donejs build?

In the quick start guide, it only refers to donejs build, but in the in depth guide, it says node build in a few places.

![2015-10-13_0159](https://cloud.githubusercontent.com/assets/22180/10447928/4502beb2-714e-11e5-9d14-1df3e89d7e8c.png)

**Comment by daffl** [comment]
`donejs build` is running `npm run build` which is set in the package.json as `scripts: { build: "node build" }`. It should be consistent though and probably be `donejs build` everywhere.
