### ISSUE TITLE
mobile headers

### ISSUE THREAD

**Issue by moschel** [donejs/donejs#182]
Pretty minor, but why are we cutting off the title after so few characters on mobile?

![2015-10-13_0202](https://cloud.githubusercontent.com/assets/22180/10447944/819e87b6-714e-11e5-959d-383cc4d80694.png)

**Comment by atomgroom** [comment]
Hey @moschel Good catch. It looks like the tablet (portrait) media query is kicking in too early.  I'll take a look today.
