### ISSUE TITLE
Guides hover link

### ISSUE THREAD

**Issue by moschel** [donejs/donejs#184]
![2015-10-06_1702](https://cloud.githubusercontent.com/assets/22180/10323978/2af24d96-6c4c-11e5-9a0b-a29b48905f3d.png)

For some reason Quick start is always given a gray background, so when you hover over place-my-order.com, they both have a gray background, which looks like a bug.

**Comment by atomgroomdesign** [comment]
Fixed in the branch css-tweaks-v2.
