### ISSUE TITLE
Headings: White Space

### ISSUE THREAD

**Issue by atomgroomdesign** [donejs/donejs#192]
User feedback: There's a lot of white space in the headings with the black background, it seem excessive.

We should address this with the design team.

**Comment by moschel** [comment]
It still feels like an excessive amount of whitespace IMO. Do we need all this space?

![2015-10-07_1811](https://cloud.githubusercontent.com/assets/22180/10353723/d62cd4ce-6d1e-11e5-9e20-e131576a3af1.png)

**Comment by atomgroomdesign** [comment]
@moschel We reduced it by 100px as we felt that it was balanced and smaller than the main heading.

**Comment by justinbmeyer** [comment]
It's fine. It works much better with the pmo guide that has longer sections.

**Comment by atomgroomdesign** [comment]
I adjusted it just a little bit more. Hopefully this will satisfy all concerns.

**Comment by justinbmeyer** [comment]
@atomgroomdesign spacing looks good thanks!
