### ISSUE TITLE
videos not full width

### ISSUE THREAD

**Issue by moschel** [donejs/donejs#195]
The videos are not taking up the full container width. I'm not sure if that's a css issue or something with the video files themselves. @phillipskevin do you know?

![donejs_-_donejs](https://cloud.githubusercontent.com/assets/22180/10474953/0317dcf2-7203-11e5-8649-65116a5f8c7a.png)

**Comment by phillipskevin** [comment]
This is because the `.background video` has a fixed height and the videos are not all the correct dimensions. I'll try to resize them.

**Comment by atomgroom** [comment]
Closing. This is completed here: https://github.com/donejs/donejs/pull/203
