### ISSUE TITLE
Feature buttons

### ISSUE THREAD

**Issue by moschel** [donejs/donejs#197]
#180 shows the buttons floating next to each other. Could you please make that happen. I added buttons here: http://donejs.com/Features.html#section_ProgressiveLoading

![2015-10-14_0012](https://cloud.githubusercontent.com/assets/22180/10475471/990d4b42-7209-11e5-87ca-8dc7b8780bb4.png)

**Comment by atomgroom** [comment]
Hrm. That's odd.  I actually tested that specifically and it worked. :-1:  I'll take a look and see what's going on.

**Comment by atomgroom** [comment]
Ah, Okay. I see what it is. DocumentJS is wrapping them in a `<p>` tag because there are line breaks around it.  If we just remove the breaks, they will float.  I'll take care of it and link to the PR to show you.
