### ISSUE TITLE
Difference between javascriptmvc and jquerymx

### ISSUE THREAD

**Issue by danielhunt** [donejs/donejs#2]
According to the docs for javascriptmvc, we should:
  git submodule add git@github.com:_YOU_/jquerymx.git jquery

According to the docs for jquerymx, we should:
  git submodule add git@github.com:_YOU_/javascriptmvc.git jquery

Considering that "./js" only actually works within the javascriptmvc codebase, what exactly should I be doing to start _using_ JMVC?
If this is already painfully clear in the readme, I apologise, but I just can't figure out what I should be doing to just get started here :(

**Comment by moschel** [comment]
Follow the installation guide here:

http://javascriptmvc.com/#&who=install

I fixed the old reference you found to javascriptmvc.git in the README. Thanks for pointing that out!

**Comment by danielhunt** [comment]
Excellent - cheers for clearing that up! :)
