### ISSUE TITLE
Guide shows can, can-connect, can-ssr, ... as peerDependencies of donejs

### ISSUE THREAD

**Issue by phillipskevin** [donejs/donejs#20]
The Guide shows this folder structure after installing donejs as a dependency: 

```
├── package.json
├── node_modules/
|   ├── .bin/
|   └── can/
|   └── can-connect/
|   └── can-ssr/
|   └── ...
```

It looks like the peer dependencies were removed in 0.1.0. Here's the folder structure I'm seeing with donejs@0.1.1:

```
├── package.json
├── node_modules/
|   ├── .bin/
|   └── donejs/
```

**Comment by phillipskevin** [comment]
Also, after installing place-my-order-api as a dependency, this is what I see in package.json:

```
  "dependencies": {
    "donejs": "^0.1.1",
    "place-my-order-api": "^0.4.2"
  }
```

**Comment by matthewp** [comment]
Thanks, donejs init is replacing our use of peerDependencies. I think we can remove them from the package.json, agree @daffl ?

**Comment by justinbmeyer** [comment]
Yes, they have been moved to within a "donejs" property name in package.json: https://github.com/donejs/donejs/blob/master/package.json#L44
