### ISSUE TITLE
Maintainable section images very wide in IE11

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#200]
<img width="1316" alt="screen shot 2015-10-14 at 2 21 14 pm" src="https://cloud.githubusercontent.com/assets/361671/10493405/f27866b0-727e-11e5-9fd2-be5412ae2dff.png">

**Comment by matthewp** [comment]
This is true of just the images, not the videos. cc @atomgroomdesign @phillipskevin @moschel

**Comment by atomgroom** [comment]
And so the IE fixing begins.  Maybe we also need a label, just for IE :)

**Comment by matthewp** [comment]
There's a "compatibility" label that is not just for the website but you could use it in conjuction with the "website" label.

**Comment by atomgroom** [comment]
Closing, it worked itself out. Wow.
