### ISSUE TITLE
Support `donejs add` command

### ISSUE THREAD

**Issue by phillipskevin** [donejs/donejs#202]
User should be able to run commands like `donejs add cordova`. 

This will:
1. Install the donejs "plugin" (such as `donejs-cordava`) if not already installed
2. Run any generators supplied by the plugin

**Comment by phillipskevin** [comment]
`donejs add cordova` should run the default generator supplied by `donejs-cordova`.

`donejs add cordova foo` should run the `foo` generator supplied by `donejs-cordova`.

**Comment by daffl** [comment]
This is already supported.
