### ISSUE TITLE
FuncUnit able to use Jasmine (and JSTestDriver)

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#21]
FuncUnit should be able to use Jasmine or other testing solutions.  And JSTestDriver should work as a steal.browser.

References:
- https://github.com/jupiterjs/funcunit/issues/12
- http://forum.javascriptmvc.com/#Topic/32525000000224009/32525000000667494

**Comment by daffl** [comment]
DoneJS repository migration.
