### ISSUE TITLE
Grey description text is too close to back ground color in "Community" section

### ISSUE THREAD

**Issue by skylerraytaylor** [donejs/donejs#210]
"If you’re looking for help the best place to start is the forums or our Gitter chatroom." is too light

**Comment by daffl** [comment]
I was just going to submit an issue that the text should probably be removed, the other two sections just have three links each and with the text it looks really unbalanced. I think we're both talking about this:

![screen shot 2015-10-07 at 2 56 28 pm](https://cloud.githubusercontent.com/assets/338316/10352407/bd2fcc44-6d03-11e5-8e1b-b5317108d385.png)

**Comment by atomgroomdesign** [comment]
Updated in https://github.com/donejs/donejs/pull/208
