### ISSUE TITLE
textarea shouldn't be resizable, change Twitter widget

### ISSUE THREAD

**Issue by daffl** [donejs/donejs#211]
The textarea on the homepage shouldn't be resizable:

![screen shot 2015-10-07 at 3 02 42 pm](https://cloud.githubusercontent.com/assets/338316/10352534/8252f2f8-6d04-11e5-94da-91bfcc02cc49.png)

I'm also wondering if there is a way to configure the Twitter widget to not show `followers` after the number (we're migrating the old JMVC repo so the GitHub star count will take more space).

**Comment by atomgroomdesign** [comment]
@daffl Good call, overlooked.  Yes, we can remove that with `data-show-count="false"`

**Comment by atomgroomdesign** [comment]
@daffl Are you referring to just the word `followers`? - Because that to my knowledge is *not* possible.

**Comment by daffl** [comment]
Can you customize the "Follow @donejs" text? I think it's worth showing the follower count but we might run out of room when showing the thousands of stars we will obviously get ;)

**Comment by atomgroomdesign** [comment]
We can remove the @donejs text as an option.

https://dev.twitter.com/web/follow-button
