### ISSUE TITLE
donejs doesn't pass stdin to child process

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#212]

**Comment by matthewp** [comment]
Actually passing stdin isn't enough, the terminal has to be a tty.  This has to return true: `process.stdout.isTTY`.  I think the only way for this to happen is to use spawn.

**Comment by matthewp** [comment]
Implementing the same fix done before: https://github.com/donejs/donejs/commit/67963a2a14b155edf4b82ed085f0a1bfbe249a38

**Comment by daffl** [comment]
I've done this in `donejs-cli` at https://github.com/donejs/cli/blob/master/lib/utils.js#L37 already. We should use spawn as suggested and set `{ stdio: 'inherit' }` in the options.

**Comment by matthewp** [comment]
So is bin/donejs here just going to call into donejs-cli then?

**Comment by daffl** [comment]
The other way around.

**Comment by matthewp** [comment]
I don't get it, the user installed donejs, doesn't it need to call donejs-cli?
