### ISSUE TITLE
buttons not aligned

### ISSUE THREAD

**Issue by moschel** [donejs/donejs#229]
At certain page widths, the buttons are on separate lines, but not left aligned. Their left edges should line up:

![2015-10-16_1830](https://cloud.githubusercontent.com/assets/22180/10555394/11e87470-7434-11e5-9f62-6b76bc9e021f.png)

**Comment by atomgroom** [comment]
Hrm.  Yes, that's not supposed to be that way.  The buttons are supposed to be 100% width at that viewport size, as well.

**Comment by atomgroom** [comment]
@moschel Actually, I can't replicate that on my end:

![donejs-btns](https://cloud.githubusercontent.com/assets/5687712/10578816/2e3bb576-763a-11e5-9bac-2fe5aa64f9c7.gif)

**Comment by atomgroom** [comment]
Closing for now. Please re-open and ping me if it's still a problem for you.
