### ISSUE TITLE
MXUI documentation

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#23]
Clean up and document MXUI.

Things to think about ...

A lot of the API needs to get cleaned up, but we should prioritize what is most useful:
- fill
- accordion
- grid
- list
- slider

etc

**Comment by daffl** [comment]
Totally up for it. I was thinking of using the jQuery UI CSS framework for the markup (should be easy to make it configurable of course). You said a lot of it is already in use. How would we do that with a cleanup? Develop it on a separate branch? Oh and write access to the MXUI repository would be great :)

**Comment by moschel** [comment]
write access = done

**Comment by daffl** [comment]
DoneJS repository migration.
