### ISSUE TITLE
Funny Pull Quote Design

### ISSUE THREAD

**Issue by atomgroom** [donejs/donejs#231]

**Comment by moschel** [comment]
Please talk to me about this before you work on it, I have some more details

**Comment by atomgroom** [comment]
@moschel Here's the latest example.  I would pull an object from each video and put it where the truck currently is.  This would be a pretty quick project for each pull quote. 

![donejs-pull-quote-funny-v4](https://cloud.githubusercontent.com/assets/5687712/10587109/41a451ec-7665-11e5-8375-c0d86cd87c13.jpg)
