### ISSUE TITLE
caption text

### ISSUE THREAD

**Issue by moschel** [donejs/donejs#232]
Please make caption text closer to the images. right now there's too big a gap, which causes confusion

![2015-10-18_0016](https://cloud.githubusercontent.com/assets/22180/10562668/a66d1336-752d-11e5-8b5b-0592dc6c5b90.png)

**Comment by atomgroom** [comment]
@moschel Is this the desired spacing you're looking for?

![image-crop-2](https://cloud.githubusercontent.com/assets/5687712/10578524/58e7904e-7638-11e5-9626-18bf60ca7fab.gif)

**Comment by moschel** [comment]
yeah that's better
