### ISSUE TITLE
ul spacing

### ISSUE THREAD

**Issue by moschel** [donejs/donejs#233]
Too much space between ol's and ul's. Please decrease it.

![2015-10-18_0033](https://cloud.githubusercontent.com/assets/22180/10562726/e1fc9bd6-752f-11e5-833c-d0145aef92d2.png)

**Comment by atomgroom** [comment]
@moschel I thought that we have already completed this here: https://github.com/donejs/donejs/issues/176

**Comment by moschel** [comment]
@atomgroomdesign I know, but I asked others and they agreed with me that it seems strangely spacious on the Features page. Please tweak it a little.
