### ISSUE TITLE
Path to list.js and list.stache is incorrect

### ISSUE THREAD

**Issue by phillipskevin** [donejs/donejs#24]
In the "Add the connection to the page" section of the Guide, these paths:

`pmo/restaurant/list.js`
`pmo/restaurant/list.stache`

should be

`pmo/restaurant/list/list.js`
`pmo/restaurant/lsit/list.stache`

as given in the "Creating a restaurant list element" section.

**Comment by justinbmeyer** [comment]
@phillipskevin does this section still exist?  I can't find it.  Thanks!

**Comment by phillipskevin** [comment]
@justinbmeyer The section is [Add data to the page](http://donejs.com/Guide.html#section_Adddatatothepage) now and has the correct paths. Thanks!
