### ISSUE TITLE
Homepage: Let people know to start on gitter

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#246]
previously, there was some text in the community section telling people to get started on gitter to get help.  I think we should bring that back for release.  We can put it here:

![donejs_-_donejs](https://cloud.githubusercontent.com/assets/78602/10588892/12c053ea-766e-11e5-8676-b2efc4568420.png)

**Comment by atomgroom** [comment]
Text was: "If you’re looking for help the best place to start is the forums or our Gitter chatroom."
