### ISSUE TITLE
Community Landing Page

### ISSUE THREAD

**Issue by atomgroom** [donejs/donejs#248]
Design a community landing page that will be linked to from the global header button.

**Comment by atomgroom** [comment]
![donejs-community-landing-v1](https://cloud.githubusercontent.com/assets/5687712/10589804/de0f0bdc-7672-11e5-9f1d-35098ce6ba68.jpg)

@moschel @justinbmeyer

**Comment by atomgroom** [comment]
We should add a meetups section in there to and list the cities, then link to them individually.

**Comment by moschel** [comment]
Yeah needs meetups, but other than that the design looks good to me. I think we should add some text at the top describing what this page is for, our commitment to community, and linking to http://donejs.com/About.html#section=section_Community

@justinbmeyer ?

**Comment by moschel** [comment]
Also, should we have a bithub feed in here? Or another form of social media/updating content?

**Comment by atomgroom** [comment]
![donejs-community-landing-v2](https://cloud.githubusercontent.com/assets/5687712/10611246/c865b850-7710-11e5-9772-58840d142d73.jpg)

**Comment by atomgroom** [comment]
Here's another iteration based from feedback on the Meetup section (confusing, and hard to scan).  New version has alphabetical, tabular data, and a mock Bithub Feed a the bottom.

![donejs-community-landing-v3](https://cloud.githubusercontent.com/assets/5687712/10612739/c46682dc-7717-11e5-8762-a14e28535770.jpg)

**Comment by skylerraytaylor** [comment]
Here's a layout based on this wireframe: https://docs.google.com/drawings/d/1WkrB51-t6WMXbm96mkeg4rfD4r_ccU7_hlJIoTQ8qQk/edit
![donejs-features-page](https://cloud.githubusercontent.com/assets/3943219/10740181/cb93c476-7bee-11e5-875b-35c07d5e1b78.jpg)

**Comment by skylerraytaylor** [comment]
Update to the Free Weekly Training section - add link to calendar
![donejs-features-page](https://cloud.githubusercontent.com/assets/3943219/10744642/7610346a-7c09-11e5-9d09-d6841afe3d58.jpg)

**Comment by atomgroom** [comment]
@justinbmeyer @skylerraytaylor @moschel - What are your ideas on the three videos in the above image (under "Free Weekly Trainings")? Can you let me know what you want to put there please?

Also, if you have any special ideas for the smaller responsive views, please list the designs here - otherwise I'll follow the same patterns as the home page.

**Comment by justinbmeyer** [comment]
@atomgroomdesign it should be the last 3 videos in our training series.
