### ISSUE TITLE
JavaScriptMVC Community Gamification

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#25]
I've been inspired by http://www.codinghorror.com/blog/2011/10/the-gamification.html and would like to do something similar with JavaScriptMVC.

We can have a points system and give away prizes for achieving a certain level of points.  Points can be earned for:
- Setting up an account (we probably need to know github and forums user).
- Viewing a documentation page for 1 min a scrolling to the bottom of it (0.5)
- Expanding demos (0.5)
- Posting on the forums (1)
- Answering a question correctly on the forums (5)
- Submitting an accepted bug report (10)
- Fixing documentation (10)
- Writing an article (10)
- Launching an app (20)
- Fixing a bug (50)
- Implementing a feature (100)

We can give away prizes:
- sticker 
- yellow headband
- t-shirt
- jersey
- ?

**Comment by daffl** [comment]
DoneJS repository migration.
