### ISSUE TITLE
jsbin for Minimal DOM updates

### ISSUE THREAD

**Issue by moschel** [donejs/donejs#254]
Need to add a JSBin spinning circles example that Justin worked on recently.

It should just compare us to React and Angular. We'll need to add Angular.

**Comment by moschel** [comment]
http://donejs.com/Features.html#section_MinimalDOMUpdates

http://jsbin.com/pamodu/5/edit?html,css,js,output

https://github.com/bitovi/canjs/blob/master/view/stache/visual_benchmark.html

1) getting Justin's performance improvements visible
2) remove ember, adding Angular

**Comment by ccummings** [comment]
Here's the JSBin: http://jsbin.com/ducodekufe/edit?js,output

I added a feature that displays the last result for each framework when you finish running a test.

Here are my results: 
`CanJS: 3.61 | React: 3.58 | Angular: 4.41`

Also created on using Mustache: http://jsbin.com/zusenesaho/1/edit?html,js,output
`CanJS: 8.34 |  React: 3.76 | Angular: 4.46`

UPDATE: I created a much nicer looking bin that runs each library 1000 times and displays a graph at the end: http://jsbin.com/xabigerizu/1

**Comment by justinbmeyer** [comment]
Ugg.  Let's talk tomorrow about getting us faster then react.
