### ISSUE TITLE
Home Page: Better Performance Links

### ISSUE THREAD

**Issue by atomgroom** [donejs/donejs#258]
Please add guide/feature links to the various numeric bullet points that slide in and out of each section, appropriately.  

Currently, these are svgs, so the fastest way might be to make "hot spots" that are positioned over the svg.  Otherwise, the entire graphic would need to be coded in html, css, with sliced up images.

![screen shot 2015-10-20 at 10 49 11 am](https://cloud.githubusercontent.com/assets/5687712/10612860/4789eff0-7718-11e5-89f8-4fe23e082633.png)

**Comment by julia-allyce** [comment]
@atomgroomdesign it looks like you can add links to SVG text elements: http://tutorials.jenkov.com/svg/a-element.html 

edit: ooo nvrm. We aren't using text, but shapes which makes it a bit tricky to plop in a link :/
