### ISSUE TITLE
js scripts reference invalid FuncUnit path

### ISSUE THREAD

**Issue by mindscratch** [donejs/donejs#27]
The js and js.bat scripts ([example](https://github.com/jupiterjs/javascriptmvc/blob/master/js#L13)) reference incorrect paths. In particular they reference "funcunit\java\selenium-server-standalone...".

The "java" portion of the path no longer exists in [funcunit](https://github.com/jupiterjs/funcunit), instead it should just be "funcunit\selenium" (fix slashes depending on windows / *nix).

**Comment by justinbmeyer** [comment]
Brian?

**Comment by justinbmeyer** [comment]
Brian?

**Comment by moschel** [comment]
no one should  be starting selenium this way anymore (it starts automatically in funcunit) so I removed this dead path
