### ISSUE TITLE
jsperf for minimal DOM requests

### ISSUE THREAD

**Issue by moschel** [donejs/donejs#273]

**Comment by ccummings** [comment]
JSPerf has gone way downhill and is borderline unusable at this point. So I created a JSBin that runs TodoMVC with CanJS and React and simulates adding an increasing number of todos to each. 

After the test is run, a line chart comparing the two is displayed: http://output.jsbin.com/vorahipohi/1

Here's the graph I got from running this 10 times (smooths out the weird bumps). This is what we should embed: http://output.jsbin.com/zemoxuxele/1/

**Comment by moschel** [comment]
The chart buries the lead a little bit IMO. It starts to diverge around 50 todos, but the scaling is so large (b/c of including the 1000 items case) that you can't really tell. I'd either remove 500, 750, and 1000, or have 2 graphs - one for smaller and one for larger numbers of todos - so you can more closely see the 50-250 todo cases (since these are more realistic anyways).

**Comment by moschel** [comment]
Could you please add this to the feature writeup with a short description? 

Should we also include the spinning circles, since that shows an advantage over Angular?

@justinbmeyer

**Comment by ccummings** [comment]
A closeup on the smaller numbers only shows us being marginally faster than React, the real good stuff is shown by 500, 750 and 1000.

The scaling that React forces is actually a good thing. If we try to fix that we weaken our case by showing React and DoneJS closer together.

I have a PR that adds the examples with a writeup. The charts are just placeholders for now.
