### ISSUE TITLE
longevity on the homepage

### ISSUE THREAD

**Issue by moschel** [donejs/donejs#274]
Creating an issue to track this.

We need a subtle way to show that DoneJS is not a "new" framework, but rather part of the JavaScriptMVC-->CanJS 8+ year lineage.

We haven't finalized how to show this, but a leading idea is to put some text under the description, above the npm installation steps. Maybe something that says "Not just another JavaScript framework" that links to http://donejs.com/About.html#section=section_Evolve (which will have a longer description of this).

We need to agree to 1) the right approach 2) a design and 3) the right text.

cc @atomgroomdesign @justinbmeyer @daffl

**Comment by moschel** [comment]
I think the text should be more explicit. Some options...
- 8 years in the making
- JavaScriptMVC's step child
- Steady, consistent improvements since 2007
- JavaScriptMVC + 8 years of evolution
- Innovating since 2007

**Comment by moschel** [comment]
From @atomgroomdesign 
- 8 years of JavaScript evolution

**Comment by moschel** [comment]
- DoneJS is JavaScriptMVC, reincarnated. We've been making steady, consistent improvements since 2007.
- DoneJS is JavaScriptMVC reincarnated, with 8 years of innovation.
- JavaScriptMVC, reincarnated, with 8 years of innovation.

**Comment by skylerraytaylor** [comment]
This mockup is approved and moving to implementation.

![donjs-homepage-hero-revised](https://cloud.githubusercontent.com/assets/3943219/10705954/b88db006-79a7-11e5-872c-8f0928e6992f.jpg)

**Comment by moschel** [comment]
@James0x57 finished this and its been merged. Closing.

**Comment by daffl** [comment]
No change in the text?
