### ISSUE TITLE
using package name breaks production loading

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#28]
instead of

```
<html>
	<body>
		<script src="/node_modules/steal/steal.production.js" 
               main="index.stache!done-autorender"></script>
	</body>
</html>
```

I had

```
<html>
	<body>
		<script src="/node_modules/steal/steal.production.js" 
               main="bitballs/index.stache!done-autorender"></script>
	</body>
</html>
```

**Comment by matthewp** [comment]
I think this is fixed in steal-tools 0.11.0-pre.8.  Previously steal-tools was producing bad bundle names when the main is an npm name.  

Note that the main in the script tag here should match what is used in pkg.system.main. So if you're using directories.lib both should include the package name.

**Comment by justinbmeyer** [comment]
I will verify.

**Comment by matthewp** [comment]
I'm going to close this because it's how all of our apps are [written now](https://github.com/donejs/chat/blob/master/src/index.stache#L44).  This is the commit that fixed the issue: https://github.com/stealjs/steal-tools/commit/80f4190240e8b232554f8d26d74e71483d2cac43
