### ISSUE TITLE
Unable to find "extension"'s helpers

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#29]
I get a bunch of warnings like:

2can.js:262 WARN: can/view/stache/mustache_core.js: Unable to find helper "asset".
can.js:262 WARN: can/view/stache/mustache_core.js: Unable to find key or helper "isProduction".

looking into `extensions.js` it's not clear how this is supposed to be used.  A config dependency?

**Comment by matthewp** [comment]
`asset` and `isProduction` are helpers that only exist in server side rendering.  I'm not sure what the best solution is to make these warnings go away.

**Comment by justinbmeyer** [comment]
I think we should have an `isProduction` at least.  Lets talk about `asset`.  We could simply add a dummy helper to make the warning go away.

**Comment by matthewp** [comment]
We can add a dummy helper but where?  The ssr extension is only applied on the server.  I guess done-autorender could make those be noops in the client.

**Comment by matthewp** [comment]
Going to add the dummy helper in done-autorender on the client.

**Comment by matthewp** [comment]
This is fixed by https://github.com/donejs/autorender/issues/2 and https://github.com/donejs/donejs/commit/679bb4a8b0721a30fb4f307edeb419700bd94eed
