### ISSUE TITLE
JavascriptMVC with Google App Engine

### ISSUE THREAD

**Issue by CostaDave** [donejs/donejs#29]
I am trying to use JavscriptMVC in a GAE project and I am running into some problems when it is loading.  Firebug shows that all of the .js files are being loaded, but when it comes time to load all of the .ejs files, it breaks.  It shows them as 200 OK, but it does not seem to like the mime type.  Anyone ever dealt with this or has anyone ever successfully deployed JMVC with App Engine?

Thanks

**Comment by justinbmeyer** [comment]
This isn't a bug with JMVC so please ask it on the forums.  thanks.
