### ISSUE TITLE
Make a contribution guide

### ISSUE THREAD

**Issue by moschel** [donejs/donejs#295]
I'm disabling the link on the homepage to the contribution guide for now. At some point we should make one and bring the link back.
- [ ] document sub projects like https://github.com/donejs/generator-donejs/issues/135

**Comment by chasenlehara** [comment]
The Contribution Guide still isn’t up on the website.
<img width="468" alt="screen shot 2016-07-12 at 9 21 10 am" src="https://cloud.githubusercontent.com/assets/10070176/16774721/2529263a-4812-11e6-82b0-3d3b73bca29b.png">

**Comment by chasenlehara** [comment]
It’d be great if this guide showed how we use the [Difficulty - Easy](https://github.com/donejs/donejs/issues?q=is%3Aopen+is%3Aissue+label%3A%22Difficulty+-+Easy%22) label in our repos to make it easy for new contributors.

**Comment by matthewp** [comment]
@chasenlehara do you plan on taking this on? If not I'd like to remove it from the 1.0 epic.

**Comment by chasenlehara** [comment]
Yes, I’ll aim to work on it this week.
