### ISSUE TITLE
Click to play videos, hide controls

### ISSUE THREAD

**Issue by moschel** [donejs/donejs#297]
The videos in the caching section have controls that cover part of the video itself.

http://donejs.com/Features.html#section=section_CachingandMinimalDataRequests__Howitworks__Combiningrequests

They should have controls that hide, and that require click to play.

**Comment by moschel** [comment]
![2015-10-25_1326](https://cloud.githubusercontent.com/assets/22180/10717091/163bae72-7b1c-11e5-9109-f318790db239.png)

**Comment by moschel** [comment]
@James0x57 could you please take a look at this tomorrow morning? I think there's some JS that is causing the mouseover effect to happen. We want to deactivate that in the Features page (really everywhere but the homepage). All the videos in this page should be the normal click to play types.

**Comment by JaneOri** [comment]
All set, live!
