### ISSUE TITLE
body click not triggered.

### ISSUE THREAD

**Issue by julesbou** [donejs/donejs#3]
I have this in a controller <em>(doesn't work)</em>:

<pre>
'body click': function( el ) 
{
     alert('ok');
},
</pre>

When i try this:

<pre>
$('body').click(function(el) 
{
    alert('ok');
});
</pre>

It's work.

This sound weird, please can you take a look at this issue.
Many thanks

**Comment by jupiterjs** [comment]
This won't work unless you're in a main controller or put an element controller on the document.Element.  A controller can only listen to elements 'within' it's element.  The body is outsite almost everyone.

if you want to listen to the window being clicked, there might be windowclick as an action, or at lease you can do :

this.bind(document.body,"bodyClick")

in your controller's init.

Please read up on controller in the docs for a better explanation.

Also, this belongs in the jQueryMX bugs, but that's ok.
