### ISSUE TITLE
Cordova app some times closes in iOS

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#311]
This happens when you run `donejs build cordova` and the simulator launches.

Cannot pin down what makes it happen vs not happen. I don't think it has anything to do with our code but perhaps something we are doing wrong with the Cordova options.

If you then launch it again from the home screen it works.

**Comment by justinbmeyer** [comment]
@matthewp when you say:

> If you then launch it again from the home screen it works.

it keeps working ... never closing again?

**Comment by matthewp** [comment]
Until you rebuild, yes. But for me it might not work the first time you launch it from the home screen (might take a second attempt), so I'm going to look into it tomorrow. Could also be my version of simulator, going to ask others to try it.

**Comment by justinbmeyer** [comment]
I'm going to close this as I don't think anyone else has reported it.
