### ISSUE TITLE
Model destroy - need attributes

### ISSUE THREAD

**Issue by marknadig** [donejs/donejs#32]
Similar to this question:
http://forum.javascriptmvc.com/topic/destroy-method-signature-on-model?reply=true&remember=604800&securemode=false

I have a nested route in a rails app and need additional attributes of the model instance to form it correctly. Currently only ID is passed into Destroy.

Last word from Justin on that thread "I need to think about how to make something like this a little easier."

Any more thoughts on this? Would like to be able to refer to all attributes on model in destroy().

**Comment by justinbmeyer** [comment]
this belongs in jquerymx
