### ISSUE TITLE
Chat Guide: nw wording

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#322]
Why does it say:

> We can answer most prompts with the default except for the version which needs to be set to the latest stable version (currently 0.12.3). 

When it appears you can simply hit enter and it will pick latest?

**Comment by matthewp** [comment]
Does the latest work? When that was written the latest was a beta without an OSX download.

**Comment by justinbmeyer** [comment]
Didn't try. The language is confusing either way.

**Comment by matthewp** [comment]
I don't see anything confusing about it, what would you suggest?
