### ISSUE TITLE
donejs add nw twice

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#323]
If you run this twice, it doesn't seem to update `build.js`. try with different version numbers.

**Comment by phillipskevin** [comment]
We only update `build.js` if it does not already contain `nwOptions`. Otherwise we would have to parse `build.js` and update its AST in order to change it correctly. We can do this, but once it is written it's relatively easy for a user to update one of the options.

**Comment by justinbmeyer** [comment]
The alternative would be to add some comments like:

```
// start - generated by `donejs add nw`
CODE
// end - generated by `donejs add nw`
```

And then just replace the CODE.

**Comment by matthewp** [comment]
I prefer the AST option, I like to keep my scripts as readable as if they were hand-written.

**Comment by justinbmeyer** [comment]
It would still be readable. And this gives people a warning not to touch.

**Comment by daffl** [comment]
I'm not sure if this is really important. The AST options sounds like a lot of work just to not have a user update their `build.js` manually.
`donejs-nw` and `donejs-cordova` should probably throw an error when you try to run it twice though.

**Comment by matthewp** [comment]
On second thought I don't think comments would be such a terrible thing. @moschel made a mistake the first time and tried running it again so he did run into this issue.

**Comment by phillipskevin** [comment]
Any issues with me merging and publishing these to close this issue? 
https://github.com/donejs/donejs-nw/pull/2
https://github.com/donejs/donejs-cordova/pull/13

cc @justinbmeyer @matthewp @daffl

**Comment by matthewp** [comment]
Nope, go for it.
