### ISSUE TITLE
Pangea graphic

### ISSUE THREAD

**Issue by moschel** [donejs/donejs#329]
Making the GIF that shows JMVC splitting into subprojects and re-joining to form DoneJS

**Comment by atomgroom** [comment]
First Animation

![pangea-001](https://cloud.githubusercontent.com/assets/5687712/10802079/a84e0ce2-7d88-11e5-8c75-2b0bcd6341dd.gif)

**Comment by justinbmeyer** [comment]
@moschel is there something you're going to do with this?
