### ISSUE TITLE
bit-c3 error on features page

### ISSUE THREAD

**Issue by moschel** [donejs/donejs#336]
![2015-10-27_1156](https://cloud.githubusercontent.com/assets/22180/10765986/61fea386-7ca3-11e5-8580-9c019c2f32f2.png)

**Comment by moschel** [comment]
Same error happens here: http://jsbin.com/puwesa/1/edit?html,output

**Comment by Alfredo-Delgado** [comment]
I can't reproduce the error, but added a check to the line in the file causing the error and @julia-allyce is no longer seeing those errors.

**Comment by moschel** [comment]
seems fixed for me too
