### ISSUE TITLE
donejs -v or donejs -V

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#349]
Currently it's `donejs -V` as the short version of `--version`, is a capital V more common?  I feel like lowercase v is more common. I tried on a few commonly used utilities, node, npm, and man are lowercase v, ssh, curl and grunt are uppercase V.  What the v.

**Comment by marshallswain** [comment]
I tested this out naturally a couple days ago.  My inclination was to try -v.  When that didn't work, I didn't even think of trying -V, but went straight to --version.

**Comment by daffl** [comment]
I think we should stick with what Commander provides. It actually doesn't look that easily changeable.

**Comment by daffl** [comment]
Closing as per my last comment. I think in the docs we should use `--version` if possible.
