### ISSUE TITLE
javascriptMVC 3.2.2 Fununit/run on Windows generate broken page URL

### ISSUE THREAD

**Issue by Zhankevich** [donejs/donejs#35]
When start test with phantomjs like this
js.bat funcunit/run phantomjs plugins/publish_panel/funcunit.html
It generate  file path starting with file://  !!!! But windows need file:/// (plus one '/' ).

I found what is wrong. In funcinit/run file we have
FuncUnit.funcunitPage = FuncUnit._getPageUrl(page, opts.coverage, FuncUnit.coverageIgnore);
There are two function with name _getPageUrl(). One is in steal/browser/browser.js and one in funcunit/commandline/util.js
But funcunit/run use first one where i have found ERROR in 38 line: 
page = "file://"+cwd+"/"+page; - but must be: page = "file:///"+cwd+"/"+page;

**Comment by polgfred** [comment]
`cwd` should already begin with a slash.

**Comment by Zhankevich** [comment]
On Window cwd start with disk name ( c:\work ). Maybe you have to check for system type or use _getPageUrl() function from steal/browser/browser.js, where it also change slashs to one type

**Comment by moschel** [comment]
This has already been fixed in master:

https://github.com/jupiterjs/funcunit/commit/786d4b525953f1df74b2ab6c1ca680aedbca336c
