### ISSUE TITLE
donejs add app: Giving an absolute path for src folder breaks things ~5

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#353]
if someone gives the `src` folder an absolute path, it breaks at least live-reload it seems.  We should detect an absolute path and either warn the user or convert it to a relative path.

**Comment by frank-dspeed** [comment]
No you should not warn lol you should handle that maybe :) so that even that works ? :) +1

**Comment by Sinjhin** [comment]
See https://github.com/donejs/generator-donejs/pull/150

**Comment by phillipskevin** [comment]
This was fixed on `major` but not on `master` and so it was never released. Reopening while we get it put in the right place.

**Comment by marshallswain** [comment]
I think this is what was breaking my demo page, here: https://github.com/stealjs/steal-react-jsx/issues/8

**Comment by phillipskevin** [comment]
Since we're focused on 1.0, going to close this since it is fixed there.
