### ISSUE TITLE
better UX for matrix tooltips

### ISSUE THREAD

**Issue by moschel** [donejs/donejs#357]
Right now, the tooltips require JS before they render anything. The takes several (more than 5) seconds before the JS executes on my desktop with a good connection, so if you click before that, nothing shows up. Could this progressively enhance better? For example, could we have the images contain alt tags, which are replaced by the data- attributes for tooltips after the JS loads?

**Comment by atomgroom** [comment]
Hey @moschel ,

That's actually a really great idea. I do not have any issues on my end, if I refresh and click, I get the the tooltip immediately on the live site.  I think this would require a JS dev to implement your example.  Do we have any one available to work on that? I'll try to think of some other options too.
