### ISSUE TITLE
pluginifyjs does not parse EJS correctly

### ISSUE THREAD

**Issue by reykjavikingur** [donejs/donejs#36]
I am using EJS templates in an app, but when I run pluginifyjs on it, the resulting JS file has the EJS code concatenated directly into it. Trying to load this file in a browser throws an error: "Illegal XML character '<%'". The pluginifyjs script should parse EJS code into regular JS before inserting into the final JS output, so that it is possible to embed EJS files in applications.

**Comment by justinbmeyer** [comment]
this is a bug with steal, please move it there.
