### ISSUE TITLE
Add warning that npm 1.x is not supported

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#370]
npm 1.x doesn't support passing arguments into scripts which causes `donejs build cordova` to fail.

**Comment by daffl** [comment]
We could hard-code `donejs build` to run `node build` instead of the NPM script.

**Comment by daffl** [comment]
On the other hand it's a single command to update your NPM and I don't think it's too much to ask to use a 2.x version.

**Comment by matthewp** [comment]
Here's the open donejs-cli PR: https://github.com/donejs/cli/pull/9

**Comment by matthewp** [comment]
This was merged, waiting on the next donejs-cli release to close.
