### ISSUE TITLE
Quick start guide: update some text

### ISSUE THREAD

**Issue by ilyavf** [donejs/donejs#371]
1. "by updating messages/messages.stache" to "by updating **src/**messages/messages.stache"
2. "This is done by adding dynamic imports for the home.component and chat/messages/ components": change "chat/messages/" to "**chat-messages**" or to "**messages/**".
3. For

```
<a href="{{routeUrl page='chat' }}"> 
```

it would be nice to explain how routeUrl gets called on click.

**Comment by moschel** [comment]
@ilyavf for number 3... routeUrl doesn't get called on click, it's a helper that generates an href. Not sure what you mean by that one. Maybe we can discuss.
