### ISSUE TITLE
can-import relative modules causes an exception in the build/live-reload

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#372]
It's because done-autorender and can/view/stache/system append moduleNames to the `bundle` array without normalizing them.

**Comment by daffl** [comment]
Would this hold off a release? I don't think we're talking about can-importing relative modules anywhere.

**Comment by matthewp** [comment]
It's easy to fix.

**Comment by matthewp** [comment]
- [x] - canjs issue: https://github.com/bitovi/canjs/issues/2037
- [x] - done-autorender issue: https://github.com/donejs/autorender/issues/13

**Comment by matthewp** [comment]
This is verified.
