### ISSUE TITLE
Support Node 4.0 and npm 3.0

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#376]
Lets add support to Node 4.0 and npm 3.0.

**Comment by marshallswain** [comment]
What parts need to be updated?  I just did the Quick Start Guide using Node v4.2.1, and it seemed to work perfectly.  Using donejs -V 0.5.3

**Comment by justinbmeyer** [comment]
I think it's npm that's the bigger problem.

**Comment by matthewp** [comment]
Here's the system-npm issue: https://github.com/stealjs/system-npm/issues/72

**Comment by niallobrien** [comment]
I got errors installing with node 4.2.1 and npm 2.14.7.

**Comment by phillipskevin** [comment]
@niallobrien did you try continuing after installing? I was able to complete the quick start guide with the same versions. I also got some errors like this, but they didn't prevent anything from working correctly.

```
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
9 errors generated.
make: *** [Release/obj.target/validation/src/validation.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
```

**Comment by sireskay** [comment]
Any ETA on this?

**Comment by justinbmeyer** [comment]
@skolade My guess is over 2 weeks.  We are working on improving our test infrastructure to make verifying all the different of operation systems, node, and npm versions are working right.

Once that is done, we'll have to make the modifications to our libraries.  Steal is probably the most challenging, and I think @matthewp has already made progress.  This is our highest priority effort right now.  @daffl is working on it almost full time.

**Comment by matthewp** [comment]
Tracking the npm3 support in Steal here: https://github.com/stealjs/steal/issues/521

Also note that will need to update generator-donejs so that it enables Steal/npm3 if the user is using npm3.

**Comment by matthewp** [comment]
Issue: https://github.com/donejs/generator-donejs/issues/55

**Comment by daffl** [comment]
This is done, verified to be working and released.
