### ISSUE TITLE
jquerymx download builder is out of date

### ISSUE THREAD

**Issue by ecentinela** [donejs/donejs#38]
The downloaded scripts are not the same as the complete download.
For example, shipped jquery version is 1.6.4

**Comment by polgfred** [comment]
I'll try to take a look at this today.

**Comment by ecentinela** [comment]
Is there any jupiterjs repository that I can observe to see when this issue is resolved?

**Comment by polgfred** [comment]
These changes would go into jupiterjs/javascriptmvc-site.

**Comment by polgfred** [comment]
I'm not seeing this. I just downloaded the complete JavascriptMVC and a custom bundle from the jQueryMX download builder. Both are showing jQuery 1.7.1.

**Comment by ecentinela** [comment]
Now is fine.
Seems someone updated the site this weekend.
