### ISSUE TITLE
Development server crashes during Getting data from the server

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#38]
http://donejs.com/Guide.html#section_GettingandDisplayingDatafromtheServer

User ran into this issue, would be good to track down the problem with him/her.

**Comment by justinbmeyer** [comment]
@matthewp what user?  @daffl could not reproduce.

**Comment by marshallswain** [comment]
Maybe this was the issue where if the API server wasn't running it would crash the development server as soon as the client requested data from the API.

**Comment by matthewp** [comment]
@justinbmeyer The person that emailed you a month ago.
