### ISSUE TITLE
Steal to support cache busting

### ISSUE THREAD

**Issue by jtsoi** [donejs/donejs#39]
(Moving to a new issue, as per Justin's request.)

As JMVC gets traction and is used more and more in production, there is a clear need for cache busting in steal.

Something along these lines:

Current way to load an app in prod is:

`<script type="text/javascript" src="steal.production.js?myApp"></script>`

What if there would be an option to add: 
`<script type="text/javascript" src="steal.production.js?myApp&_=123456789"></script>`

Inspired by jQuery getScript cache busting.

The _ variable would propagate to all dependency calls steal makes.
This way you could change the _ variable to the build number for your app and be sure that 
users always get the latest code and we can turn up cache to forever. (or git revision)

(Maybe "v" is a better varible than "_" )

**Comment by justinbmeyer** [comment]
Please add this to steal's issues.  Thanks!
