### ISSUE TITLE
`donejs build`: a better error message is needed when package.json is malformed.

### ISSUE THREAD

**Issue by marshallswain** [donejs/donejs#391]
While going through the quick start guide, I missed a comma while adding the "system.envs" section to the package.json.  Running donejs build with a malformed package.json produces the output found below.  It does say that it "Could not run `build`" but then shows CLI usage info, which lead the developer to think that they've typed the command incorrectly.  Checking the docs shows that you typed it correctly, but it's not working.  Can we detect a malformed `package.json` and give a better error?

![screen shot 2015-10-29 at 5 13 44 pm](https://cloud.githubusercontent.com/assets/128857/10834667/e49c79b2-7e60-11e5-90bb-ff9bd30a6ba9.jpg)

**Comment by matthewp** [comment]
Great idea.

**Comment by matthewp** [comment]
https://github.com/donejs/cli/blob/master/bin/donejs#L90  Is where needs to be changed. Perhaps we can parse the error message.
