### ISSUE TITLE
add memory safety to the features page ~8

### ISSUE THREAD

**Issue by moschel** [donejs/donejs#395]
Talk about the cleanData hook, cleaning up event handlers when removing components, _bindings counting and removing stale model instances from memory.

Are there other things we do for memory safety?

Find out if React/Angular do any of these and compare them.

**Comment by justinbmeyer** [comment]
We should probably hit this on CanJS.

**Comment by matthewp** [comment]
Thinking out loud here, we should talk about:

* Event listeners created by template event bindings are automatically cleaned up.
* Ditto for event bindings created with controls.
* dom-data is cleaned up (not automatically though, I think).

As far as comparing this to other frameworks, I would assume they all do the same thing, would be very surprised if not.

**Comment by justinbmeyer** [comment]
Our stuff works a bit different. You can mutate the DOM directly and our stuff should clean itself up. Everything else you likely need to go "through the framework".

**Comment by matthewp** [comment]
I think you are talking about when MutationObserver is available. I'll add something about that too.

**Comment by justinbmeyer** [comment]
Every nodelist is designed to clean itself up if its elements are removed. This means you can render the contents of a 3rd party tabs widget with stache. If the tabs widget removed those elements, all bindings would go with it.
