### ISSUE TITLE
Guide Integration Test

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#396]
We need a test that runs through the guide and makes sure everything is working.

**Comment by matthewp** [comment]
We need to be able to take the guide's markdown and spit out a series of tests.

Likely we need some documentjs tags to direct what the tests should do.

**Comment by matthewp** [comment]
Ran through the guide and took notes on needs for this issue:

### Needs

Keep the app open the entire time in a browser to ensure live-reload works

### Guide Actions

npm install
run commands (doings init, donejs add, etc)
Update contents of a file
Launch a browser and click stuff
Update partial contents of a file (json)

### Guide Tests

Client Side
Server Side (mocha)
Testing within a simulator / emulator

**Comment by justinbmeyer** [comment]
Ideally, the changes to certain files will all be reference-able by documentjs.  That way we can keep things consistent easy.

**Comment by matthewp** [comment]
My initial idea is to use tags in the markdown above code blocks like:

``````
@test-command
@test-verify install-verify.js

\```
npm install donejs -g
\```
``````

Where `install-verify.js` is a Node script that runs after the command completes, runs Mocha tests or something.

Some times the tests will need to be ran within the open browser window, some times as Node scripts, so need to figure out how to declare all of that.

But the goal is that the guide is the source of truth and we don't have to maintain separate files that have all of the same code snippets.

**Comment by justinbmeyer** [comment]
I think the code snippets are the source of the guide, not the other way around.  At least, I think that approach is much easier.

**Comment by justinbmeyer** [comment]
I think it would just take a custom tag like 

```
@source-ref test/guides/quick/step_1_app.js 2-20
```

the 2-20 is if we just wanted to show a particular spot.

**Comment by matthewp** [comment]
I've thought about that as well, my concern is will that interfere with other tags like the code highlighting that was added?

**Comment by justinbmeyer** [comment]
code highlighting would work fine with this.

**Comment by matthewp** [comment]
Going to work back from _immediate needs_ to _automating everything_

## Immediate
- We need to be able to run the donejs-chat tests in Travis on demand.

## Need badly
- We need to be able to run both guides on a Windows CI.
- We need to be able to run the place-my-order tests in Travis on demand.

## Need slightly less badly
- We need to be able to trigger the tests to run whenever a sub-project is published.
- We need to have it send emails to OS team when there is a failure.

**Comment by justinbmeyer** [comment]
@matthewp is this closed?

**Comment by matthewp** [comment]
Only the donejs-chat guide test is running in CI.

**Comment by matthewp** [comment]
PMO part is missing, but has its own issues in #528 and #529.
