### ISSUE TITLE
js jquery/generate/app changes the case of the path given

### ISSUE THREAD

**Issue by daredevildave** [donejs/donejs#4]
Running the command:
    ./js jquery/generate/app /home/dave/Projects/mvcapp

Generates the new app in:
    /home/dave/projects/mvcapp

On case-sensitive OS's this is incorrect.
OS: Ubuntu 10.04
Release: 3.01

**Comment by lastzero** [comment]
This makes sense, as you want a common behaviour on the different platforms/filesystems. If you allow uppercase, I am sure some windows/virtualbox user will check this in as "working perfectly" and because some include uses lowercase, the code will break on a normal Linux (that means on the Web server, in the worst case).

Is there any reason why you provide an absolute path rather doing this?

./js jquery/generate/app mvcapp

**Comment by daredevildave** [comment]
Well, I have the jmvc installed somewhere like:
    /home/dave/Projects/jmvc
and I want to create the app in:
    /home/dave/Projects/mvcapp

From the first folder if I run:
    ./js jquery/generate/app ../mvcapp
I get a FileNotFound exception from java

So I'm using the full path, however, on Ubuntu it doesn't get created where I specify as it changes the path to all lowercase.

**Comment by lastzero** [comment]
Works for me:

<pre>./js jquery/generate/app mvcapp</pre>


Why do you use ../ ?

**Comment by daredevildave** [comment]
I don't want the app to be created in a sub-directory of the jmvc folder.

**Comment by jupiterjs** [comment]
Why don't you want it there?  It's how most apps are organized.  I could probably make ../ work.

**Comment by jupiterjs** [comment]
Btw, if you want it to work real quick, you can generate an app in your folder, move it where you want, then you just have to change the path to steal in the .html files.

**Comment by daredevildave** [comment]
I've been working with it in a sub-folder. It wasn't clear at the start that the created app would be dependent on files in the jmvc folder. My usual folder structure is:

```
~/Projects/appname/files
```

I thought that would be more logical, but I I'll rename my jmvc folder to appname and have:
    ~/Projects/appname/appname/...
                       jquery/...
                       steal/...
                       etc

Perhaps it should error/warn if you try and install it outside of the main folder.

**Comment by jupiterjs** [comment]
yeah, I'll work on this sometime this week hopefully.

**Comment by justinbmeyer** [comment]
I'm moving this to steal's issues where it belongs:

https://github.com/jupiterjs/steal/issues/77
