### ISSUE TITLE
menu broken on ios Chrome

### ISSUE THREAD

**Issue by moschel** [donejs/donejs#403]
To reproduce, on an actual phone, open chrome to the features page or a guide.

Click one of the headers like "Performance Features". It seems to load something but the menu doesn't expand.

The + icon also doesn't do anything.

I can't reproduce this on a simulator or on Chrome desktop simulating ios.

**Comment by Alfredo-Delgado** [comment]
I was able to reproduce. (I can’t click on the `x` to close Table of Contents or expand the options.)

![photo](https://cloud.githubusercontent.com/assets/798836/10888092/31c7a4ce-8158-11e5-9049-d155d1966962.PNG)

**Comment by moschel** [comment]
Still doesn't work. Slightly better but the minimize and maximize buttons don't work.

**Comment by moschel** [comment]
I'll try to record a video later.

**Comment by moschel** [comment]
Not sure how well this shows up, but I'm clicking on the + and - icons over and over. The behavior that results is strange and unpredictable. Sometimes it kinda works, usually not. When it works, it selects a random row of the sub-categories.

![bug2](https://cloud.githubusercontent.com/assets/22180/10901449/275177de-81b4-11e5-9d3e-33a3ef90ea5e.gif)

**Comment by Alfredo-Delgado** [comment]
I checked out donejs.com with Chrome on a Nexus 7 running Android 5.1.1 and it exhibited some of the same long scroll bugginess that we're seeing in iOS.

The initial bug (main items aren't expanded) was only happening on iOS because there was some code particularly targeting iOS responsible for that.
