### ISSUE TITLE
Open source license information is missing

### ISSUE THREAD

**Issue by AnnotatedJS** [donejs/donejs#412]
The first claim on the donejs homepage is that "DoneJS is an open source JavaScript framework".

However, there is no license information to be found on the homepage, nor on the DoneJS Release blog post of bitovi nor on the done.js Github repository page

**Comment by justinbmeyer** [comment]
It is MIT and in our package.json

https://github.com/donejs/donejs/blob/master/package.json

But we can add it other places too.

**Comment by AnnotatedJS** [comment]
Thanks for the response. I am used looking for the license information as a separate file in the main folder of the repository.

**Comment by bkonkle** [comment]
I'd definitely recommend adding a LICENSE file. The MIT designation in package.json indicates which license you're using, but it doesn't constitute an actual license agreement. If there were a legal challenge, the fact that there is no license text would likely mean that the code is considered proprietary.

**Comment by matthewp** [comment]
Yes, you're right, we do need a LICENSE file, some companies won't use a project without one.

**Comment by matthewp** [comment]
@alexisabril you did this for some other projects, how do you determine which year to use?
