### ISSUE TITLE
Project name should validate against npm guidelines (eg. no caps, url-friendly)

### ISSUE THREAD

**Issue by DesignByOnyx** [donejs/donejs#415]
I just created a project and gave it an invalid name:

```
donejs init
$ Project name: My Project
...
```

This resulted in invalid paths used in `index.stache`:

``` html
<can-import from="My Project/styles.less!">
<can-import from="My Project/app" export-as="viewModel" />
```

Npm has pretty specific guidelines on naming a project - `donejs init` should provide some sort of validation or at least instruction on this: https://docs.npmjs.com/files/package.json

**Comment by matthewp** [comment]
Thanks!  Can you also file this same issue in https://github.com/donejs/generator-donejs?
