### ISSUE TITLE
Features page SSR: unclear wording

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#416]
http://donejs.com/Features.html#section=section_Server_SideRendered__Howitworks

> (single context is optional, so reload is something you can opt into)

I'm not sure what this means at all.

**Comment by matthewp** [comment]
> Some systems, even if they do use a virtual DOM, require a new browser instance entirely, or at the very least, reloading the application and its memory for each incoming request,

I don't know of any frameworks that do that, which do?

**Comment by justinbmeyer** [comment]
Typically JS frameworks do not, but this is the de facto way things like php and rails work.

**Comment by matthewp** [comment]
Going to remove the part about single context being optional, I'm not aware of any methods to use DoneJS in a php kind of way.

**Comment by justinbmeyer** [comment]
I think we'd like to make it optional.  This would be great for apps that don't need as fast SSR performance, but would like to make globals work without any problem.

**Comment by matthewp** [comment]
I'd research to see if there's any cgi options for use with Node.

**Comment by justinbmeyer** [comment]
@matthewp Let me clarify what I was thinking (didn't read this whole issue) ... essentially, we re-load all modules every time.  Every render would use its own version of CanJS, making memory leaks and problems with globals much more rare.

**Comment by matthewp** [comment]
Yeah, I understand, this is cgi essentially. There may be existing packages/tools to make Node work as a cgi interface. I would do this as a new project to experiment.

**Comment by matthewp** [comment]
It might also be possible to do that by cloning Steal but re-using the source code and merely re-executing that. I filed https://github.com/donejs/done-ssr/issues/216 to discuss that feature. Will keep this one about the documentation.

**Comment by matthewp** [comment]
Fixed by #816
