### ISSUE TITLE
place my order bugs

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#418]
https://gitter.im/donejs/donejs?at=56397f03a530033014e408a9

https://twitter.com/niall_obrien/status/661532076039135233

**Comment by daffl** [comment]
I can verify that this is an issue in Safari with the current place-my-order.com but not in the guide walkthrough with the latest version of everything. I will update place-my-order.com with that version shortly.

**Comment by daffl** [comment]
Verified this is working in the latest place-my-order guide and the version deployed via https://github.com/donejs/place-my-order/pull/83
