### ISSUE TITLE
Support for Electron by Atom.io ~13

### ISSUE THREAD

**Issue by FlipOneDev** [donejs/donejs#419]
Microsoft (Visual Studio Code), Google (Pixate design tool), Github (Atom Editor) and Slack (Slack Desktop Client) are just a few of the software vendors now using Electron (electron.atom.io) to power their desktop apps.

It's good you're now supporting NW.js, but it would be really wonderful, both for us developers and for DoneJS, if you will provide full support for Electron.

Looking forward to it! And I hope soon enough. :)

**Comment by daffl** [comment]
I approve. In fact, I'd like to start working on `donejs-electron` shortly. I've built a DoneJS Electron app at https://github.com/daffl/mysam but I haven't looked into how to bundle it all up (other than through an `npm install -g`).

**Comment by matthewp** [comment]
Just curious, what are the advantages of Electron over Nw.js?  Btw, anyone can create plugins that will work with `donejs add foo`, see the [donejs-nw](https://github.com/donejs/donejs-nw) project as an example.

**Comment by daffl** [comment]
I found it easier to use esp. with having a JS file with all your configuration as the entry point and I generally like the APIs more. Chromium isn't as tightly coupled so they can upgrade more quickly.

**Comment by daslicht** [comment]
Is there meanwhile a solution to get code highlight and errors in Atom ?

**Comment by justinbmeyer** [comment]
@daslicht not that I know.  But presumably you can use standard JS and handlebars highlighters.

**Comment by daslicht** [comment]
ok thanks

**Comment by matthewp** [comment]
Hey @Sinjhin, did you work on this previously?

**Comment by Sinjhin** [comment]
@matthewp Yes, see:
https://github.com/stealjs/steal-electron
and
https://github.com/donejs/donejs-electron

I also have some work done on generator-donejs that I can push to a branch. It will take all three repos working together for this to work.

If I remember correctly I got the generator part working to build an electron app with some bugs that still need to be worked out when I had to take a break from it.

**Comment by matthewp** [comment]
Awesome, I'm going to move this to 1.1 as it likely won't make 1.0.

**Comment by justinbmeyer** [comment]
Moving this to 1.0 for a quick investigation spike.  If it seems easily doable, it will be part of 1.0.

**Comment by matthewp** [comment]
This is doneish.

**Comment by matthewp** [comment]
Actually, need to wait for https://github.com/donejs/donejs/pull/846

**Comment by matthewp** [comment]
This can be closed now.
