### ISSUE TITLE
donejs-native

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#421]
React has a  "react-native" package that uses their virtual DOM to translate to native API calls. The advantage of this over Cordova is that you are using the native UI so performance is better. Other frameworks are working on this same thing, I think Angular has said they will be using react-native as their back end.

Conceptually this could work similar to how worker thread rendering works and could reuse some of that code, especially [dom-patch](https://github.com/canjs/dom-patch).  We would render to can-simple-dom and then instead of applying the patches to a real DOM they would re-render the React virtual dom.

**Comment by ericelliott** [comment]
:+1:

**Comment by justinbmeyer** [comment]
Most people that I've talked to who have tried react native have struggled with it.  I'm not totally sold it's a good long term investment.

**Comment by matthewp** [comment]
@justinbmeyer Can you be more specific than that? From what I've read it requires some compromises (must use Flexbox for example) and might not be easy to use 1 codebase for app + web but the benefit being a better native experience. So the use-case would be that you're primarily interested in developing a native app but want to use a familiar technology (donejs) to do so.

**Comment by justinbmeyer** [comment]
It's mostly a gut feeling that the "web" is the stack, not JavaScript. That the performance gains will be minimal for most apps over the next few years of improving hardware and DOM engines.

**Comment by frank-dspeed** [comment]
@matthewp Question what is about all the cordova nativ plugins for hardware support like cam, mic, viewport and many more is that still working then?

 i am not sure about that but a cordova app most times also will use the device hardware and cordova has a massiv stack of that hardware support

**Comment by matthewp** [comment]
I no longer support this proposal.
