### ISSUE TITLE
deploy to alternate account fails but command line shows success

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#428]
Try to create a firebase account with a different google account.

Try to deploy to it after already logging in.  The deploy shows that it was successful, but it wasn't.

**Comment by matthewp** [comment]
This is an old one, going to try and replicate with these steps:

1. Be logged into Account A.
2. Create a firebase with Account B.
3. Use Account B's firebase name when setting up deployment.
4. Run `donejs deploy` and see what happens.

Now that we've switched off of donejs-deploy this might already be fixed but I'll test it anyways.

**Comment by matthewp** [comment]
This is no longer a problem, get an error message now:

<img width="682" alt="screen shot 2017-02-13 at 10 46 23 am" src="https://cloud.githubusercontent.com/assets/361671/22890329/0a1ce65c-f1da-11e6-9ba6-1493c1aad887.png">
