### ISSUE TITLE
Your tutorials about get started are outdated if using the bat file! (Installing with a script)

### ISSUE THREAD

**Issue by totty90** [donejs/donejs#43]
1) Here [http://v3.javascriptmvc.com/docs.html#&who=developwithgit] go to "Installing with a script" and click on the "Windows". The link is dead - page not found: https://github.com/jupiterjs/javascriptmvc/raw/master/scripts/getjmvc.bat

Please update this.

2) If you change "jupiterjs" to "bitovi", because your project migrated you will get: https://github.com/bitovi/javascriptmvc/raw/master/scripts/getjmvc.bat
Now this works, but after run it will create the following folders: canjs, documentjs, funcunit, jquerypp, steal.. Wait a minute: jquerypp?? canjs??

Now in your tutorial at http://javascriptmvc.com/docs.html#!rapidstart have:
steal('jquery/class', function(){
  $.Class
})

Well, jquery doesn't exists. Now we have jquerypp, therefore all your tutorials are broken.

3) We can fix this too, change the example to:
steal('jquerypp/class', function(){
  $.Class
})
Now I get the following errors:
GET file:///D:/web/abc/can/lib/jquery.1.8.3.js  steal.js:1321
GET file:///D:/web/abc/can/construct/construct.js  steal.js:1321
GET file:///D:/web/abc/can/construct/proxy/proxy.js  steal.js:1321
GET file:///D:/web/abc/can/construct/super/super.js  steal.js:1321

4) I give up using git. I download the full static package and it works...

5) Using the zip file provided will not work with git... I don't know why but there is a problem with the funcunit folder...
I get "Not a git repository: /Users/daff/Jupiter/jmvc/..../modules/syn" in GitExtensions...

6) Removed the folder, I will might take a look later at this problem..

You should really do something about it because this sucks!
thanks for your time.

**Comment by justinbmeyer** [comment]
We just updated to a new version (3.3) in master last night, we deployed the docs and a new release today so everything should be fixed.

**Comment by alexisabril** [comment]
- we are deploying today(future tense)

**Comment by totty90** [comment]
Thanks.. I really thought it was not supported anymore (I checked the last commit and didn't seemed to be so) because of those problems in the documentation...
