### ISSUE TITLE
'donejs init' prompt to overwrite package.json 

### ISSUE THREAD

**Issue by cklanac** [donejs/donejs#44]
Running `donejs init` on a project that already has a package.json... donejs attempts to overwrite files. Instead, it should  (y/n) prompt in the terminal,  It says (Ynaxdh).

<img width="150" alt="upload" src="https://cloud.githubusercontent.com/assets/1008777/9386236/29711ebc-4720-11e5-859a-6334d46ed0e7.png">

**Comment by justinbmeyer** [comment]
Closing for #59.
