### ISSUE TITLE
donejs init fails installing DocumentJS

### ISSUE THREAD

**Issue by daffl** [donejs/donejs#440]
This is what I am currently seeing in v0.5.7:

<img width="1280" alt="screen shot 2015-12-15 at 11 58 03 pm" src="https://cloud.githubusercontent.com/assets/338316/11835372/d2f98000-a387-11e5-810e-4f1b146de235.png">

**Comment by daffl** [comment]
Looks like GitHub was down for a moment. It works now.

**Comment by justinbmeyer** [comment]
Why is github needed?
