### ISSUE TITLE
donejs init on an already init-ed project

### ISSUE THREAD

**Issue by Macrofig** [donejs/donejs#45]
When you run `npm init` on a project that was already init-ed, the prompt goes through it's files. It will only change a value that it prompted for, it won't affect the rest of the existing `package.json`.

When you do `donejs init`, we have to be careful because there are prompts from Yeoman that could potentially overwrite index files.  I get that it's more of a Yeoman issue but we could get around it by adding a prompt that does something like:
```
Regenerate base files? (y/N) _
```

`N` being the default when a project already exists. `Y` kicks off Yeoman and we can handle the overwriting prompts then.

**Comment by justinbmeyer** [comment]
Closing for #59
