### ISSUE TITLE
package.json defaults

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#455]
I think we should provide some defaults to avoid npm warnings:
- description - An awesome donejs app
- license - the "no license" license
- repository - not sure what to put here .... it would be nice to infer it ... but probably not possible unless there's a .git somewhere.

**Comment by matthewp** [comment]
@justinbmeyer NPM warnings are muted now because we use loglevel error, so this is probably not needed if it's about warnings. We could add it anyways just to have though.

**Comment by justinbmeyer** [comment]
> NPM warnings are muted now because we use loglevel error, so this is probably not needed if it's about warnings. 

This is only during `init` right?  Probably don't want it any other time.

**Comment by matthewp** [comment]
Issue moved to [donejs/generator-donejs #199](https://github.com/donejs/generator-donejs/issues/199) via [**ZenHub**](https://www.zenhub.com/)
