### ISSUE TITLE
PMO - Order History - Unnecessary requests

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#466]
The Order History page makes the following requests:

![place-my-order_and_new_issue_ _donejs_donejs](https://cloud.githubusercontent.com/assets/78602/12190764/27656cbe-b592-11e5-930e-683ce1d7f3d9.png)

This seems to be due to the fact the inline cache doesn't have everything it should:

```
INLINE_CACHE = {
  "orders": {
    "{\"status\":\"delivered\"}": [
      {
        "status": "delivered",
        "items": [
          {
            "name": "Ricotta Gnocchi",
            "price": 15.99
          },
          {
            "name": "Roasted Salmon",
            "price": 23.99
          }
        ],
        "name": "Justin",
        "address": "B",
        "phone": "123",
        "_id": "7yC7p9GWRjzJ6tEW"
      }
    ]
  }
};
```

new, preparing, delivery are all missing.

**Comment by matthewp** [comment]
I think it's probably the new way we add data with can-wait, it's not merging the sets that belong to the same key.

**Comment by matthewp** [comment]
Unfortunately can-wait's data is an array so it's something like this:

```js
[ { pageData: orders: {...} }, { pageData: orders: {...} } ]
```

In retrospect I wish the data was saved as an object where you have to provide a key. This way can-connect could (more easily) update orders.

**Comment by matthewp** [comment]
So what happens is can-connect pushes new data into the Request  that looks something like this:

``` js
[ { pageData: { orders: {...} }, { pageData: { orders: {...} } ]
```

And can-ssr merges these. We just need to merge them 2 levels deep, I believe.

**Comment by matthewp** [comment]
Here's the can-ssr issue: https://github.com/canjs/can-ssr/issues/105

**Comment by matthewp** [comment]
Verified this as fixed.
