### ISSUE TITLE
New project references "place-my-order"

### ISSUE THREAD

**Issue by akagomez** [donejs/donejs#469]
My project is called "scraplog" and somehow my `index.stache` references "place-my-order" in the production `<script>` tag's `main` attribute. 

```
<html>
  <head>
    <title>{{title}}</title>
    {{asset "css"}}
  </head>
  <body>
    <can-import from="scraplog/styles.less!" />
    <can-import from="scraplog/app" as="viewModel" />

    <h1>{{message}}</h1>

    {{asset "inline-cache"}}

    {{#switch @env.NODE_ENV}}
      {{#case "production"}}
        <script src="/node_modules/steal/steal.production.js"  main="place-my-order/index.stache!done-autorender"></script>
      {{/case}}
      {{#default}}
        <script src="/node_modules/steal/steal.js"></script>
      {{/default}}
    {{/switch}}
  </body>
</html>
```

**Comment by justinbmeyer** [comment]
Actually, I'm not sure this is a bug.  Did you re-init this folder?  

It seems like what you are showing is impossible from the current state of the `index.stache` template:

https://github.com/donejs/generator-donejs/blob/master/app/templates/src/index.stache#L17

**Comment by justinbmeyer** [comment]
Also, which version of donejs are you using?  0.6?

**Comment by akagomez** [comment]
Just ran `donejs init foobar` and got this for an `index.stache`:

```
<html>
  <head>
    <title>{{title}}</title>
    {{asset "css"}}
  </head>
  <body>
    <can-import from="foobar/styles.less!" />
    <can-import from="foobar/app" as="viewModel" />

    <h1>{{message}}</h1>

    {{asset "inline-cache"}}

    {{#switch @env.NODE_ENV}}
      {{#case "production"}}
        <script src="/node_modules/steal/steal.production.js"  main="place-my-order/index.stache!done-autorender"></script>
      {{/case}}
      {{#default}}
        <script src="/node_modules/steal/steal.js"></script>
      {{/default}}
    {{/switch}}
  </body>
</html>
```

**Comment by akagomez** [comment]
My `donejs` version is `0.6.0`.

**Comment by matthewp** [comment]
What are your steps to create the project? Are you doing:

```
donejs init project-name
```

or

```
mkdir project-name
cd project-name
donejs init
```

Both are valid.

**Comment by akagomez** [comment]
`donejs init project-name`

**Comment by matthewp** [comment]
what version of generator-donejs is in your node_modules folder? Can you check that file justin referenced above?

**Comment by akagomez** [comment]
My `generator-donejs` `index.stache` looks like @justinbmeyer's. The `main` attribute looks like this: 

`main="<%= name %>/index.stache!done-autorender"`

**Comment by matthewp** [comment]
Which version is in the package.json?

**Comment by akagomez** [comment]
`"version": "0.4.3",`

**Comment by daffl** [comment]
This looks like an issue of an older DoneJS version. The generator should use the project name for `index.stache` (see https://github.com/donejs/generator-donejs/blob/master/app/templates/src/index.stache#L17).

**Comment by daffl** [comment]
I can't verify this with the latest versions. Please reopen if it still happens after `npm cache clean` and reinstalling everything.
