### ISSUE TITLE
Forced to restart donejs develop process ~8

### ISSUE THREAD

**Issue by akagomez** [donejs/donejs#470]
When importing a component with `<can-import>` I entered the path incorrectly which caused a typical NodeJS "file not found" error to be thrown. After fixing the path the server would not respond. I was forced to kill/start the `donejs develop` process. 

![donejs-forced-process-restart](https://cloud.githubusercontent.com/assets/82166/12235559/92789bae-b842-11e5-8fd2-52c7136d5fa9.gif)

**Comment by matthewp** [comment]
This probably happens for any incorrect import, not just can-imports.  I'm guessing that steal-tools is the culprit.

**Comment by matthewp** [comment]
This is the underlying bug: https://github.com/stealjs/steal/issues/1057

I'm working on it now.

**Comment by justinbmeyer** [comment]
Can we have some sort of generic catch-all error handler that will essentially restart or shutdown everything?

**Comment by matthewp** [comment]
You can do that with processes. Have a super process that starts the web server as a subprocess, if an error occurs kill it and start a new one. The trouble would be detecting when that needs to happen.

**Comment by matthewp** [comment]
Fixed in Steal 1.2.5
