### ISSUE TITLE
Dependencies on git

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#473]
https://github.com/donejs/cli/pull/30

**Comment by daffl** [comment]
`devDependencies` shouldn't be installed when running `npm install donejs -g` though right?

**Comment by daffl** [comment]
Oh nevermind, it's in the `donejs` packages section.

**Comment by matthewp** [comment]
There's one remaining git dependency:

![gitdep](https://cloud.githubusercontent.com/assets/361671/12268004/ed0c6628-b918-11e5-9d0e-8b17489a6237.PNG)

This is owned by **divshot-push**, I've asked them to either publish / use https here: https://github.com/divshot/divshot-push/issues/3

**Comment by daffl** [comment]
Divshot is gone anyway. Can't we just remove it?

**Comment by matthewp** [comment]
That's true, we moved to firebase before the 0.5.0 release, we could just do a major version bump of donejs-deploy with divshot removed.

**Comment by justinbmeyer** [comment]
Let's do it.

**Comment by daffl** [comment]
Closed now via https://github.com/donejs/deploy/pull/43
