### ISSUE TITLE
Add Greenkeeper for DoneJS dependency updates ~2

### ISSUE THREAD

**Issue by daffl** [donejs/donejs#475]
http://greenkeeper.io is exactly what we need to keep the DoneJS dependencies up to date. Whenever a dependency gets updated and does not match the SemVer range it will issue a pull request with the updated `package.json` which will kick off CI.

**Comment by phillipskevin** [comment]
We'll do this once the `-alpha` versions get promoted to 1.0 finals.

**Comment by phillipskevin** [comment]
turns out I'm not an owner on the donejs repos, @matthewp do you want to take this one?

**Comment by matthewp** [comment]
Sure.

**Comment by matthewp** [comment]
This won't cause the donejs dependencies to be updated though, since those dependencies are stored in donejs-cli's package.json "donejs" field.

**Comment by matthewp** [comment]
It's set up now.
