### ISSUE TITLE
PMO: Tests do not pass in travis

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#476]
I'm not sure why: https://travis-ci.org/matthewp/place-my-order/builds/101914756

**Comment by daffl** [comment]
Does it work locally?

**Comment by matthewp** [comment]
Yep.

**Comment by daffl** [comment]
Also with Firefox 43?

**Comment by matthewp** [comment]
Yeah, that link is using 43.

**Comment by daffl** [comment]
I tried a fresh clone and checked out the branch and I'm getting

```
error "Error loading "jquery@2.2.0#jquery" at http://localhost:3996/node_modules/jquery/jquery.js
Error loading "jquery@2.2.0#jquery" from "place-my-order@0.0.0#test/test" at http://localhost:3996/src/test/test.js
Not Found: http://localhost:3996/node_modules/jquery/jquery.js" 
```

In Firefox.

**Comment by daffl** [comment]
That's probably because it still puts `jquery@^2.1.4`  in the `package.json`. Locking to 2.1.4 fixes it.

**Comment by daffl** [comment]
Closed via https://github.com/donejs/generator-donejs/pull/63 in the latest patch release
