### ISSUE TITLE
PMO: Going to Order History after the Order page causes an exception

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#477]
![err](https://cloud.githubusercontent.com/assets/361671/12275475/4600e9a0-b93e-11e5-8ebf-12d7551483be.PNG)

**Comment by matthewp** [comment]
This is not OS related, can be reproduced by clone https://github.com/matthewp/matthew-pmo doing an npm install, starting donejs api and donejs develop.

Restaurants -> State -> City -> Place My Order -> Order from Foo -> Order History

**Comment by justinbmeyer** [comment]
I'm checking this out now.

**Comment by justinbmeyer** [comment]
@matthewp when I try to run `donejs api` I get:

```
 donejs api
Could not find local DoneJS binary (/Users/justin/dev/matthew-pmo/node_modules/.bin/donejs)
```

**Comment by justinbmeyer** [comment]
@matthewp this project is pointing at `"can": "^2.3.0-pre.8",` ... it is possible this is a problem just because of the deps?

**Comment by justinbmeyer** [comment]
@matthewp I'm going to try my app and see if I can see this there.  If not, I think we'll need to upgrade your app before it's worth spending a lot of time on it.  It's possible this is fixed with latest everything.

**Comment by justinbmeyer** [comment]
@matthewp I'm able to recreate in my app.  Good catch!

**Comment by justinbmeyer** [comment]
I think the bug is related to switch / case.  It seems like `{{#case 'order'}}` is being re-evaluated from within an already torn down `{{#switch action}}`.

I'm not exactly sure why when `{{#switch action}}` is torndown that it's not killing `{{#case 'order'}}`.

**Comment by matthewp** [comment]
@justinbmeyer Sorry, that was indeed an old project from this August. The project I actually worked on today was https://github.com/matthewp/place-my-order  Sorry about that.

**Comment by justinbmeyer** [comment]
Created a CanJS issue for it: https://github.com/canjs/canjs/issues/2188
