### ISSUE TITLE
Error when trying to generate a component

### ISSUE THREAD

**Issue by cklanac** [donejs/donejs#48]
donejs generate component home.component pmo-home
Native thread-sleep not available.
This will result in much slower performance, but it will still work.
You should re-install spawn-sync or upgrade to the latest version of node if possible.

Check /Users/joecrick/WebstormProjects/DoneTraining/done-js-class/node_modules/generator-donejs/node_modules/yeoman-generator/node_modules/cross-spawn/node_modules/spawn-sync/error.log for more details

**Comment by justinbmeyer** [comment]
@cklanac any more details about this?  What environment was this running in?

**Comment by daffl** [comment]
I couldn't reproduce this. It looks like an older version of Node which we don't test with. We are supporting latest 0.10 and upwards.
