### ISSUE TITLE
PMO: 2 404s loading socket.io stuff

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#490]
<img width="1293" alt="screen shot 2016-01-13 at 4 40 39 pm" src="https://cloud.githubusercontent.com/assets/361671/12308652/6d92492e-ba14-11e5-8072-bd5cf13cb2df.png">

Also reported in #456

**Comment by matthewp** [comment]
I've found a solution for these 404s but still need to write a test, that's going to hard to come up with. Putting my thoughts here. 

It's a weird scenario where you have a dependency graph like:
- socket.io-client
  - component-emitter 1.2.0
  - engine.io-client
    - component-emitter 1.1.2

However in the node_modules they are ordered like:
- node_modules/component-emitter 1.1.2
- node_modules/socket.io-client/node_modules/component-emitter 1.2.0

That is, the more nested component-emitter (according to the dependency graph) is less nested in the filesystem.

The bug (on our part) is that we are overwriting the same object over and over when we traverse, meaning that when we go looking for 1.1.2 we try to find it in a nested position even though it was already found at the root node_modules.

The fix is to leave packages in the context even if they aren't the package we are looking for.

**Comment by justinbmeyer** [comment]
Is npm3 depth first?  Why would 1.1.2 get installed less nested?  The only thing I can think of is that children are installed before parents.

**Comment by matthewp** [comment]
This is fixed in Steal 0.13.1, I've verified in my own place-my-order.
