### ISSUE TITLE
donejs init error on windows

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#494]
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "can-fixture@^0.1.0" "documentjs@^0.4.1" "donejs-cli@^0.6.0" "donejs-deploy@^0.4.0" "funcunit@~3.0.0" "steal-qunit@^0.1.1" "steal-tools@^0.13.0" "testee@^0.2.4" "--loglevel=error" "--save-dev"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! documentjs@0.4.2 postinstall: `install-engine-dependencies`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the documentjs@0.4.2 postinstall script 'install-engine-dependencies'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the documentjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     install-engine-dependencies
npm ERR! You can get their info via:
npm ERR!     npm owner ls documentjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Users\justi\dev\place-my-order\npm-debug.log

**Comment by justinbmeyer** [comment]
This ends up not adding any `devDependencies`.  Which also prevents tests from working.

**Comment by justinbmeyer** [comment]
```
c:\Users\justi\dev\place-my-order>npm install documentjs@0.4.2 --save-dev
npm WARN install Couldn't install optional dependency: Unsupported

> documentjs@0.4.2 postinstall c:\Users\justi\dev\place-my-order\node_modules\documentjs
> install-engine-dependencies

c:\Users\justi\dev\place-my-order\node_modules\engine-dependencies\engine-dependencies.js:78
        var keys = Object.keys(obj);
                          ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at findWhere (c:\Users\justi\dev\place-my-order\node_modules\engine-dependencies\engine-dependencies.js:78:20)
    at engineDependencies (c:\Users\justi\dev\place-my-order\node_modules\engine-dependencies\engine-dependencies.js:40:26)
    at Object.<anonymous> (c:\Users\justi\dev\place-my-order\node_modules\engine-dependencies\bin\install-engine-dependencies:22:1)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:429:10)
    at startup (node.js:139:18)
npm WARN EPACKAGEJSON place-my-order@0.0.0 No repository field.
npm WARN EPACKAGEJSON place-my-order@0.0.0 No license field.
```

**Comment by justinbmeyer** [comment]
I also see this:

```
npm WARN install Couldn't install optional dependency: Unsupported

> documentjs@0.4.2 postinstall c:\Users\justi\dev\place-my-order\node_modules\documentjs
> install-engine-dependencies

module.js:327
    throw err;
    ^

Error: Cannot find module 'c:\Users\justi\dev\place-my-order\node_modules\documentjs\node_modules\c:\Users\justi\dev\place-my-order\node_modules\engine-dependencies\bin\install-engine-dependencies/package.json'
```

**Comment by justinbmeyer** [comment]
This seems to fix it: https://github.com/bitovi/engine-dependencies/pull/7, but it needs a release to NPM.

**Comment by matthewp** [comment]
This should be fixed.
