### ISSUE TITLE
Locked jQuery dependency doesn't work with Steal + NPM2 

### ISSUE THREAD

**Issue by daffl** [donejs/donejs#497]
The fix for #476 to install a fixed version of jQuery does not work with Steal and NPM2. One of the jQuery package.json's errors (not with a 404 but an HTML error) because it is not installed.

**Comment by matthewp** [comment]
I'll look into this, saw no problems with a fresh donejs init this morning with npm3.

**Comment by daffl** [comment]
Happens only with NPM2

**Comment by matthewp** [comment]
I'm not seeing this, after a fresh donejs init it's working for me, anything in particular you did differently?

<img width="1321" alt="screen shot 2016-01-20 at 12 29 18 pm" src="https://cloud.githubusercontent.com/assets/361671/12457253/89e2caa6-bf71-11e5-99ab-5a5aab3ecda8.png">

**Comment by daffl** [comment]
You are right. That may be something else. Still checking why it didn't give a 404.
