### ISSUE TITLE
util/domless is in production build

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#498]
From https://github.com/donejs/donejs/issues/456

**Comment by matthewp** [comment]
I went back to StealTools 0.7 to see how it handled it and nothing has changed. Modules that are brought in by buildConfig are treated as any other plugin and are an empty module in production (back then it used System.set, but now we use define() )

I don't think this is a bug. Would be nice to exclude these parts but I can't think of a good way off hand. We could have an `excludeFromBuild` flag or something.

**Comment by justinbmeyer** [comment]
Ah, they are an empty module.  That's fine.  How does it know they should be empty?

**Comment by matthewp** [comment]
It marks everything that comes through the BuildSystem as a plugin.

**Comment by matthewp** [comment]
Going to close this as not a bug.
