### ISSUE TITLE
Error in browser/ maybe ssr after starting a new project.

### ISSUE THREAD

**Issue by marshallswain** [donejs/donejs#501]
@julia-allyce noted an issue she had after starting a new project.  I ran into a similar issue.  See my thoughts below.

```
julia [6:38 PM] 
uhmm I just generated a new project, and ran `donejs develop`

[6:39] 
if i go to localhost:8080/production.html i get the error:

[6:39] 
Uncaught SyntaxError: Unexpected token < index.js:1

[6:39] 
which i assume is from parsing index.stache?

[6:40] 
ehh development.html works

kevin [6:50 PM] 
I think you probably just need to do `donejs build` before hitting production.html


----- Today January 23rd, 2016 -----
julia [9:44 AM] 
Potentially unhandled rejection [13] SyntaxError: Error loading "package.json!npm" at http://localhost:8080/package.json
Unexpected token <

[9:44] 
Im getting this really ambiguous error…I can’t figure out where it is coming from

marshall [10:03 AM] 
@julia I fixed this by running `npm install` inside the node_modules/<dependency> folder for one of my dependencies, but I can’t remember which.(edited)

[10:07] 
I think it’s caused by a missing sub-dependency, so where there would be an expected package.json there is nothing, so the SSR server is returning a response that starts with `<`.  Just a guess.(edited)
```

**Comment by marshallswain** [comment]
After talking more with @julia-allyce, I think I ran into this issue by selecting the wrong npm version during `donejs init`.  She appears to be getting the issue by changing npm versions afterwards.  How does one tell Steal that we've changed versions?

**Comment by julia-allyce** [comment]
@marshallswain  thanks for documenting this

I was able to resolve this by switching npm versions and reinstalling my node_modules :unamused:

**Comment by matthewp** [comment]
Switching from which version to what version?

**Comment by matthewp** [comment]
If you're using NPM 3.x you want to add `"npmAlgorithm": "flat"` to the the package.json under `"system"`, if using NPM 2.x remove that property.  It does mean that everyone on the team needs to be using the same version. Maybe we could supporting setting this config in localStorage or something, so individuals could control it.

**Comment by marshallswain** [comment]
Has this already been documented?

**Comment by matthewp** [comment]
Yeah, it's in the stealjs docs like here: http://stealjs.com/docs/npm.html#section_Use

If you create a new project with `donejs init` it will detect what version of npm you are using and add the flag if needed.

**Comment by marshallswain** [comment]
Thanks.
