### ISSUE TITLE
PMO: Set algebra isn't being used in orders and it's broken when added ~8

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#503]
There should be a set algebra like:

```
new set.Algebra(set.comparators.enum("type",["new", ...])
```

I added this and things broke.

**Comment by matthewp** [comment]
Is this still broke?

**Comment by justinbmeyer** [comment]
I will check.

**Comment by phillipskevin** [comment]
@justinbmeyer do you remember what broke when you added this before? Nothing overtly breaks when I add the algebra, but I'm not super confident how to verify that the algebra is working.

**Comment by phillipskevin** [comment]
I don't see the requests being combined as mentioned in https://github.com/donejs/donejs/issues/638. So it must not be working correctly.

**Comment by phillipskevin** [comment]
Actually, combining requests is working. I just forgot to change `type` to `status` when I copied over your example code above.

**Comment by phillipskevin** [comment]
Going to use this to update place-my-order.com and https://github.com/donejs/donejs/issues/633 to handle updating the guides and generators.

**Comment by phillipskevin** [comment]
Issue moved to [donejs/place-my-order #131](https://github.com/donejs/place-my-order/issues/131) via [**ZenHub**](https://www.zenhub.com/)
