### ISSUE TITLE
PMO: iOS looks ok

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#504]
the app is unusable on iOS because of unresponsive styles.

**Comment by daffl** [comment]
This also came up a while ago at https://github.com/donejs/place-my-order/issues/85

**Comment by matthewp** [comment]
https://github.com/donejs/place-my-order/commit/f7867c443f233cbbc25531bdf04e77a076548475 is probably what is needed.

**Comment by justinbmeyer** [comment]
Ah, but shouldn't pmo-assets be pulling in bootstrap?  I'd rather not have to add another step.

**Comment by matthewp** [comment]
pmo-assets doesn't include markup, this is not just styles.

**Comment by matthewp** [comment]
Ok, now I see that we don't have bootstrap with pmo-assets, so this would require installing it. I think we can avoid it and make it look decent with some css changes, looking into it now.

**Comment by matthewp** [comment]
Here's what I've got from add a meta viewport table and a couple of css tweaks:

<img width="354" alt="screen shot 2016-01-26 at 8 40 13 am" src="https://cloud.githubusercontent.com/assets/361671/12582042/7d79e4ca-c408-11e5-98c4-978aa72677de.png">

**Comment by matthewp** [comment]
https://github.com/donejs/place-my-order-assets/pull/3 applied those styles, also updating the guide.

**Comment by matthewp** [comment]
This is what it looks like now:

<img width="487" alt="screen shot 2016-01-26 at 12 39 58 pm" src="https://cloud.githubusercontent.com/assets/361671/12590679/29d17a7a-c432-11e5-8620-a96d42a990d3.png">
