### ISSUE TITLE
PMO: Unable to create an order in iOS / nw.js

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#505]
After generating an app, I was unable to create an order.

**Comment by matthewp** [comment]
Can you share your repo, will make it easier to debug.

**Comment by justinbmeyer** [comment]
Related: #512

**Comment by justinbmeyer** [comment]
https://github.com/justinbmeyer/place-my-order

**Comment by matthewp** [comment]
Was able to verify this is fixed.
