### ISSUE TITLE
use package.json over yo-rc

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#508]
Someone generated the app with the wrong project name, but then changed their `package.json`'s name.  Future generator use ignored `package.json` and used yo-rc's instead.

**Comment by daffl** [comment]
@pYr0x also suggested to use `package.json` for all that information in https://github.com/donejs/generator-donejs/issues/60. We should easily be able to get rid of the `.yo-rc.json`.

**Comment by pYr0x** [comment]
made a PR https://github.com/donejs/generator-donejs/pull/66

**Comment by matthewp** [comment]
Cool, thanks, will take a look.
