### ISSUE TITLE
Generate plural fixture names

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#509]
instead of `fixtures/city.js`, make it`fixtures/cities.js`

This will make it much less confusing which is the model and fixture.

**Comment by cherifGsoul** [comment]
Should this be real plural like:

`person => people`

or just put an `s` at end?

**Comment by justinbmeyer** [comment]
real plural would be ideal.  There's probably decent node packages that help with this.

**Comment by cherifGsoul** [comment]
@justinbmeyer I see [lodash-inflection mixin](https://www.npmjs.com/package/lodash-inflection) can do the work, any thoughts?

**Comment by cherifGsoul** [comment]
Test model names already in plural they should be singular https://github.com/donejs/generator-donejs/blob/master/test/supermodel.test.js#L100, should we force this convention even if the user make a plural model names?
