### ISSUE TITLE
Thoughts After Building First(ish) Donejs App

### ISSUE THREAD

**Issue by julia-allyce** [donejs/donejs#513]
1. I was able to put together 80% of the app in >12 working hours.
2. I wasn’t able to get DoneJS working on my collaborators machines :/
   - One person had issues with NPM install (user error maybe?). She didn’t return to finish the hackathon
   - Another person, Alia, was on a windows machine. So we had long filename issues, so we switched the build to npm 3. It would be great like Matthew mentioned to let npm algorithm be a global setting so not everyone in a project has to use the same version of npm
   - After Alia upgraded npm to 3, and installed donejs globally it couldn’t be found ? I wasn’t able to debug this remotely and with my limited windows knowledge.
3. We were able to deploy DoneJS on a Go server (sans SSR) which was pretty cool, and easy.
4. Supermodels seemed to just work….except! It was posting with type webform instead of JSON by default, which I didnt expect.
5. It would be nice to be able to configure an expiration for local storage. So after Xhrs it has to be cleared and new data needs to be fetched.
6. We show in the guides 2 different ways to fetch data, one using can-connect/tag and another from inside the VM. This is fine, but maybe this means we should document the different ways to get data, and why you might do it each way.
7. We need better docs for our new binding syntax with examples, and why you’d want to use a specific type of binding.
8. It would be good to have docs on how to build forms with canjs/stache, and again why you’d want to use the examples given.
9. Docs on how to load pages/modules with routing would be good too. I’d like a more fleshed out example of using a switch with more complicated routing structure. Should you subroute in your page component? How? or keep all routing in index.stache? This seems like it would get unmanageable in large applications.
10. Several times I ran into ambiguous error messages that took a while to debug...It would be nice in development mode to have errors inject into the dom or do something more obvious. Maybe we can throw terminal alerts. I’d often be deep into making a new component before I realized I broke something. With hot module swapping the app almost always seemed to continue working, especially when I am just looking at half the screen behind my text editor.
11. Over all DoneJS was pretty easy to use for me, but I am still hesitant about the steep learning curve for someone coming from a different framework :/
12. The quick start guide was super helpful, I used it as a reference a lot. I only jumped into the in-depth guide once to sanity check how I was getting data, only to see the in-depth guide has a different solution :[

**Comment by julia-allyce** [comment]
### Comments from original Google Doc

> It would be great like Matthew mentioned to let npm algorithm be a global setting so not everyone in a project has to use the same version of npm

Issue opened: https://github.com/stealjs/steal/issues/563

> After Alia upgraded npm to 3, and installed donejs globally it couldn’t be found ?

@matthewp: "This might depend on how you install it, but I believe this is a Node and/or NPM thing, the installed packages are placed in a different location depending on what version installed them"

> It was posting with type webform instead of JSON by default, which I didnt expect.

@marshallswain: "This surprised me, too. It only became a problem on a service that can accept big requests (bigger than what query strings allow). There doesn't seem to be a simple way to change it, either, other than overwriting the getListData, etc. methods."

> It would be nice in development mode to have errors inject into the dom

@matthewp: "I like that idea a lot, I've seen other frameworks do things like this and I think it's helpful. Good error messages is a killer feature we shouldn't ignore.
We should create an issue and break down the types of errors that can occur."
Opened issue #514 

> guide once to sanity check how I was getting data, only to see the in-depth guide has a different solution :[

@matthewp: "Oh, can you file bugs about that? We've been updating the in-depth guide recently, if there is a discrepancy we should fix it."

**Comment by julia-allyce** [comment]
> This surprised me, too. It only became a problem on a service that can accept big requests (bigger than what query strings allow). There doesn't seem to be a simple way to change it, either, other than overwriting the getListData, etc. methods.

@marshallswain I'd like to know _why_ its not JSON by default. The limit on query string length can easily be maxed out. @justinbmeyer is there a way to easily specify what types of requests you are making?

**Comment by justinbmeyer** [comment]
>  It only became a problem on a service that can accept big requests (bigger than what query strings allow). 
> I'd like to know why its not JSON by default. The limit on query string length can easily be maxed out. 

@marshallswain / @julia-allyce I think there's some confusion here.

Using querystrings on GET requests still makes a ton of sense.  `GET /todos?due=today`.  The limit on query string length will almost never be maxed out.  If it is, switching to JSON in the URL will not help.

Using form-url-encoded request bodies in `POST` and `PUT` doesn't really make sense anymore.  It did originally because not all server frameworks easily supported JSON.  Times have changed.  Does IE8 support JSON.parse?  

Even if not, I'd be fine making the default behavior of can-connect to POST/PUT JSON data.  People can polyfill IE8 if needed.

>  is there a way to easily specify what types of requests you are making?

Yes, you can make a jQuery prefilter that does this.

There doesn't seem to be a simple way to change it, either, other than overwriting the getListData, etc. methods."
