### ISSUE TITLE
Remove can-connect/tag from guides. ~3

### ISSUE THREAD

**Issue by julia-allyce** [donejs/donejs#515]
> We should not use can-connect/tag in the quick start anymore.  Real apps probably don't use it.

The indepth guide uses a getter in the VM to return a promise, and the quick start uses the can-connect/tag
- http://donejs.com/place-my-order.html#section=section_Adddatatothepage
- http://donejs.com/Guide.html#section=section_Usetheconnection

I don't know if this is an "issue", but it might be an indicator we should dedicate some documentation to explaining the different ways you can load data for a page and why you might use one or the other. If you look at reacts doc's which are really good. Each topic breaks down how you can do something and why you should do it that way.

Adding, another section to the donejs site for this kind of guide would be really helpful. We could cover topics that most apps will always implement: loading data into your page, routing, building forms, when/why to use specific data binding, setting up a realtime connection, handling session data(??), writing custom can-connect handlers

edit: I realizes our guides do this, but this would be a more ~~in-depth~~ focused/very specific/concise discussion of each topic, and not tied to a "build-an-app" guide. Something that could be used as a reference and allow users to compare options for performing a specific task.

**Comment by justinbmeyer** [comment]
@julia-allyce Imo, this level of detail would be too much for the DoneJS site.  This type of detail should be in `can-connect`'s docs, specifically supermap and can/tag's.  

As you noted, the guides can cover this topic (btw, the PMO guide actually uses both techniques).  They should link to the right places.  

I'd be alright with an FAQ page on donejs (similar to the API page), that links to corresponding "answers" on the individual project docs pages.

**Comment by chasenlehara** [comment]
I think this kind of information would be a great fit for the [Recipes section of the CanJS website](https://canjs.com/guides/BuildAnApplicationWithData.html).

If each project had a page with useful how-to info (Recipes, Common Patterns, etc.), then we could link to their pages from a page on the DoneJS website.

**Comment by phillipskevin** [comment]
Plan based on the discussion at the [DoneJS Contributors Meeting](http://forums.donejs.com/t/donejs-contributors-meeting-2017-02-10/547/7):

- change the chat guide to load chat data in the viewModel instead of using can-connect/tag
- change the restaurant model in the PMO guide to load data in the viewModel
- leave the order model in the PMO guide as-is and make sure the use of can-connect-tag is explained well

**Comment by phillipskevin** [comment]
Closing this for the separate issues for each guide.
