### ISSUE TITLE
Pushstate routes no longer update after a hot reload.  

### ISSUE THREAD

**Issue by marshallswain** [donejs/donejs#524]
can.route params update, but the URL doesn’t.  I'm using a new app generated with donejs@0.7.0-pre.1

**Comment by justinbmeyer** [comment]
@marshallswain can you give an example of your app?  Does this happen in donejs-chat?

**Comment by marshallswain** [comment]
I'll whittle it down to see if I can better identify what breaks it.

**Comment by daffl** [comment]
Yesterday at the meetup I verified that this works. Please reopen if it is still happening and you have more info.
