### ISSUE TITLE
Installing donejs-cli is taking a long time

### ISSUE THREAD

**Issue by daffl** [donejs/donejs#536]
Also if it is already installed (which should skip the installation entirely)

**Comment by daffl** [comment]
There is nothing that we can really do about this. `donejs-cli` gets installed every time and this will only be happening when initializing a new project.

**Comment by justinbmeyer** [comment]
Is this issue for just the CLI or donejs a whole?  I think we should work to improve DoneJS's installation time.  I think an audit of our dependencies could result in a reduction in package sizes needed to be downloaded.

Also, like you mentioned in another issue, progressively adding things like `deploy firebase` would go a long way.

**Comment by daffl** [comment]
An audit of all dependencies and not pulling in optional dependencies would definitely help. I created https://github.com/donejs/donejs/issues/540 for the deploy.
