### ISSUE TITLE
Make deploy plugin based

### ISSUE THREAD

**Issue by daffl** [donejs/donejs#540]
Currently `donejs-deploy` ships all it's deployment strategies, causing the installation of many potentially unused modules. Just like `donejs add cordova` etc. deployment strategies should be in their own DoneJS plugin modules. We will need:
- `donejs-heroku` to deploy to Heroku (instead of setting it up separately on Travis CI we can just use this command) as `donejs add heroku`
- `donejs-firebase` to be able to run `donejs add firebase`
- `donejs-s3` for deployment of static assets to S3
  
  `donejs deploy` will then just run the configured strategies.

**Comment by daffl** [comment]
Also see https://github.com/donejs/deploy/issues/38

**Comment by chasenlehara** [comment]
I’ve started to help with this by adding this repo for `donejs add firebase`: https://github.com/donejs/donejs-firebase

Right now the 0.1.1 release just makes the required `package.json` modifications, but it can be expanded to include the Firebase code as well.

**Comment by justinbmeyer** [comment]
Closing for that other issue.

**Comment by matthewp** [comment]
@phillipskevin can this be closed?

**Comment by phillipskevin** [comment]
I think it can. Firebase deploys no longer use `donejs-deploy` and the guides/generators don't use it anymore. 

We do not have `donejs-heroku` or `donejs-s3` at the moment. `donejs-heroku` is covered by https://github.com/donejs/donejs/issues/640. Should we create a new issue for S3 or just wait and see if anyone requests this?

**Comment by matthewp** [comment]
I would wait for it to be requested.
