### ISSUE TITLE
Needs a generic way for new folder initialization

### ISSUE THREAD

**Issue by daffl** [donejs/donejs#541]
After we added `donejs plugin` we now need `donejs generator`. There probably is no way around listing those top level commands (since we don't want to install `donejs cli` first in every folder someone runs `donejs` just to find out it's something that can't run) though.

**Comment by justinbmeyer** [comment]
What's wrong with installing the cli first?

**Comment by daffl** [comment]
I don't want a `node_modules` folder to show up everywhere I happen to run `donejs`.

**Comment by daffl** [comment]
It turns out that this can be done already with the `--type` parameter. Since generators are probably not as common as a plugin there shouldn't be any changes necessary and it can just run

```
donejs init --type generator
```

**Comment by justinbmeyer** [comment]
> I don't want a node_modules folder to show up everywhere I happen to run donejs.

Why would you run `donejs` in a folder where you didn't already have `node_modules` or intend to?
