### ISSUE TITLE
0.7.0 Release

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#542]
This is complete, everything is passing.

<img width="1156" alt="screen shot 2016-02-24 at 9 05 32 am" src="https://cloud.githubusercontent.com/assets/361671/13287621/ed203912-dad5-11e5-8258-d9fe08bee1ce.png">

<img width="1081" alt="screen shot 2016-02-24 at 9 05 45 am" src="https://cloud.githubusercontent.com/assets/361671/13287624/efa01ab8-dad5-11e5-8d5e-3b6da884fddf.png">

**Comment by daffl** [comment]
It's out so we can close this.
