### ISSUE TITLE
Initing a camelCased project won't start

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#543]
``` shell
donejs init helloWorld
```

Will write out `hello-world` in the package.json, but leave it as `helloWorld` in the index.stache imports. This causes the app to fail to load.  Do we need to convert to the kebab casing?

**Comment by daffl** [comment]
Yes. I will work on this with some other generator tweaks today.

**Comment by phillipskevin** [comment]
Same problem if you do `donejs init World`.
