### ISSUE TITLE
Ubuntu 14.04 not installing

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#556]
http://pastebin.com/KBhYu2me

**Comment by daffl** [comment]
This looks like a Linux permission issue. I just installed on my 15.04 Ubuntu VM and everything went through ok.

**Comment by daffl** [comment]
You will either have to run `sudo npm install donejs -g` or use [nvm](https://github.com/creationix/nvm) which installs all Node versions local to the user.
