### ISSUE TITLE
Specify required versions of Node and npm at beginning of Guide

### ISSUE THREAD

**Issue by CODE-REaD** [donejs/donejs#571]
As an initiate to the DoneJS **[Quick Start Guide](https://donejs.com/Guide.html)**, I previously wrote:

> I notice at https://donejs.com/SettingUp.html that specific versions of Node and npm are required by DoneJS. If still applicable, I strongly recommend that information be added to the Guide.

I now notice that the **[Quick Start Guide](https://donejs.com/Guide.html)** is a subsequent step to the **[Setting Up DoneJS](https://donejs.com/SettingUp.html)** guide, which _does_ include required versions of Node and npm.  So it is a matter of ensuring the user encounters these guides in the correct order.

For that purpose (and because I stumbled over it myself), I hereby request a reference to **Setting Up DoneJS** as its prerequisite at the beginning of the **Quick Start Guide**.  Thanks.

**Comment by matthewp** [comment]
Fixed in #799
