### ISSUE TITLE
Setting Up DoneJS guide does not include Node installation instructions

### ISSUE THREAD

**Issue by CODE-REaD** [donejs/donejs#572]
I was confused Saturday when after following the **[Setting Up DoneJS](https://donejs.com/SettingUp.html)** guide I could not run the npm command.  This was because I had not installed Node.  While the **[Setting Up DoneJS](https://donejs.com/SettingUp.html)** guide does specify that "First you need a recent version of Node.js," it does not furnish instructions for installing Node.js (though it gives instructions for installing all of the other prerequisites).

So for consistency I request that the **Setting Up DoneJS** guide also include installation instructions for Node.js.  Thanks.

**Comment by matthewp** [comment]
Makes sense, thanks!

**Comment by matthewp** [comment]
Fixed by #808
