### ISSUE TITLE
Typo in index.stache endures until donejs server reset

### ISSUE THREAD

**Issue by CODE-REaD** [donejs/donejs#573]
**Environment:** AWS UNIX instance on Amazon's cloud.
**Issue:** Typo in index.stache displays in generated pages until DoneJS server is restarted.
**Details:**

> I made a typo in my editing of index.stache (entered "<can-import from-"bootstrap/less/bootstrap.less!" />", note from- instead of from=) and even after correcting it, the web page still shows my typo. This happens even if I open a new browser session, so the typo is somehow "stuck" in the DoneJS mechanism. Restarting the donejs server did clear the problem.

According to [@marshallswain](http://forums.donejs.com/t/first-time-user-notes-on-quick-start-guide-part-1/188),

> Thanks for pointing this one out. I'm pretty sure this is a known issue with the top level template. I'm not sure if we have a solution for it, yet, since this is a result of how the SSR server caches the page (or something to that effect), but this is something that could at least be pointed out in the documentation.

**Comment by matthewp** [comment]
So this is can-import related, could this be the same bug as:

https://github.com/donejs/donejs/issues/470

??

**Comment by matthewp** [comment]
I think it's the same issue.
