### ISSUE TITLE
npm run document doesn't work on Windows

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#576]
```
Generating guides at site

C:\Users\Matthew\dev\donejs\node_modules\documentjs\lib\process\clean_doc_map.js:6
4
                throw "The parent DocObject ("+options.parent+") was not found!";
                ^
 The parent DocObject (donejs) was not found!

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\no
de_modules\\npm\\bin\\npm-cli.js" "run" "document"
```

**Comment by justinbmeyer** [comment]
What's the error?

**Comment by matthewp** [comment]
I updated the original issue.  Note  that this is about running donejs' documentation, not a donejs apps.

**Comment by matthewp** [comment]
Looks like the problem is that the README.md is not added to the docMap

**Comment by matthewp** [comment]
The problem is this regex expecting unix paths: https://github.com/bitovi/documentjs/blob/master/lib/process/file.js#L102

**Comment by matthewp** [comment]
This is blocking https://github.com/donejs/donejs/pull/566

**Comment by matthewp** [comment]
This is fixed now.

**Comment by dawnwages** [comment]
I'm having issues and seeing this error on Windows.
