### ISSUE TITLE
Add code coverage to projects

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#584]
Here's a few that I'd start with:
- [x] - [generator-donejs](https://github.com/donejs/generator-donejs/milestones/Code%20Coverage)
- [x] - done-ssr
- [x] - steal-tools
- [x] - donejs/cli

**Comment by matthewp** [comment]
Don't do done-ssr for now, it might be difficult because it spawns subprocesses to run tests.

**Comment by daffl** [comment]
This should be mostly done now right?

**Comment by matthewp** [comment]
Yep.
