### ISSUE TITLE
Donejs init should merge package.json if it already exists

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#59]
If I already have a package.json and run donejs init, it should use my existing settings appropriately.

**Comment by daffl** [comment]
It already does by reading the initial package.json at https://github.com/donejs/generator-donejs/blob/master/app/index.js#L12 and then merging it with the generator content at https://github.com/donejs/generator-donejs/blob/master/app/index.js#L139. Prompts for fields will also only be shown when the field isn't present in the original package.json.
