### ISSUE TITLE
Dependencies installed can be different than what is in donejs-cli

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#590]
This was reported in gitter: 

https://gitter.im/donejs/donejs?at=56f44b78d39de41b495d87b2

What's interesting is that most of the package.json is up-to-date, it's just the dependency list that is not.

**Comment by matthewp** [comment]
Hey @tracer99, in the folder where you are initing from, do you have a `node_modules/` folder, and does that node_modules folder have a `donejs-cli` subfolder?

**Comment by justinbmeyer** [comment]
I once found an error because the parent folder had a `node_modules` so parts of the CLI didn't work.

**Comment by tracer99** [comment]
I ran init in my home dir. I don't have a node_modules dir there. 
Of note is that the directory I initialized the project already existed.
That directory did not have a node_modules dir or anything that would have conflicted. It was a boilerplate git project setup by our system.

**Comment by matthewp** [comment]
@tracer99 Did the folder have a package.json by any chance?

**Comment by tracer99** [comment]
Nope.

**Comment by tracer99** [comment]
I re-did an init on a clean install (not into an existing dir)
Just to be safe:

```
node -v
v0.12.12

npm cache clear

donejs -V
0.8.0
```

This is the package.json that was generated https://gist.github.com/tracer99/85d10956dc20a170fa55

**Comment by matthewp** [comment]
Anything in the existing directory at all?

**Comment by tracer99** [comment]
We have a boilerplate new git project init on our git server. This is what it creates and what the dir had:

```
.gitignore
Makefile
README
bin/README
docs/README
tests/README
```

**Comment by phillipskevin** [comment]
So you can see in that package.json that `donejs-cli@0.7.0` was installed, so this is the 0.7.0 dependencies. I'm going to investigate how it's possible that an older cli was installed.

**Comment by phillipskevin** [comment]
Ok, I was able to reproduce this issue.

Prior to 0.9, this issue could occur if you had a package.json in any parent directory of where you're initializing a new app.

```
$ donejs -V
0.7.2
$ donejs init
...
$ cat package.json | grep donejs-cli
"donejs-cli": "^0.7.0"
$ mkdir -p foo/bar/baz/zero-eight-app
$ cd foo/bar/baz/zero-eight-app/
$ npm i -g donejs@0.8
$ donejs init
...
$ cat package.json | grep donejs-cli
    "donejs-cli": "^0.7.0",
$ mkdir ../zero-nine-app
$ cd ../zero-nine-app
$ npm i -g donejs@0.9
$ donejs init
...
$ cat package.json | grep donejs-cli
"donejs-cli": "^0.9.4",
```
