### ISSUE TITLE
init does not create a project in 0.8.0

### ISSUE THREAD

**Issue by phillipskevin** [donejs/donejs#595]
Running `donejs init` does not create a project using DoneJS 0.8.0.

```
$ node --version
v4.4.1
$ npm --version
2.14.20
$ donejs --version
0.8.0

$ donejs init test-project
Initializing new DoneJS application at /Users/kevin/dev/projects/test-project
Installing donejs-cli
donejs-cli@0.8.0 ../../../node_modules/donejs-cli

$ cd test-project/
$ ls
```

**Comment by phillipskevin** [comment]
The `ls` at the end shows that the test-project folder is empty.

**Comment by matthewp** [comment]
Do you have a node_modules folder at ../../../ ? I think this is a bug we've seen before and is not completely fixed.

**Comment by phillipskevin** [comment]
Yes, apparently my home folder had a node_modules folder. If I delete that, the project is created correctly.

**Comment by matthewp** [comment]
Ok, we need to get this fixed, going to assign it to @m-mujica since he is working on donejs-cli now.

**Comment by m-mujica** [comment]
Fixed in master.
