### ISSUE TITLE
yo generators try to write to some global configuration

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#596]
this was breaking b/c of permissions, yo was trying to write to the users's local folder, but we should figure out a way of handling these errors.

**Comment by matthewp** [comment]
Any idea where it was trying to write to?

**Comment by justinbmeyer** [comment]
I don't remember anymore, but it was in some folder like `/private` or `/var`.  

I might have had people run this:

https://docs.npmjs.com/getting-started/fixing-npm-permissions

This might need to be higher than `P3` because I think I had to have someone run this almost every time.

**Comment by phillipskevin** [comment]
It definitely writes to `.yo-rc-global.json` in the user's home directory. https://github.com/yeoman/doctor might be of help when this happens.

**Comment by matthewp** [comment]
Maybe we should have a `donejs doctor` that runs stuff like that.

**Comment by matthewp** [comment]
I was able to replicate by creating a new user and making it the owner of my `~/.yo-rc-global.json` file:

<img width="682" alt="screen shot 2017-02-14 at 10 43 41 am" src="https://cloud.githubusercontent.com/assets/361671/22936120/884fd9b2-f2a2-11e6-91fc-6c9b48089547.png">

**Comment by matthewp** [comment]
Trying to think of a fix here. In this case I think the error message is pretty reasonable. Not pretty to look at, but it directly tells you the issue.

Maybe the errors people have gotten at meetups have been of a different variety though.

**Comment by phillipskevin** [comment]
Does `yo doctor` fix the issue? Or at least let give you more information about the problem?

**Comment by matthewp** [comment]
Actually no, it doesn't catch this issue:

```
Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version
```

**Comment by phillipskevin** [comment]
I did some digging into this and yeoman's base generator creates two Storage objects [here](https://github.com/yeoman/generator/blob/bea86c758e6235f6b577683e928f5cda2adaf9ce/lib/index.js#L137-L138).

`this.config` is the local config for the app `path/to/app/.yo-rc.json`
`this._globalConfig` is the global config for the user `users/home/dir/.yo-rc-global.json`

The global config doesn't seem to be a public API as it's not mentioned at all in their docs http://yeoman.io/authoring/storage.html. However, the only solution I see right now is to overwrite the `_globalConfig` if access to that file is denied.

**Comment by justinbmeyer** [comment]
Can we just give a good warning pointing them in the right spot to resolve.

**Comment by phillipskevin** [comment]
We could give a warning and then kill the process so they could update the permissions and rerun the generator.

It's possible that some users won't be able to update the permissions of the file, which is why I was thinking we would just force it to not use the global config if they don't have access.

**Comment by phillipskevin** [comment]
I found a better solution to this by wrapping the `_writeFiles` function with a try/catch. Again, this isn't a documented API, but I think it's the best solution and we'll just have to try to protect ourselves by making sure our tests will fail if they change this API.

**Comment by phillipskevin** [comment]
Actually, overwriting `_writeFiles` doesn't work consistently either, so I'm going to go with the original solution of forcing it to not use the global config if it's not writeable.
