### ISSUE TITLE
done-fetch

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#598]
We should create a `fetch` module that polyfills the API on the client/server. In the future this will be the primary API for doing networks requests, not XHR. Will want to provide the same Zone caching as the xhr cache currently gives us.

**Comment by pYr0x** [comment]
what about https://github.com/github/fetch ?
create a fork?

**Comment by matthewp** [comment]
This would likely use that under the hood, or more likely https://www.npmjs.com/package/isomorphic-fetch since it runs in Node as well.

**Comment by matthewp** [comment]
This is all about Zones, starting in DoneJS 0.8.0 we now have XHR caching that prevents duplicate fetches from happening in the client (when server-side rendering). This issue is about bringing the same functionality to `fetch`.

**Comment by justinbmeyer** [comment]
@matthewp does this issue belong in `can-zone`?

**Comment by matthewp** [comment]
Filed https://github.com/canjs/can-zone/issues/89
