### ISSUE TITLE
Test and specify engines and os-es (7)

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#60]
We need to make sure DoneJS (and its sub-projects), are able to run in certain versions of node and certain operating systems.  These should be specified in `package.json`'s [engines](https://docs.npmjs.com/files/package.json#engines) and [os](https://docs.npmjs.com/files/package.json#os)

 Steps:

 - figure out a way to test sub-projects in different environments.  All those sub-projects should list this information.
 - possibly create an integration test

Projects to look at:

- StealTools / live-reload (2) (1) (1).
- can-ssr (1) (1) (1)
- DocumentJS (windows 3) (node 1) (CI 1). 
- Generators / cli (3) (1) (1)

**Comment by justinbmeyer** [comment]
node: 10, 12, and io.

**Comment by daffl** [comment]
https://github.com/donejs/donejs/pull/68 tests run on Node 0.10, latest and io.js on Linux and Windows (caught a bug that way, too). Working on setting the same up for the generator.

**Comment by justinbmeyer** [comment]
Related DocumentJS issues:

- https://github.com/bitovi/documentjs/issues/104

**Comment by matthewp** [comment]
steal-tools is now being tested in Node 0.10.x, 0.12.x, and IO.js 3.2.x in Travis and Appveyor (for Windows).  All tests passing in minor.

Going to update the docs on contributing with Windows.
