### ISSUE TITLE
Deprecation Warning shown incorrectly

### ISSUE THREAD

**Issue by phillipskevin** [donejs/donejs#607]
The deprecation warning for `donejs init` is shown even if you use `donejs add app`:

```
14:52 $ donejs add app test-proj

DEPRECATION NOTICE:

     donejs init [folder] is deprecated

     Use donejs add app [folder] instead
```

**Comment by m-mujica** [comment]
@phillipskevin that's weird, the `donejs add` callback [does not call](https://github.com/donejs/donejs/blob/0abb614321e1216b8504d32ce040d39035d71802/lib/cli/index.js#L14-L16) the deprecation notice function.

how can I replicate? did you install globally donejs from master?

**Comment by phillipskevin** [comment]
I didn't spend a lot of time looking into it, but I thought it was just because `add` calls `init` here: https://github.com/donejs/donejs/blob/master/lib/cli/cmd-add.js#L18

All I did was install the latest from master and `npm link` it.

**Comment by m-mujica** [comment]
Gotcha, that `init` is from `donejs-cli` it's not the same thing. I'm looking into it, but makes no sense to me.

**Comment by daffl** [comment]
Can we double check this tomorrow?

**Comment by daffl** [comment]
I verified that this is working too. Closing this for now but we'll keep an eye on it once the official release is out.
