### ISSUE TITLE
Make development.html use hashchange routing

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#609]
It might be possible to simply map `can/route/pushstate/pushstate` to "@empty".

**Comment by justinbmeyer** [comment]
- this would go in the app generator's `development.html` template.
- it would add a script tag like:

```
<script>
  steal = {map: {"can/route/pushstate/pushstate": "@empty"}}
</script>
```

**Comment by pYr0x** [comment]
why not provide this info in the `system.envs` in the package.json?

**Comment by matthewp** [comment]
@pYr0x I thought about this way as well, it would essentially be:

```
<script env="browser-development" src="node_modules/steal/steal.js"></script>
```

```
{
  "system": {
    "envs": {
      "browser-development": {
        "map": {
          "can/route/pushstate/pushstate": "@empty"
        }
      }
    }
  }
}
```

**Comment by matthewp** [comment]
^ the downside to the above is that it adds noise to your package.json

**Comment by pYr0x** [comment]
@matthewp for a build maybe we can provide to cleanup the package.json and write that clean object to the bundled file?
like we talked about `jsonOptions`

**Comment by matthewp** [comment]
Maybe, but what I meant is that it creates visual noise when looking at your package.json that really only applies to one narrow scenario. I would probably just implement this with the script tag way since it isolates the change to the development.html file.

**Comment by justinbmeyer** [comment]
@matthewp 

> env="browser-development"

This is a different environment than "window-development"?  

I think this name would be a bit confusing.  What is the difference between "browser" and "window".  Both the browser and window do support pushstate.

I agree that it's nicer in the development file.

**Comment by ilyavf** [comment]
@justinbmeyer: Why do we need hash over pushstate routing during development?

**Comment by justinbmeyer** [comment]
@ilyavf during the majority of development, people can hopefully use `pushstate` and server-side rendering.  However, if bugs are introduced, server-side rendering might not work.  It's difficult to debug things in node.

So instead, we created `development.html` to run the application without server-side rendering.  But you cant really use a pushstate based app without server-side support.  So, we should make the app work with hashchange in this scenario.

**Comment by ilyavf** [comment]
Thanks @justinbmeyer. Makes sense.

**Comment by ilyavf** [comment]
@justinbmeyer, I added the script tag, its working, but I only tested it manually.
Do we want an automated test for this issue? Like, generate a project, etc.

**Comment by justinbmeyer** [comment]
@ilyavf it would be great to have a test, or make it part of the already existing integration test.  I suppose it could be as simple as opening up `development.html` after `donejs-chat` is finished using Zombie (or whatever @matthewp is using as a headless browser).  Then changing the hash to `#!chat` and seeing if the page updates correctly.

I'm sure @matthewp could give some pointers on how to test this.  Thanks for the fix!!!

**Comment by ilyavf** [comment]
This issue is [fixed](https://github.com/donejs/generator-donejs/commit/03b5f521dcaa1ee89272996722a6303d4eb99239) in [generator-donejs #113](https://github.com/donejs/generator-donejs/issues/113)

To test the issue:
- generate project with `generator-donejs`;
- copy the test into the project test folder;
- update app files for the test (add routing and a button for navigation);
- execute project's tests.

[This line](https://github.com/donejs/generator-donejs/blob/master/test/app.test.js#L30) runs tests off the generated project.

**Comment by matthewp** [comment]
Yay!
