### ISSUE TITLE
donejs Quick Start Guide Firebase Configuration Issue

### ISSUE THREAD

**Issue by starlap** [donejs/donejs#615]
**Syntax Errors When Configuring Firebase Deployment**

**Environment:**
Ubuntu 15.04
Node 4.4.2
Firefox

**Steps:**

_Guide Section_: Deploy.Configure Done JS
1. In the `package.json`,  add the following:

``` JavaScript
{
    "donejs": {
      "deploy": {
        "root": "dist",
        "services": {
          "production": {
            "type": "firebase",
            "config": {
              "firebase": "<appname>",
              "public": "./dist",
              "headers": [{
                "source": "/**",
                "headers": [{
                  "key": "Access-Control-Allow-Origin",
                  "value": "*"
                }]
              }]
            }
          }
        }
      }
```

**Expected Outcome:**
Copying the guide's configuration for the Firebase deployment to package.json produces no syntax errors.

**Actual Outcome:**
Copying the guide's configuration for the Firebase deployment to package.json produces syntax errors.
![deploy_configure_error](https://cloud.githubusercontent.com/assets/18269875/14340533/750ffdde-fc3d-11e5-83a6-d2e047400976.png)

**Comment by matthewp** [comment]
Thanks, so should we just get rid of the outer `{ }`?

**Comment by starlap** [comment]
Hey!

That's what I would recommend, but maybe run it by Justin since I'm a
newb and I'm not sure how he wants to manage my bugs.

**Comment by justinbmeyer** [comment]
I think we should add CanJS style highlighting.

**Comment by matthewp** [comment]
This has been superseded by `donejs add firebase` so is no longer needed.
