### ISSUE TITLE
donejs Quick Start Guide Inconsistent Steps

### ISSUE THREAD

**Issue by starlap** [donejs/donejs#616]
**Inconsistent Explanation of Expected Steps**

**Explanation:**
In sections 
- Setup
- Messages

whenever a command elicits prompts, the guide reflects this, and provides guidance about the expected inputs to prompts.

**Expected Result:**

_Guide Section_ Cordova Install

The Cordova install prompts the user for input.  The guide reflects this and provides guidance about the expected inputs. 

**Actual Outcome:**
The Cordova install prompts the user for input.  The guide does not reflect this and does not provide guidance about the expected inputs. 

**Setup Section:**
![question_prompt_setup](https://cloud.githubusercontent.com/assets/18269875/14341038/9676e186-fc42-11e5-8547-9fc5f87563ac.png)

**Message Section**
![question_prompts_message](https://cloud.githubusercontent.com/assets/18269875/14341039/9a1a904e-fc42-11e5-8f97-58423fa24d83.png)

**Cordova Section**
![cordova_section](https://cloud.githubusercontent.com/assets/18269875/14341102/42829da8-fc43-11e5-914b-58739d90ee65.png)

**Cordova Prompts**
![question_prompts_cordova](https://cloud.githubusercontent.com/assets/18269875/14341040/9c7e5e60-fc42-11e5-872a-3b5f4c77ee6c.png)

**Comment by matthewp** [comment]
This has been updated to instruct the users to accept the defaults.
