### ISSUE TITLE
Error Encountered When Performing Cordova Build in donejs Quick Start Guide

### ISSUE THREAD

**Issue by starlap** [donejs/donejs#617]
**Error When Performing Cordova Build in Ubuntu**

**Environment:**
Ubuntu 15.04
Node 4.4.2
Chrome

**Steps:**

_Guide Section_ Desktop and Mobile Apps.Cordova
1. Make sure latest version of Android Studio is installed
2. In the console, run `donejs add cordova` 
3. In the console, run `donejs build cordova`

**Expected Outcome:**
  After the installation, we should see the emulator running the Cordova application.

**Actual Outcome:**
After, the installation, I get an error message.  
The error message that I received is this:

sudo donejs add cordova
[sudo] password for starla: 
? Name of project for Cordova donejs chat
? ID of project for Cordova com.donejs.donejschat
? What platforms would you like to support (needs SDK installed) Ubuntu
npm WARN package.json donejs-chat@0.0.0 No repository field.
npm WARN package.json donejs-chat@0.0.0 No license field.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
steal-cordova@0.1.3 node_modules/steal-cordova
├── pdenodeify@0.1.0
├── xtend@4.0.1
├── async@1.5.2
├── es6-promise@2.3.0
├── fs-extra@0.19.0 (jsonfile@2.2.3, graceful-fs@3.0.8)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── rimraf@2.5.2 (glob@7.0.3)
├── multi-glob@0.4.0 (glob@7.0.3, lodash@4.9.0)
└── cordova@5.4.1 (underscore@1.7.0, q@1.0.1, ansi@0.3.1, nopt@3.0.1, update-notifier@0.5.0, cordova-lib@5.4.1)
starla@joe-ThinkPad-E555:~/MEGA/Bitovi_Work/donejs-chat/donejs-chat$ sudo donejs build cordova

> donejs-chat@0.0.0 build /home/starla/MEGA/Bitovi_Work/donejs-chat
> node build "cordova"

OPENING: /home/starla/MEGA/Bitovi_Work/donejs-chat/package.json!npm
/home/starla/MEGA/Bitovi_Work/donejs-chat/build.js:26
  buildPromise.then(stealCordova.build).then(stealCordova.Ubuntu.emulate);
                                                                ^

TypeError: Cannot read property 'emulate' of undefined
    at Object.<anonymous> (/home/starla/MEGA/Bitovi_Work/donejs-chat/build.js:26:65)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

npm ERR! Linux 4.2.0-35-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build" "cordova"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE
npm ERR! donejs-chat@0.0.0 build: `node build "cordova"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the donejs-chat@0.0.0 build script 'node build "cordova"'.
npm ERR! This is most likely a problem with the donejs-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build "cordova"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs donejs-chat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls donejs-chat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/starla/MEGA/Bitovi_Work/donejs-chat/npm-debug.log
Error: Command `npm` did not complete successfully
    at ChildProcess.<anonymous> (/home/starla/MEGA/Bitovi_Work/donejs-chat/node_modules/donejs-cli/lib/utils.js:37:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

**Comment by phillipskevin** [comment]
I think steal-cordova only supports emulators for `ios` and `android`: https://github.com/stealjs/steal-cordova/blob/master/lib/main.js#L88-L107. 

donejs-cordova allows you to select `'ios'`, `'android'`, `'wp8'`, `'windows'`, `'amazon-fireos'`, `'blackberry10'`, `'Firefox OS'`, or `'Ubuntu'`. Should we just remove these other options? I don't know if there's much benefit in letting people build for these other (mostly defunct) platforms.

I also think we could probably improve the Quick Start guide to make it clear that you're selecting the platform that you want to build the app for, not the platform you're building on.

cc @justinbmeyer @chasenlehara

**Comment by matthewp** [comment]
I vote get rid of if it can't be done generically.
