### ISSUE TITLE
Need to restart the server to see file changes

### ISSUE THREAD

**Issue by akagomez** [donejs/donejs#618]
It seems to be isolated to files served via:

```
// index.stache

{{{pageComponent}}}
```

```
// app.js

stache.registerHelper('pageComponent', function(options){
  var pageComponent = options.context.attr('pageComponentConfig');
  var template =
      '<can-import from="egowall/pages/' + pageComponent.moduleName + '/">' +
        '{{#if isResolved}}' +
          '{{#with ../.}}' + pageComponent.component + '{{/with}}' +
        '{{else}}' +
          'Loading...' +
        '{{/if}}' +
      '</can-import>';

  return stache(template)(this, options.helpers, options.nodeList);
});
```

**Comment by matthewp** [comment]
Are these listed under "system.bundle" in your package.json?

**Comment by matthewp** [comment]
Like this: https://github.com/donejs/bitballs/blob/master/public/package.json#L64

**Comment by akagomez** [comment]
Nope. I'll give that a go.

**Comment by akagomez** [comment]
Darn. That didn't do it for me.

**Comment by akagomez** [comment]
Wait! Just realized I may have had it in the wrong place.

**Comment by akagomez** [comment]
Nice! It doesn't live reload, but it does serve up the latest when I refresh (which is far more important).

**Comment by matthewp** [comment]
It definitely should live reload. If you're changing a module listed under `bundle` that should live-reload just like any other module.

**Comment by akagomez** [comment]
I'm seeing another issue now that seems related. My `component.js` files aren't being run. I think something's not resolving in my LESS.

**Comment by matthewp** [comment]
This should be fixed by https://github.com/canjs/can-fixture/pull/25, reopen if not.
