### ISSUE TITLE
Tabs styles are broken. (1)

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#62]
<img width="621" alt="place_my_order" src="https://cloud.githubusercontent.com/assets/78602/9217667/14ec0baa-4090-11e5-96a8-3c55b60e12ac.png">

**Comment by daffl** [comment]
This has been fixed via

- https://github.com/bitovi-components/bit-tabs/commit/e805c68ace630131e2a8ef49adc4f0005af15539
- https://github.com/donejs/donejs/commit/789f8c42989474747838002d20e67187c9dd7f5f
- https://github.com/donejs/place-my-order-assets/commit/02f9622b4a4b5a241995eb523dd45db28119fbe5

**Comment by daffl** [comment]
We are now providing a bit-tabs module that does not load its styles. Turned out that overriding the LESS was not very reliable.
