### ISSUE TITLE
User Issue-Inconsistent Visuals in DoneJS Guide

### ISSUE THREAD

**Issue by starlap** [donejs/donejs#626]
**Inconsistent Visuals In The Guide**

**Explanation:**
At some points in the guide, there is a blue border that seems to be giving tips to the user.  There are only a few times when this is used but there are many other times when the user is given tips. This seems inconsistent.  

The first three examples show the blue border/info sections versus some other "tips" sections that did not have a blue border:

**Examples**

**Example Blue Border 1**
![routing_info_highlight](https://cloud.githubusercontent.com/assets/18269875/14552438/54c90ff0-0293-11e6-86cf-652df39bdc3e.png)

**Example Blue Border 2**
![routeurl_highlight](https://cloud.githubusercontent.com/assets/18269875/14552441/57adaf00-0293-11e6-852b-4cf5fc44351b.png)

**Example Blue Border 3**
![error_message_highlight](https://cloud.githubusercontent.com/assets/18269875/14552448/5f545d62-0293-11e6-8b1e-75584ff4bf19.png)

**Example No Border**
![generate_custom_info_no highlight](https://cloud.githubusercontent.com/assets/18269875/14552452/631f067c-0293-11e6-8ea8-a001150bd867.png)

**Example No Border**
![Uploading Modular_tip.png…]()

![realtime_connection_tip](https://cloud.githubusercontent.com/assets/18269875/14552571/8bb5921c-0294-11e6-8f42-b6d35887eb02.png)

**Comment by justinbmeyer** [comment]
@starlap thanks for reporting.  Can you break these out into separate issues?

Regarding Issue #1 ...

Why are "Example No Border" considered tips? Why would they be in a blue "notice" section?

The way I look at those blue "notice" sections is that they are special asides.  The other content doesn't warrant the same level of special attention.

**Comment by starlap** [comment]
Hi Justin, 

You're welcome!
I certainly can break these out into separate issues. 

Regarding Issue #1:
That makes sense to me. Sounds good!
