### ISSUE TITLE
Wrong diff shown when adding Bootstrap

### ISSUE THREAD

**Issue by chasenlehara** [donejs/donejs#627]
In [this section](https://donejs.com/Guide.html#section=section_Addittothepage) of the guide, we add Bootstrap to our `index.stache` file, but the diff shows us adding the import for the view model instead of importing Bootstrap.
<img width="842" alt="screen shot 2016-04-16 at 9 39 46 pm" src="https://cloud.githubusercontent.com/assets/10070176/14585089/dda01a60-041b-11e6-9cbc-112fb89f3aca.png">

**Comment by phillipskevin** [comment]
This is fixed in major.
