### ISSUE TITLE
The src/home.component shouldn’t have the DoneJS logo header

### ISSUE THREAD

**Issue by chasenlehara** [donejs/donejs#628]
In [this section of the guide](https://donejs.com/Guide.html#section=section_Navigatebetweenpages), we instruct users to add the DoneJS header to the `home.component` template, but it’s already added in [another section](https://donejs.com/Guide.html#section=section_Addittothepage).

This diff shouldn’t have the `h1`:
<img width="884" alt="screen shot 2016-04-16 at 9 41 22 pm" src="https://cloud.githubusercontent.com/assets/10070176/14585092/0762d19e-041c-11e6-99db-55b2567bd7bf.png">

**Comment by phillipskevin** [comment]
The first time, we are adding it to index.stache. In the later section, we are moving it to the home.component. That's why it says:

>First, let's update src/home.component with the original content from the homepage and a link to the chat messages page:

I think the highlighting is correct. Please re-open if you disagree.
