### ISSUE TITLE
The diff for updating src/index.stache to switch between pages is incorrect

### ISSUE THREAD

**Issue by chasenlehara** [donejs/donejs#629]
The diff in [this section](https://donejs.com/Guide.html#section=section_Navigatebetweenpages) should highlight `{{#eq page 'chat'}}` through `{{/eq}}`. Additionally, it doesn’t have the header we added in [this section](https://donejs.com/Guide.html#section=section_Addittothepage).

Right now it’s highlighting this:
<img width="844" alt="screen shot 2016-04-17 at 8 50 25 am" src="https://cloud.githubusercontent.com/assets/10070176/14588282/2f4f9698-047a-11e6-857a-9977e63182a6.png">

**Comment by matthewp** [comment]
This is fixed in 1.0. Going to remove it from that epic.

**Comment by phillipskevin** [comment]
This was fixed in 0.9 also with #695.
