### ISSUE TITLE
re-attachment flash

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#631]
At this step: http://127.0.0.1:2020/place-my-order.html#section=section_Switchbetweencomponents

The <pmo-home> content wasn't shown until I refreshed.  It seems like SSR is also not working.  The homepage is not displayed.

**Comment by matthewp** [comment]
Worked for me:

![screen shot 2016-04-21 at 3 22 11 pm](https://cloud.githubusercontent.com/assets/361671/14721607/3fa02414-07d5-11e6-9c2d-a8830810dda5.png)

<img width="871" alt="screen shot 2016-04-21 at 3 21 58 pm" src="https://cloud.githubusercontent.com/assets/361671/14721610/439bd6d0-07d5-11e6-9586-dcb82ccb6f45.png">

**Comment by matthewp** [comment]
My guess is that the file watcher didn't get triggered. What version of OSX @justinbmeyer ?  Might need os version specific file watcher options because they can be more/less sensitive.

Going to try it again anyways.

**Comment by matthewp** [comment]
I am seeing the reattachment flash though.

**Comment by justinbmeyer** [comment]
OSX 10.11.2
