### ISSUE TITLE
Update PMO guide and generators to use new store syntax.

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#633]
- use set algebra
- use new store restful hookup
- use `store.getList` instead of `store.findAll`

**Comment by phillipskevin** [comment]
@justinbmeyer can you explain what the middle bullet means?
> use new store restful hookup

**Comment by phillipskevin** [comment]
This is talking about using the algebra in the fixture.store like
```
const store = fixture.store(json, Order.algebra);
```

**Comment by phillipskevin** [comment]
closed by https://github.com/donejs/donejs/issues/817.
