### ISSUE TITLE
Changing the app view model does not live reload

### ISSUE THREAD

**Issue by daffl** [donejs/donejs#634]
After creating and starting a new application with 0.9.2, when changing e.g. the message in `src/app.js` the page does not live-reload. A hard reload does show the change.

**Comment by matthewp** [comment]
Seems to be working now, must have been fixed in the time since this was filed :( sorry for not getting to this sooner.

![lrlol](https://cloud.githubusercontent.com/assets/361671/22436571/a3e310f6-e6f2-11e6-9696-546b0692adf3.gif)
