### ISSUE TITLE
PMO - Deploy to Heroku - Real time not working

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#639]
![place-my-order](https://cloud.githubusercontent.com/assets/78602/14727635/99902f9c-07f2-11e6-8619-652876e08e62.png)

This might be a known issue, but we aren't proxying the socket connection or changing the url it seems.

**Comment by matthewp** [comment]
@justinbmeyer did you create the Procfile shown here? https://donejs.com/place-my-order.html#section=section_DeployyourNodecode

**Comment by justinbmeyer** [comment]
@matthewp yeah

**Comment by justinbmeyer** [comment]
I'll be pushing to my pmo repo in a moment.

**Comment by justinbmeyer** [comment]
What I just merged for the CD step: https://github.com/justinbmeyer/place-my-order

**Comment by justinbmeyer** [comment]
Shows procfile:

![obscure-river-65999_ _resources___heroku](https://cloud.githubusercontent.com/assets/78602/14728020/aac24cba-07f6-11e6-960a-fa6748b93bfc.png)

**Comment by justinbmeyer** [comment]
My app: https://obscure-river-65999.herokuapp.com/order-history

**Comment by matthewp** [comment]
https://github.com/donejs/done-serve/issues/5

**Comment by matthewp** [comment]
This is working for me locally now (proxying to http://www.place-my-order.com/api)

**Comment by matthewp** [comment]
Going to close.
