### ISSUE TITLE
Simplify PMO deploy

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#640]
Ideally, it could look something like:

_previously in the CI section_

`donejs add travis`

Then in the Deploy section:
### static hosting on firebase
1. Sign up for firebase
2. Run `donejs add firebase <app-name>` ... this installs the firebase deploy, updates package.json.

remaining steps are the same.
### Deploy your node code
1.  Download heroku toolbelt, login/create.
2.  `donejs add heroku <heroku-app-name>` - configs heroku, creates proc file.
3.  update procfile to add proxy.
4.  remaining steps are the same
### Continuous Deploy
1.  `donejs add travis-to-heroku`
2.  `donejs add travis-to-firebase`

Ideally those could run `travis-encrypt` in the right way to fill out `.travis.yml`.

**Comment by matthewp** [comment]
@justinbmeyer @phillipskevin Seeing if you all think this is worth doing. It would surely make doing the PMO guide easier but would likely take a while to do as it is adding 4 new generators that we haven't made yet.

**Comment by phillipskevin** [comment]
I think this is worth doing. I do not think this is worth doing prior to releasing 1.0.

**Comment by matthewp** [comment]
We are deferring this to 1.1-ish.

**Comment by matthewp** [comment]
@m-mujica Link to this issue when you do the guide updates for this.
