### ISSUE TITLE
User Issue- Confusing Wording Under Bootstrap Section

### ISSUE THREAD

**Issue by starlap** [donejs/donejs#642]
**Confusing Wording Under Bootstrap Section**

**Explanation:**
In the Bootstrap section, the wording "The highlighted lines have been added or changed" was not immediately clear to me that I needed to make the changes shown in the example. In other, similar, parts of the guide, the user is told to "Update ________ to look like this"

**Examples:**

**Bootstrap Instructions**
![bootstrap_update](https://cloud.githubusercontent.com/assets/18269875/14552806/21d1742c-0296-11e6-8d32-78bacdc50f9f.png)

**VS. Messages Instructions**
![messages_instruction](https://cloud.githubusercontent.com/assets/18269875/14552808/296851f6-0296-11e6-98db-893cd448c4fc.png)

**And Messages Instructions**
![update_messages_message](https://cloud.githubusercontent.com/assets/18269875/14552811/2d35b35a-0296-11e6-962f-31aa0d275968.png)

**Comment by justinbmeyer** [comment]
@starlap I'm sorta confused what you mean.  It says right before that box:

Update `src/index.stache` to look like this:

**Comment by justinbmeyer** [comment]
are you saying the box might distract users from the "update" message?

**Comment by starlap** [comment]
Yes, that's probably a better way to put it.  It's a bit distracting.

**Comment by matthewp** [comment]
Fixed by #816
