### ISSUE TITLE
User Issue- Highlighted Sections are Difficult to See

### ISSUE THREAD

**Issue by starlap** [donejs/donejs#643]
**Highlighted Sections are Very Faint and Hard to See**

**Explanation:**
Throughout the guide the blue highlighted sections, that indicate commands to be edited, are very hard to see. At some screen angles, (a very upright angle) the blue highlights weren't visible at all. 

**Example**

![faint-highlights](https://cloud.githubusercontent.com/assets/18269875/14552858/b72fbd4e-0296-11e6-8f07-09e692d3a977.png)

**Comment by matthewp** [comment]
Aren't these green?

**Comment by justinbmeyer** [comment]
Does it seem like the highlighting is on the wrong lines in that example?  

I think the colors are fine.  Maybe take a picture of a monitor that looks bad.
