### ISSUE TITLE
City Not Showing Up with NW on Ubuntu 12.04 on ChromeOS

### ISSUE THREAD

**Issue by ZebGirouard** [donejs/donejs#645]
Hi guys,

Unsure if this is a reproducible issue for you (or if you care too much) since it seems to be unique to Unity running on ChromeOS.

The error I see on loading the NW linux64 place-my-order app is:

~/repos/place-my-order/build/place-my-order/linux64$ ./place-my-order 
[16883:0423/170830:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
Gtk-Message: Failed to load module "unity-gtk-module"
[16883:0423/170830:INFO:audio_manager_pulse.cc(258)] Failed to connect to the context.  Error: Connection refused
ATTENTION: default value of option force_s3tc_enable overridden by environment

And after it loads, things look "generally" good, but, in the Restaurants tab, when clicking the State from the dropdown, all I see is "Choose a City".  I am 99% sure I had the city model base-url updated, because when I closed it (with identical text to the walkthrough), it didn't prompt me to save changes.  So I don't think it's that, but unsure what it might be.

If you'd like to look at my repo code to see if it's something silly I forgot, you can [check it out here.](https://github.com/ZebGirouard/place-my-order)

**Comment by matthewp** [comment]
Hey, sorry for taking a long time to reply. Are you still experiencing this issue? If so I'll fire up a VM and take a look.

**Comment by matthewp** [comment]
Closing, if you're still having an issue let me know.
