### ISSUE TITLE
Conflict with ES6 Map

### ISSUE THREAD

**Issue by minsooshin** [donejs/donejs#646]
When we create a component by `donejs add component example example`, it creates javascript file (example.js). It has the line `import Map from 'can/map/';`. There is possibility this `Map` name can be conflict with `Map` of ES6.
Can we use different name for it such as `CanMap` for scaffolding?

**Comment by justinbmeyer** [comment]
Yeah, I think this is probably a good idea.  Tools like JSHint also complain about it.

**Comment by justinbmeyer** [comment]
This will be closed by: https://github.com/donejs/donejs/issues/707
