### ISSUE TITLE
Wrong Keyword in Update in In-depth Guide

### ISSUE THREAD

**Issue by starlap** [donejs/donejs#649]
**Environment**
Ubuntu 15.04
Node 4.4.3 LTS
Chrome

**Wrong Keyword Used/Does Not Reflect the Keyword Listed in the User Console**

**Steps:**
1. Go to "Getting Date From the Server"
2. Go to "Add Data to the Page"
3. Go to the update box for `src/restaurant/list/list.js`

**Explanation:**
The keyword used in the update box is 'var' but the user's consul says "const", so the user has to update more than what is highlighted in the box.

**Example**

![wrong_wording](https://cloud.githubusercontent.com/assets/18269875/14756601/7e7ba03a-089f-11e6-93b1-0bbe6a886305.png)

**Comment by phillipskevin** [comment]
This is fixed in `major`.
