### ISSUE TITLE
Confusing/Incorrect Update Instructions In In-Depth Guide

### ISSUE THREAD

**Issue by starlap** [donejs/donejs#650]
**Environment**
Ubuntu 15.04
Node 4.4.3 LTS
Chrome

**Confusing/Incorrect Update Instructions in Guide**

**Steps:**
1. Go to "Setting Up Routing"
2.  Go to "Create a Loading Indicator"
3. Go to the update box for `src/loading.component`

**Explanation**
The elements in the box do not match what the user is seeing, before they are to edit the data.

**Example**

![elements_routing](https://cloud.githubusercontent.com/assets/18269875/14756235/a9776bdc-089c-11e6-84a7-b00f997202ee.png)

**Note**
I might suggest a global cut and paste for the box

**Comment by justinbmeyer** [comment]
I'm not sure what you mean by "before they are to edit the data" because it's only showing what the file should be updated to.  Perhaps you mean that the inserted area should include `<template>`.

**Comment by justinbmeyer** [comment]
Closing for https://github.com/donejs/donejs/issues/708
