### ISSUE TITLE
Confusing/Incorrect Update Instructions In In-Depth Guide

### ISSUE THREAD

**Issue by starlap** [donejs/donejs#651]
**Environment**
Ubuntu 15.04
Node 4.4.3 LTS
Chrome

**Confusing/Incorrect Update Instructions in Guide**

**Steps:**
1.  Go to "Creating a Homepage Element"
2.  Go to the box that shows the elements to be updated in `src/home.component`

**Explanation**
The elements in the box do not match what the user is seeing, before they are to edit the data.

**Example**

![elements_update](https://cloud.githubusercontent.com/assets/18269875/14755842/dee9be62-0899-11e6-8ad6-8b9872dd87b3.png)

**Notes**
I might suggest a global copy and paste, in this box.

**Comment by justinbmeyer** [comment]
Closing for https://github.com/donejs/donejs/issues/708
