### ISSUE TITLE
Default "Please choose an item" Message in In-Depth Guide

### ISSUE THREAD

**Issue by starlap** [donejs/donejs#653]
**The Order Section Defaults to "Please Choose An Item" Error Message** 

**Environment:**
Ubuntu 15.04
Chrome

**Explanation:**
The "Please Choose An Item" message is present, in the ordering section, immediately upon landing on the ordering page.  I wasn't sure if this was intentional.  
![ezgif com-video-to-gif 4](https://cloud.githubusercontent.com/assets/18269875/14695019/d0e1470e-0722-11e6-86aa-ea2ed8e7fffb.gif)

**Comment by justinbmeyer** [comment]
intentional, thanks!
