### ISSUE TITLE
Blank Screen Occurs With Trailing Slash Addition to URL in In-Depth Guide

### ISSUE THREAD

**Issue by starlap** [donejs/donejs#654]
**Blank Screen Appears With Use of Trailing Slash on ALL URLs except the Homepage**

**Environment:**
Ubuntu 15.04
Chrome

**Steps:**
1. Click on the "Restaurants" tab, from the homepage.
2. In the URL section, place a trailing slash at the end of the URL, and press enter.

**Expected Outcome:**
After adding a trailing slash to the "Restaurants" URL, the user should  be directed to the "Restaurants" landing page.

**Actual Outcome:**
After adding a trailing slash to the "Restaurants" URL, the screen goes blank.

**Note:**
This occurrence also happens with the same process for the "Order History" URL

![ezgif com-video-to-gif 3](https://cloud.githubusercontent.com/assets/18269875/14694829/3e7152fc-0721-11e6-9fcd-929f7ed5c5ef.gif)

**Comment by justinbmeyer** [comment]
Should we support a generic 404?  Or should we have a default case?

**Comment by phillipskevin** [comment]
I think the best solution would be to provide a way to define a route with optional trailing slashes.

Currently, you can make this work by specifying your routes like:
```
route('{page}', { page: 'home' });
route('{page}/', { page: 'home' });
route('{page}/{slug}', { slug: null });
route('{page}/{slug}/', { slug: null });
route('{page}/{slug}/{action}', { slug: null, action: null });
route('{page}/{slug}/{action}/', { slug: null, action: null });
```

but, (1) this is ugly and (2) you get warnings about the matching routes:

```
WARN: two routes were registered with matching keys:
	(1) route("{page}", {"page":"home"})
	(2) route("{page}/", {"page":"home"})
(1) will always be chosen since it was registered first
WARN: two routes were registered with matching keys:
	(1) route("{page}/{slug}", {"slug":null})
	(2) route("{page}/{slug}/", {"slug":null})
(1) will always be chosen since it was registered first
WARN: two routes were registered with matching keys:
	(1) route("{page}/{slug}/{action}", {"slug":null,"action":null})
	(2) route("{page}/{slug}/{action}/", {"slug":null,"action":null})
(1) will always be chosen since it was registered first
```

Being able to do something like this would be nice:
```
route('{page}/?', { page: 'home' });
```

**Comment by matthewp** [comment]
I don't think this is a bug, adding a trailing slash is a different route. Don't use the wrong route. 🙂

**Comment by justinbmeyer** [comment]
I do think can-route should support some way of saying `appVM.route` is `undefined` ... and letting the dev supply a 404 page.

**Comment by matthewp** [comment]
This is an ssr bug, this should already be producing a 404.

**Comment by matthewp** [comment]
Underlying issue: https://github.com/donejs/done-ssr/issues/217

**Comment by matthewp** [comment]
Fixed by https://github.com/donejs/done-ssr/pull/218
