### ISSUE TITLE
Update the Quick Start guide test to use donejs add firebase

### ISSUE THREAD

**Issue by chasenlehara** [donejs/donejs#663]
This section of the Quick Start guide test needs to be updated to use `donejs add firebase`: https://github.com/donejs/donejs/blob/852918d820ee740cc3b946f117186d0e9c90bcaf/guides/guide/test.js#L280-L309

**Comment by justinbmeyer** [comment]
It seems like this has been done?

**Comment by matthewp** [comment]
Does this issue mean we can get rid of donejs-deploy?

**Comment by chasenlehara** [comment]
@justinbmeyer, this hasn’t been done. See the [same lines in master](https://github.com/donejs/donejs/blob/master/guides/guide/test.js#L301-L302) that update the `package.json` file with [the deploy configuration](https://github.com/donejs/donejs/blob/master/guides/guide/steps/16-cdn/deploy.json).

**Comment by chasenlehara** [comment]
@matthewp, I don’t think this means we can get rid of donejs-deploy; it’s just for updating the tests to use donejs-firebase.

**Comment by matthewp** [comment]
Isn't it true that if you use donejs-firebase you are not using donejs-deploy? Looking at the code that seems to be true: https://github.com/donejs/donejs-firebase/blob/master/default/index.js#L38-L39  I might be missing something though.

We would like to defer installing so many things up front on `donejs add app`, so getting rid of donejs-deploy would be great.

**Comment by matthewp** [comment]
Oh sorry, this is about the tests!

**Comment by chasenlehara** [comment]
Yeah, this is just about updating the tests.

If I understand how everything works together, then it’d be nice to have the Firebase logic from donejs/deploy in the donejs-firebase repo.

**Comment by phillipskevin** [comment]
@matthewp took care of this with https://github.com/donejs/donejs/commit/4fe67f9b969ae2a483699642eece01d90bf9f020.
