### ISSUE TITLE
Circular references in imports cause donejs to hang

### ISSUE THREAD

**Issue by bmomberger-bitovi** [donejs/donejs#666]
Environment: node 0.12.14, npm 3.9.0.

Repro steps:
- create a donejs component with a script that:
  - exports named items
  - imports another script, which imports a named export from the first script.
    This is packaged into an example donejs app here: [steal-cirdep.zip](https://github.com/donejs/donejs/files/291486/steal-cirdep.zip)
- Run `donejs develop` and navigate directly to that components demo page (`/src/components/cirdep/cirdep.html` in the example app)
  - No problem, loads fine.
- Import the component from your app's `index.stache` with `can-import`
- Navigate to `/`
  - donejs hangs and will not serve anything until restart.

I've had hit & miss results when trying this with a production build (`donejs build && donejs start`).  The app in which I saw this issue happening would build and run fine in production, but my demo app also hangs in production.

There shouldn't be a reason why circular deps can't be handled on the server if they can be handled on the client, right?

---

Additional notes: Node 4.4.2 hangs completely even on the demo html.

**Comment by matthewp** [comment]
Hey @bmomberger-bitovi !  So this happens only on the server, right?

**Comment by bmomberger-bitovi** [comment]
That's the impression that I get.  Depending on your node version (and maybe node modules' versions?) it will either hang on the first page load with a circular dep, or it will immediately spinlock at 100% CPU usage on startup.

**Comment by matthewp** [comment]
Not sure what the problem *was* but no longer an issue in 1.0.0: https://github.com/matthewp/steal-circdep

![screen shot 2017-02-10 at 3 37 19 pm](https://cloud.githubusercontent.com/assets/361671/22843350/2a8582b2-efa7-11e6-962a-ec9721a56060.png)
