### ISSUE TITLE
Docs Features: broken link Server-side-rendering

### ISSUE THREAD

**Issue by ilyavf** [donejs/donejs#668]
Clicking on Server-side-rendering which links to https://donejs.com/Features.html#section=section_ServerSideRendered__Howitworks__PreppingyourappforSSR does not work:

![image](https://cloud.githubusercontent.com/assets/1895948/15844485/b3877774-2c38-11e6-8ff5-ca9a76d6ca03.png)

**Comment by matthewp** [comment]
This works in the new bit-docs site.
