### ISSUE TITLE
Confusing Updates to Script in PMO Guide

### ISSUE THREAD

**Issue by starlap** [donejs/donejs#672]
**Environment**
Mac El Capitan
Chrome

**Confusing Updates to Highlighted Script Changes in PMO Guide**

**Steps:**
1.  Go to [Create the Order History Element](https://donejs.com/place-my-order.html#section=section_Createtheorderhistoryelement)
2.  Go to the box that shows the script to be updated in `src/order/history.component`

**Explanation**
Throughout the guide, there are instruction boxes where the script that is to be updated does not seem to match what exists in the current script.  

**Example**
[AddingHeaderElementBug.pdf](https://github.com/donejs/donejs/files/351216/AddingHeaderElementBug.pdf)

**Notes**
I suggest a global copy and paste for all of the updates.  Several times, I have messed up a step by coping and pasting things wrong or having the updated script be slightly off from what is present in the current script.  I think this might eliminate any confusion.

**Comment by justinbmeyer** [comment]
Closed by: https://github.com/donejs/donejs/issues/708
