### ISSUE TITLE
Differentiation Between Consoles in PMO Guide

### ISSUE THREAD

**Issue by starlap** [donejs/donejs#673]
**Environment**
Mac El Capitan
Chrome

**Differentiation Between Consoles in PMO Guide Text**

**Steps:**
1.  Go to [Test the Connection](https://donejs.com/place-my-order.html#section=section_Testtheconnection)

**Explanation**
Not differentiating between when an update is to be made in the **browser** console makes things confusing.

**Example**
[BrowserConsoleTextQuestion.pdf](https://github.com/donejs/donejs/files/351228/BrowserConsoleTextQuestion.pdf)

**Another Example**
This is located at [Setting Up Travis CL](https://donejs.com/place-my-order.html#section=section_SettingupTravisCI)

<img width="669" alt="consoleterminology_2" src="https://cloud.githubusercontent.com/assets/18269875/16640181/bd8b15a8-43aa-11e6-9276-da7d31d5d5e3.png">

**Notes**
I suggest specifying "browser" console when the update is to be made in the browser console.

**Comment by justinbmeyer** [comment]
command terminal vs browser console.

**Comment by matthewp** [comment]
Fixed by #816
