### ISSUE TITLE
Text Errors in Instructions in PMO Guide

### ISSUE THREAD

**Issue by starlap** [donejs/donejs#674]
**Environment**
Mac El Capitan
Chrome

**Text Errors in Instructions in PMO Guide**

**Text Error #1**
**Steps:**
1) Go to [Using the global test page](https://donejs.com/place-my-order.html#section=section_Usingtheglobaltestpage)

**Explanation:**
Correction to use of the word "tests" in instructions.

**Example**
[TextError_Test.pdf](https://github.com/donejs/donejs/files/353259/TextError_Test.pdf)

**Text Error #2"
**Steps**
1.) Go to [Setting up Travis CI](https://donejs.com/place-my-order.html#section=section_SettingupTravisCI)
2.) Go to the section "Nested Routes"

**Explanation:**
Correction to use of the word "show" in instructions.

**Example:**
[textError2.pdf](https://github.com/donejs/donejs/files/353278/textError2.pdf)

**Comment by matthewp** [comment]
This was fixed in the 1.0 guide.
