### ISSUE TITLE
Conflict with Running Firefox While "Using a test runner" in PMO Guide 

### ISSUE THREAD

**Issue by starlap** [donejs/donejs#675]
**Environment**
Mac El Capitan
Chrome

**Conflict with Running Firefox While "Using a test runner"**

**Steps:**
1.  Go to [Using a test runner](https://donejs.com/place-my-order.html#section=section_Usingatestrunner)

**Explanation**
I was running the application in Firefox, initially, and when I ran this test, it gave me an error message that "Only one copy of Firefox can be open at a time".  It then shut my test down.

**Example**
<img width="1198" alt="testrunnerissue_firefox" src="https://cloud.githubusercontent.com/assets/18269875/16673451/2f5d5c1e-4463-11e6-948a-fa959dfce0c9.png">

**Notes:**
I recommend that, in the very start of the instructions, the user is told to run the application in something other than Firefox.  Otherwise, the user gets through 1/4 of the instructions to find that they need to run the application in something else in order to get the test runner to work.

**Comment by matthewp** [comment]
I think in this case it might be fine to tell them to close Firefox before running the tests.

**Comment by starlap** [comment]
Sounds good to me.

**Comment by matthewp** [comment]
Fixed by #816
