### ISSUE TITLE
Socket.io Error While Adding Real-Time Events in PMO

### ISSUE THREAD

**Issue by starlap** [donejs/donejs#676]
**Environment**
Mac El Capitan
Chrome

**Socket.io Error While "Adding Real-Time Events to a model" in PMO**

**Steps:**
1.) Go to [Update the template](https://donejs.com/place-my-order.html#section=section_Updatethetemplate)
2.) Go to the bottom of that section that states "If we now open the order page we see some already completed default orders. 

**Explanation**
After running the socket.io and updating the script, as per the instructions, I am not seeing any default orders.  The browser console is showing me 70+ socket.io error messages.

**Example**
[SocketIOerror.pdf](https://github.com/donejs/donejs/files/354624/SocketIOerror.pdf)

**Comment by matthewp** [comment]
Hey @starlap what version of donejs?

**Comment by starlap** [comment]
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
3less-engine.js:780 extend ' .clearfix' has no matches
http://localhost:8080/socket.io/?EIO=3&transport=polling&t=LNBD9zZ Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/socket.io/?EIO=3&transport=polling&t=LNBDAJQ Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/socket.io/?EIO=3&transport=polling&t=LNBDAu2 Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/socket.io/?EIO=3&transport=polling&t=LNBDC1U Failed to load resource: the server responded with a status of 404 (Not Found)
register.js:92 GET http://localhost:8080/socket.io/?EIO=3&transport=polling&t=LNBDDG4 404 (Not Found)wrappedFn @ register.js:92Request.create @ socket.io.js:3511Request @ socket.io.js:3424XHR.request @ socket.io.js:3352XHR.doPoll @ socket.io.js:3382Polling.poll @ socket.io.js:3795Polling.doOpen @ socket.io.js:3739Transport.open @ socket.io.js:2882Socket.open @ socket.io.js:2303Socket @ socket.io.js:2184Socket @ socket.io.js:2110Manager.open.Manager.connect @ socket.io.js:309(anonymous function) @ socket.io.js:619
register.js:92 GET http://localhost:8080/socket.io/?EIO=3&transport=polling&t=LNBDEUo 404 (Not Found)wrappedFn @ register.js:92Request.create @ socket.io.js:3511Request @ socket.io.js:3424XHR.request @ socket.io.js:3352XHR.doPoll @ socket.io.js:3382Polling.poll @ socket.io.js:3795Polling.doOpen @ socket.io.js:3739Transport.open @ socket.io.js:2882Socket.open @ socket.io.js:2303Socket @ socket.io.js:2184Socket @ socket.io.js:2110Manager.open.Manager.connect @ socket.io.js:309(anonymous function) @ socket.io.js:619
register.js:92 GET http://localhost:8080/socket.io/?EIO=3&transport=polling&t=LNBDFjT 404 (Not Found)

**Comment by matthewp** [comment]
From looking at the test project you sent me, it looks like the start and develop scripts aren't updated to what they should be from [this step](https://donejs.com/place-my-order.html#section=section_Startingtheapplication).

**Comment by starlap** [comment]
Ok, thanks.  I'll go in and see if I can get it working,
