### ISSUE TITLE
Upcoming Events page not up to date

### ISSUE THREAD

**Issue by chasenlehara** [donejs/donejs#681]
The [Upcoming Events](https://donejs.com/community.html) page is not up to date with the latest upcoming events.

<img width="870" alt="screen shot 2016-07-12 at 9 18 55 am" src="https://cloud.githubusercontent.com/assets/10070176/16774665/e6ae1294-4811-11e6-8332-5b0ccf94733d.png">

**Comment by chasenlehara** [comment]
@justinbmeyer, do you have any opinions on how we should store the upcoming events data, now that BitHub isn’t available?

**Comment by justinbmeyer** [comment]
Probably manually update the DoneJS calendar with any events we know and make a feed from that.
