### ISSUE TITLE
Missing image in the Bitballs guide

### ISSUE THREAD

**Issue by chasenlehara** [donejs/donejs#683]
The [Behavior section](https://github.com/donejs/donejs/blob/066465b7dedcb76dee8cb14456147b4c40e99891/docs/guides/bitballs.md#behavior) has the text “PIC:admin view of users page” where an image is supposed to be.

**Comment by matthewp** [comment]
@justinbmeyer can you take a screenshot of this? I don't have admin access to log in.  Or give me access and I'll do it.

**Comment by justinbmeyer** [comment]
<img width="784" alt="cursor_and_bitballs___users_list" src="https://cloud.githubusercontent.com/assets/78602/22945441/dcbfbf14-f2b9-11e6-828b-362aa80eabd7.png">

**Comment by matthewp** [comment]
Fixed by #816
