### ISSUE TITLE
Error While Launching the Simulator in PMO Guide

### ISSUE THREAD

**Issue by starlap** [donejs/donejs#686]
**Environment**
Mac El Capitan
Chrome

**Error While Running the DoneJS Build Cordova Command to Launch the Simulator in PMO**

**Steps:**
1.) Go to [AJAX](https://donejs.com/place-my-order.html#section=section_BuildingtoiOSandAndroid__AJAX)
2.) Go to the bottom of that section that has the user run the command `donejs build cordova` 

**Explanation**
After running the `donejs build cordova`command, the user sees the simulator screen appear but than receives an error message in the terminal. 

**Example**
![screen shot 2016-07-28 at 1 17 57 pm](https://cloud.githubusercontent.com/assets/18269875/17228772/5d9a9e7c-54c9-11e6-9412-e7521729cc55.png)

**Comment by matthewp** [comment]
Hey @starlap, I wasn't able to recreate. Can you close your simulator (use cmd+q to force it to quit all the way) and try again?
