### ISSUE TITLE
Firebase Website Has Changed and May Effect Deployment Instructions in PMO Guide

### ISSUE THREAD

**Issue by starlap** [donejs/donejs#687]
**Environment**
Mac El Capitan
Chrome

**Firebase Website Has Changed and May Effect Deployment Instructions in PMO Guide**

**Steps:**
1.) Go to [Static Hosting on Firebase](https://donejs.com/place-my-order.html#section=section_StatichostingonFirebase)
2.) The instructions here tell the user to create an account and go to the Account Page to begin creating our app.

**Explanation**
Upon going to the Firebase website and creating an account, the user interface has appeared to have changed and there is no longer an "Account" page.  It appears that the user now has to use the "Create a new Project" link.

**Example**
![screen shot 2016-07-28 at 3 03 07 pm](https://cloud.githubusercontent.com/assets/18269875/17231245/8f37b5a8-54d5-11e6-965a-a9ddbfa7cdbe.png)

**Comment by starlap** [comment]
I'm actually totally lost with how to create the app, with the new setup, in Firebase.

**Comment by matthewp** [comment]
That's right, the change in Firebase's UI is a breaking change. I'm going to update the guide to show images of the new console rather than the old one.
