### ISSUE TITLE
Blocked When Running the Deploy Application in the PMO Guide

### ISSUE THREAD

**Issue by starlap** [donejs/donejs#688]
**Environment**
Mac El Capitan
Chrome

**Blocked When Running the Deploy Application in the PMO Guide**

**Steps:**
1.) Go to [Run Deploy](https://donejs.com/place-my-order.html#section=section_StatichostingonFirebase__Rundeploy)
2.)Run `donejs build'  in the terminal.
3.)Run`donejs deploy' in the terminal.

**Explanation**
Upon running `donejs deploy` in the terminal, the user is blocked by an error message.

**Example**

![screen shot 2016-07-28 at 3 50 36 pm](https://cloud.githubusercontent.com/assets/18269875/17232310/f8ec5f20-54db-11e6-8039-b2237ac25f14.png)

**Comment by starlap** [comment]
At this point, I can't go further with the deployment.

**Comment by justinbmeyer** [comment]
@starlap make sure you've installed the latest version of donejs.  `npm install  -g donejs`

Also, when you include your environment, can you also include your version of node, npm, and donejs.

```
node -v
npm -v
donejs -V
```

**Comment by starlap** [comment]
Will do.  Thanks, Justin.  
I figured out I hadn't named my Firebase project correctly.

**Comment by matthewp** [comment]
Oh, was that the problem? There is a problem where if a user was using the old Firebase, the new cli tool is not compatible with the old version any more. They can continue to use `donejs-deploy` on existing projects, but `donejs add firebase` sets you up for the new Firebase console.  I think the best we can do there is add a note in the guides.

Taking this discussion to #687
