### ISSUE TITLE
Highlighted code on Quick start is not correct

### ISSUE THREAD

**Issue by tomgreever** [donejs/donejs#698]
This image supposedly highlights the lines of code that are to be updated, however they are incorrect. 
![screen shot 2016-08-16 at 1 48 55 pm](https://cloud.githubusercontent.com/assets/326843/17711637/3275c840-63b8-11e6-889d-3816d0cd5214.png)

These lines already exist in the app at this point in the guide:
- `<can-import from="donejs-chat/app" export-as="viewModel" />`
- `{{#switch env.NODE_ENV}}`

The blocks that should be highlighted is this line `<can-import from="bootstrap/less/bootstrap.less!" />` and the entire HTML block: 

```
<div class="container">
      <div class="row">
        <div class="col-sm-8 col-sm-offset-2">
          <h1 class="page-header text-center">
            <img src="http://donejs.com/static/img/donejs-logo-white.svg"
                alt="DoneJS logo" style="width: 100%;" />
            <br>Chat
          </h1>
        </div>
      </div>
    </div>
```

I believe the highlighted portions just need to move up by two lines.

**Comment by tomgreever** [comment]
Looking at this some more, I think that other code block highlights are also off by two lines: 
![screen shot 2016-08-16 at 2 26 29 pm](https://cloud.githubusercontent.com/assets/326843/17712862/85512f28-63bd-11e6-832a-92fb200eba42.png)

**Comment by justinbmeyer** [comment]
Fix after: https://github.com/donejs/donejs/issues/708

**Comment by phillipskevin** [comment]
Same as https://github.com/donejs/donejs/issues/764. Closing this one even though it came first, sorry @tomgreever.
