### ISSUE TITLE
Component generator allows names that won't work

### ISSUE THREAD

**Issue by tomgreever** [donejs/donejs#699]
When you do `donejs add component` the wizard allows you to input component names with only one word, like `cart` or `header` even though these names aren't allowed. All component tags have to be two words with a dash so that they don't conflict with existing HTML tags. The wizard should error if the user tries to input a single word, and message them to use at least two words separated by a dash.

**Comment by matthewp** [comment]
Thanks, this is a bug for sure, moved it to the repo where this code is: https://github.com/donejs/generator-donejs/issues/143
