### ISSUE TITLE
bug with 3.1.0 model.js

### ISSUE THREAD

**Issue by jeffli** [donejs/donejs#7]
Hi, Justin

It seems there is a bug in model.js v3.1.0 line1014:

```
        "default" : function(val, error, type){
            var construct = $.String.getObject(type)
            return construct ? construct(val) : val;
        }
```

when type is passed in as undefined, $.String.getObject(type) returns the 'DOMWindow',  which is an object instead of function;  then jquery.js throws out an exception "TypeError: object is not a function" in line 7101:  success = ajaxConvert( s, response );   This happens after an ajax call is finished,  the following was the complete call stack: 

jQuery.Class.convert.default() at model.js:1014
jQuery.Class._updateProperty() at model.js:1301
jQuery.Class._setProperty() at model.js:1277
jQuery.Class.attr() at model.js:1200
jQuery.Class.attrs() at model.js:1364
jQuery.Class.setup() at model.js:1048
extend.newInstance() at class.js:439
Class() at class.js:532
jQuery.Class.model() at model.js:770
class_cb() at class.js:396
ajaxConvert() at jquery.js:7551
done() at jquery.js:7101
jQuery.ajaxTransport.send.callback() at jquery.js:7909

Thanks

Jeff

**Comment by jupiterjs** [comment]
what is type?

**Comment by jeffli** [comment]
I have no idea.   From the call stack, in model.js line 1277:  converter.call(Class, value)   ,   the third parameter is missing,  when it gets to "default" : function(val, error, type){   ...  }    "type" becomes undefined

**Comment by jupiterjs** [comment]
I mean't what value is type.  It is undefined.  getObject(undefined) should probably be returning undefined.

**Comment by jeffli** [comment]
that was the issue,  $.String.getObject(undefined)  returns DOMWindow instead of undefined, which caused the exception "TypeError: object is not a function" in   return construct ? construct(val) : val;

**Comment by moschel** [comment]
@jeffli can you provide a breaking test case for this?
