### ISSUE TITLE
Build Development APK

### ISSUE THREAD

**Issue by indianscout** [donejs/donejs#700]
**Question:** is it possible to build a develoment APK? _donejs build cordova_ command always builds a production APK - steal.production.js with minified and compressed asstes etc.
It would be very helpful for debugging purposes to able to build a NOT minified and compressed version.
This is very useful for debugging code related to cordova plugins like barcode-reader/geolocation/camera/etc. - which work only on the mobile device.
I tried to _set NODE_ENV=_ and _set NODE_ENV=development_ but none works.
Unfortunately the docs do not mention much about this...

**Comment by matthewp** [comment]
Hi @indianscout! You can turn off minify in your `build.js` file like so:

``` js
stealTools.build({
  config: __dirname + "/package.json!npm"
}, {
  minify: false
});
```

[Here](http://stealjs.com/docs/steal-tools.BuildOptions.html) is the full set of options for that second arguments to stealTools.build.

Does this answer your question?

**Comment by indianscout** [comment]
Seems to be the right direction, but does not work:
![image](https://cloud.githubusercontent.com/assets/7571099/18106406/d8dcc8a4-6f03-11e6-9d30-d906b8f61e26.png)

Here my _build.js_:

```
var stealTools = require("steal-tools");

var buildPromise = stealTools.build({
  config: __dirname + "/package.json!npm"
}, {
  minify: false
});
// options added by `donejs add cordova` - START
var cordovaOptions = {
    buildDir: "./build/cordova",
    id: "my.app.org",
    name: "myApp",
    platforms: ["android"],
    plugins: [
        "cordova-plugin-transport-security",
        "cordova-plugin-barcodescanner",
        "cordova-plugin-geolocation"
    ],
    index: __dirname + "/production.html",
    glob: [
        "node_modules/steal/steal.production.js"
    ]
};

var stealCordova = require("steal-cordova")(cordovaOptions);
// Check if the cordova option is passed.
var buildCordova = process.argv.indexOf("cordova") > 0;

if(buildCordova) {
  buildPromise.then(stealCordova.build).then(stealCordova.android.emulate);
}
// options added by `donejs add cordova` - END
```

Any idea/hint why this does not work? THX

**Comment by pYr0x** [comment]
@indianscout maybe this can help you.
i used gulp for building the APK

https://github.com/pYr0x/testapp
https://github.com/pYr0x/testapp/blob/master/gulpfile.js

**Comment by indianscout** [comment]
@pYr0x: THX for the hint. Looks like a good way too. But since steal is shiped with donejs I'll give it another try.
@matthewp: my builds work now :-) The problem was that cordova build used the _www_ folder, but steal builds by default  into _build\cordova\www_. So actually I was building an APK from an old source and not the most recent one.
