### ISSUE TITLE
Sorry but donejs add app is inacceptable!

### ISSUE THREAD

**Issue by frank-dspeed** [donejs/donejs#702]
I have done the last few days many donejs related projects sometimes i don't know why the process takes realy realy realy much to long it needs refactoring if you don't address that i will fork donejs complet.

**Comment by frank-dspeed** [comment]
292M    .
node_modules folder !!!!

837 items thats not possible realy it isn't

**Comment by marshallswain** [comment]
@frank-dspeed I completely agree with you on it being a pain point to wait 5+ minutes to create a new app.  We've talked about creating a cache mechanism.  After seeing [yarn](https://yarnpkg.com/) today, I think it might be a good idea to build support for it.  I'd love to see starting a new project only take a few seconds.

I'm not really surprised with the size of the node_modules folder.  There's a lot of stuff in there by the time you add testing infrastructure and yeoman generator support.  Out of curiosity, how big is it if you only install the actual dependencies and not the devDependencies?

**Comment by marshallswain** [comment]
Hopefully I'll get some time to play with this issue: https://github.com/donejs/generator-donejs/issues/147

**Comment by justinbmeyer** [comment]
It does take a long time to install. But generally speaking, it's a one time cost. Why have you done it so many times?

Also, consider what you're getting by looking at the feature list. You'd create a similar size node_modules folder with any comparable solution.

**Comment by justinbmeyer** [comment]
Closing for https://github.com/donejs/generator-donejs/issues/145
