### ISSUE TITLE
Pick node version support

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#705]
Lets pick a good version of Node to support for 1.0.

Considerations:
- What people will be using when starting a DoneJS application.
- How much "extra" we have to install based on different node versions.
- Complexity of other node versions.
- Node operating system support.

**Comment by matthewp** [comment]
A big consideration would be what version their servers are using, since done-ssr has to run in production.

Would be interesting to hear what our users are using. I know of one company that uses Node 0.10 still I believe.

**Comment by justinbmeyer** [comment]
Uses only that version without allowing new apps to run different versions?

**Comment by daffl** [comment]
I think the main consideration should be the official [Node LTS schedule](https://github.com/nodejs/LTS):

<table>
<tr>
  <th>LTS Status</th>
  <th>Release</th>
  <th>LTS Start</th>
  <th>Maintenance Start</th>
  <th>LTS End</th>
</tr>
<tr>
  <td><b>Maintenance</b></td>
  <td>v0.10</td>
  <td>-</td>
  <td>2015-10-01</td>
  <td>2016-10-31</td>
</tr>
<tr>
  <td><b>Maintenance</b></td>
  <td>v0.12</td>
  <td>-</td>
  <td>2016-04-01</td>
  <td>2016-12-31</td>
</tr>
<tr>
  <td><b>Active</b></td>
  <td>v4</td>
  <td>2015-10-01</td>
  <td>2017-04-01</td>
  <td>2018-04-01</td>
</tr>
<tr>
  <td>N/A</td>
  <td>v5</td>
  <td colspan="3" align="center">N/A</td>
</tr>
<tr>
  <td><b>Pending</b></td>
  <td>v6</td>
  <td>2016-10-18</td>
  <td>2018-04-18</td>
  <td>2019-04-18</td>
</tr>
</table>

That means official support for 0.10 and 0.12 can be removed by 2016-12-31
I'd also go as far as only supporting latest for DoneJS and LTS + latest for done-ssr.

**Comment by frank-dspeed** [comment]
we can easy support 4+ i am into the ES7/8 Roadmap and know the Mozilla Roadmaps.

every one who uses node 0.10 0.12 should do npm install -g n and then n stable to upgrade to node 4 thats it. or n latest so node upgrades arn't a problem on any operating system the npm package n does that realy well. I am DevOps Special.

**Comment by frank-dspeed** [comment]
but when you whant to do that you should add my proposed package updates for documentjs and testee as both contain dependencys that are realy outdated. So outdated that it don't installs on all systems :) simply compare the package.json of https://github.com/dssrv/testee and https://github.com/dssrv/documentjs

my versions are 100% working tested on all relevant systems as i use docker for testing the build on diffrent node versions.

**Comment by phillipskevin** [comment]
There is a poll here to help us make the decision: http://forums.donejs.com/t/node-version-support-for-donejs-1-0/517. Please fill it out if you're interested.

**Comment by frank-dspeed** [comment]
extra info to communicate for people that have problems installing a newer node version
```
npm install -g n
n stable
```
you can also use n lts, stable, latest, v7.1.0, 6.0.0 and so on thats it 

[https://github.com/tj/n](https://github.com/tj/n)

**Comment by phillipskevin** [comment]
We decided we would use Node 4, 6, and 7. If we run into issue with Node 4 we will re-evaluate.

This was discussed at the Contributor's Meeting on 1/6: http://forums.donejs.com/t/donejs-contributors-meeting-2017-01-06/526/12.
