### ISSUE TITLE
Use CanJS-style diff view in code examples

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#708]
Make sure the associated closed issues are fixed.

**Comment by matthewp** [comment]
What is a canjs style diff view?

**Comment by justinbmeyer** [comment]
CanJS's ability to house the whole file, but collapse parts that haven't changed:


<img width="1429" alt="cursor_and_canjs_-_todomvc_guide" src="https://cloud.githubusercontent.com/assets/78602/22804412/9a668b0e-eede-11e6-835c-96810a12407a.png">


Also, canjs can load the test files as code same sources.  I think @matthewp already made this work in DoneJS, but it doesn't need to be re-implemented cc @m-mujica

**Comment by matthewp** [comment]
Ok, so we need bit-docs to use that plugin.

**Comment by matthewp** [comment]
@justinbmeyer I've been trying to add the line diffing but it doesn't seem to work. I can see that the `only` code does run but it doesn't result in any diffs occurring.  Is there any documentation on how this feature is supposed to work, like when a diff is supposed to occur? that would be helpful with debugging it.

**Comment by chasenlehara** [comment]
Can this be moved out of Icebox now that we’re using `bit-docs`?

**Comment by matthewp** [comment]
I would only move it out when someone's working on it (or planning to). I tried and couldn't get it to work.

**Comment by justinbmeyer** [comment]
What went wrong?

**Comment by matthewp** [comment]
https://github.com/donejs/donejs/issues/708#issuecomment-279772062
