### ISSUE TITLE
can-serve is not correctly proxying (1)

### ISSUE THREAD

**Issue by alexisabril** [donejs/donejs#71]
_Issue by **[matthewp](https://github.com/matthewp)** from Thursday Aug 20, 2015 at 22:34 GMT_
_Originally opened as https://github.com/donejs/donejs/issues/55_

---

We had to do:

``` js
io("http://localhost:7070")
```

The proxying is not working

**Comment by alexisabril** [comment]
_Comment by **[daffl](https://github.com/daffl)** from Thursday Aug 27, 2015 at 21:03 GMT_

---

After some rather disappointing trial & error I think proxying websockets with our setup is not possible. We might be able to add it when we have the ability for can.route to define 404s which then gets passed to the proxy but that means that alls non-matching requests will be proxied.

**Comment by daffl** [comment]
This is fixed in latest can-ssr
