### ISSUE TITLE
Project folder hard coded to main="place-my-order/...

### ISSUE THREAD

**Issue by cklanac** [donejs/donejs#71]
When creating a new project such as "mydemo"
```
donejs init mydemo
```

In `index.stache`, the `main` attribute in the script tag is set to "place-my-order".

```
{{#case "production"}}
    <script src="/node_modules/steal/steal.production.js"  main="place-my-order/index.stache!done-autorender"></script>
{{/case}}
```

**Comment by daffl** [comment]
Closed via https://github.com/donejs/generator-donejs/commit/2ce5b2978ab1e9d048d2a988d289e8664bc9324f
