### ISSUE TITLE
November Evangelism

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#723]
> This issue is to track November Evangelism Effort.  This month, we'll be reaching out to a local meetup, usergroup, or conference to speak about something DoneJS related.  Please add your talks below.  

> [Meetup Content](https://docs.google.com/document/d/1P5U-kis4ZfC0bKLhJNvhYr5jewt21YJalE2qO0yJBak/edit#)

Conferences:

 - 3/1 - San Fran - [ForwardJS](https://forwardjs.com/) - has workshops
 - 3/11 - [South Florida Dev Camp](http://www.fladotnet.com/codecamp/SpeakerRegistration.aspx)
 - 1/30 - 4/26 - [PeersConf](https://peersconf1.typeform.com/to/ANtii2)
 - ? - 5/24 - [Front-Trends](https://2017.front-trends.com/speaking-at-front-trends/) _Poland_

## Justin

Confirmed:

- 2016/11/16 - Chicago, IL [Expressive Services and Sessions with Bookshelf, Passport, and DoneJS](http://www.meetup.com/Chicago-Nodejs/events/229666692/)
- 2016/11/19 - Chicago, IL [CanJS Overview and TodoMVC - Full Day Training](http://www.meetup.com/DoneJS-Chicago/events/227969312/)

In progress:

- Silicon Valley _CanJS Overview and TodoMVC_
- ForwardJS - _Getting Started With DoneJS_
- DoneJS Chicago - [Hack Night](https://www.meetup.com/DoneJS-Chicago/events/235738140/)

**Comment by ilyavf** [comment]
Maybe talk on a local meetup about testing apps that use websockets (socket.io).
- Example app could be a RESTful model that works over websockets.
- Show how to mock a socket connection (`can-fixture-socket`)
- Show how to use `can-fixture.store`

Posted the idea to the local Toronto meetup: https://www.meetup.com/torontojs/events/234101793/

**Comment by m-mujica** [comment]
Talk at a local JS meetup https://www.meetup.com/Javascript-Chile/events/234590771/

It will be an intro to StealJS, something like the quick start, basic explanation of what StealJS, how to start with it, use an npm module and build the app.

The next one will be Dec 1, I sent an email already, will update the issue once it gets confirmed.

https://github.com/JavascriptChile/Meetups/issues/24

Update: talk confirmed.

**Comment by matthewp** [comment]
## Matthew

Confirmedish:
- 1/7/2017 - StealJS training for [DoneJS: Raleigh-Durham](https://www.meetup.com/DoneJS-raleigh-durham/events/233079906/)

In Progress:
- Going to develop a can-zone talk based on the [intro to can-zone article](https://davidwalsh.name/can-zone).

**Comment by obaidott** [comment]
Talk at Ottawa Javascript Meetup (http://www.meetup.com/Ottawa-JavaScript/) about DoneJS. Would probably do an "Intro to DoneJS" talk.

**Comment by BigAB** [comment]
I'm in touch with:
- SaskJavaScript (SKJS) (https://www.facebook.com/groups/saskjavascript/)
- Regina Tech Community (http://www.regina-technology-community.ca/)

about doing talks about DoneJS, CanJS and Steal.

Nothing confirmed yet.

**Comment by phillipskevin** [comment]
Feb 5th - StealJS Overview and light comparison to Webpack/RequireJS/SystemJS/Typescript module loader at [Software Development Community](http://www.meetup.com/SoftDev/)  .

**Comment by DesignByOnyx** [comment]
Reached out to [Denver Full Stack meetup](https://www.meetup.com/fullstack/) to talk about DoneJS and/or FeathersJS.

They are planning a meetup for January and are mulling over options. They asked that I reach out to them if I haven't heard back from them within a couple weeks. I have a calendar reminder set for Dec. 1st.

**Comment by chasenlehara** [comment]
Quick report:
- @justinbmeyer gave two talks 🎉🎉
- @m-mujica is giving a talk right now 🎉
- @matthewp and @phillipskevin have talks confirmed(ish) for the start of next year
- @DesignByOnyx, @ilyavf, @obaidott, and myself are currently scheduling talks
- @BigAB is working on reviving the meetup groups in his local community

Gentlemen, please correct me if any of the above is wrong.

I’m working on a [new spreadsheet](https://docs.google.com/a/jupiterjs.com/spreadsheets/d/1gqV-8wrmlgrkULDyheRBiPD5zhYfDzR9HXg9QNnnSTU/edit?usp=sharing) for organizing our 2017 efforts. I’ll update the spreadsheet as I work with everyone on scheduling meet-ups and conferences.
