### ISSUE TITLE
donejs init generate README.md

### ISSUE THREAD

**Issue by alexisabril** [donejs/donejs#73]
_Issue by **[justinbmeyer](https://github.com/justinbmeyer)** from Tuesday Aug 25, 2015 at 16:55 GMT_
_Originally opened as https://github.com/donejs/donejs/issues/64_

---

It would be great if the `donejs init` created a READEME with the basic commands used to develop, test, deploy, build, document the app.

**Comment by daffl** [comment]
This has been fixed via https://github.com/donejs/generator-donejs/commit/3ba7477d3a1e518d0ba2b1085c0caae042222895
