### ISSUE TITLE
Remove the need for the user to set the defaultBinding for can.route with native apps

### ISSUE THREAD

**Issue by alexisabril** [donejs/donejs#74]
_Issue by **[matthewp](https://github.com/matthewp)** from Tuesday Sep 22, 2015 at 20:35 GMT_
_Originally opened as https://github.com/donejs/donejs/issues/92_

---

This can problem be done in canjs itself. the pushstate plugin can detect if it is running on the file protocol and not add itself.

**Comment by alexisabril** [comment]
_Comment by **[daffl](https://github.com/daffl)** from Thursday Oct 01, 2015 at 20:59 GMT_

---

I'm looking into this one.

**Comment by alexisabril** [comment]
_Comment by **[matthewp](https://github.com/matthewp)** from Thursday Oct 01, 2015 at 21:07 GMT_

---

@daffl I think we can detect if on the file protocol here: https://github.com/bitovi/canjs/blob/master/route/pushstate/pushstate.js#L16

**Comment by matthewp** [comment]
@daffl I think this was fixed, no?

**Comment by daffl** [comment]
Yes. When running of the file protocol CanJS routing will now always use hash based routing.
