### ISSUE TITLE
Place My Order is "right" and linked

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#74]
- [x] - Downloads - show on the homepage
- [x] - Figure out situation with databases
- [x] - use donejs folder structure
- [x] - update to latest versions of everything
- [x] https://github.com/canjs/can-ssr/issues/53
- [ ] Submit to the app store

**Comment by matthewp** [comment]
Working on this done.

**Comment by matthewp** [comment]
Status:

* Did not figure out the database issue. place-my-order.com is running on Heroku but the database is still on the old host.  I think we should just run it all on Heroku and who cares of the database is not maintained between deployments.

* Not submitted to the App Store, going to wait for it to look nicer before trying that.  I did add instructions on how to deploy it to your iOS device and that is linked from the donejs.com download link for iOS.

**Comment by James0x57** [comment]
Downloads on the homepage are all set up!

**Comment by matthewp** [comment]
Thanks!
