### ISSUE TITLE
Proposal: Creation of CONTRIBUTING.md and Repo Infos

### ISSUE THREAD

**Issue by frank-dspeed** [donejs/donejs#748]
We Should Define and create CONTRIBUTING.md with guidlines how to contribute to the Project.
as also Create folder .github and place ISSU and PULL Templates in it a good example for this is:

[Docker Repo](https://github.com/docker/docker/tree/master/.github)

[Contrib MD File](https://github.com/docker/docker/blob/master/CONTRIBUTING.md)

**Comment by matthewp** [comment]
cc @chasenlehara At the bottom of this page: http://donejs.com/community.html  it says "Contribution guide coming soon" but that hasn't happened yet.

**Comment by chasenlehara** [comment]
Yeah @matthewp, we have an issue for the DoneJS contributing guide: https://github.com/donejs/donejs/issues/295

I had already filed an issue (in the CanJS repo) about adding issue and pull request templates: https://github.com/canjs/canjs/issues/2273. We haven’t had any more discussion about this but I think it’s a good topic. Thanks for bringing it up @frank-dspeed.

We should have this taken care of for at least CanJS before the announcement so I’ll work on some ideas. Thanks guys. 😊

**Comment by chasenlehara** [comment]
Closing in favor of https://github.com/donejs/donejs/issues/295 and https://github.com/donejs/developer-relations/issues/15
