### ISSUE TITLE
Stache partials not working

### ISSUE THREAD

**Issue by phillipskevin** [donejs/donejs#755]
I added a stache partial to the index.stache of a brand new donejs project. Sometimes the app will load fine, but sometimes the browser becomes totally unresponsive.

Here is the relevant portion of my index.stache:
```
    <can-import from="donejs-partials-test/app" export-as="viewModel" />

    <script type="text/stache" id="my-partial">
      This is the partial
    </script>

    {{>my-partial}}

    {{message}}
```

Everything else was unchanged.

**Comment by justinbmeyer** [comment]
I don't think we should support this in DoneJS.  If someone wants a partial, put it in another file, and import it.  My brain hurts thinking about what would be going on trying to support this.

**Comment by justinbmeyer** [comment]
We should make it clear that this use of partials, or any loading of stache from script tags is frowned upon and should only be used for demo/JSBin purposes.

**Comment by phillipskevin** [comment]
I'm not sure if this is caused by the way the partial is registered. This is from a [gitter conversation](https://gitter.im/donejs/donejs?at=583f701c8e29aeee601b51c5). Registering using an ID was just the simplest one to try. I can try registering partials other ways and see if the same issue occurs.

**Comment by marshallswain** [comment]
I've been using this method for partials: http://forums.donejs.com/t/using-2-3-binding-syntax-to-import-and-use-partials/22

**Comment by phillipskevin** [comment]
Thanks @marshallswain. That's the same solution I gave on gitter, but I forgot there was a forum post about it (knew I must have gotten it somewhere).

I'm still not sure what the correct way to use actual stache partials is in a DoneJS app.

This doesn't seem to work:
```
// app.js
import myPartial from './foo.stache';
can.view.registerView('myPartial', myPartial);


// index.stache
{{>myPartial}}
```

@justinbmeyer maybe you can weigh in on what the correct solution is?

**Comment by frank-dspeed** [comment]
isn't a component a stache partial at all? :)

**Comment by justinbmeyer** [comment]
@phillipskevin Matthew's trick is the correct way.  Also, `.component` files are practically partials.  If what you have there doesn't work, I consider that a bug.  But maybe it's a CanJS bug?

**Comment by phillipskevin** [comment]
I don't think there is an issue in CanJS. Partials worked fine when I tried in JSBin last night. I think either using `can-import` or `.component` files is good.
