### ISSUE TITLE
IE8 support

### ISSUE THREAD

**Issue by alexisabril** [donejs/donejs#76]
_Issue by **[matthewp](https://github.com/matthewp)** from Tuesday Sep 29, 2015 at 13:11 GMT_
_Originally opened as https://github.com/donejs/donejs/issues/106_

---

This is a parent issue.
### Bugs
- [x] - https://github.com/donejs/css/issues/16
- [x] - https://github.com/stealjs/steal/pull/488
- [x] - https://github.com/bitovi/canjs/issues/1969
- [x] - https://github.com/stealjs/transpile/issues/18
- [x] - https://github.com/donejs/autorender/issues/7
- [x] - https://github.com/donejs/autorender/issues/8
- [x] - https://github.com/donejs/autorender/issues/11
- [x] - https://github.com/donejs/css/issues/19
- [x] - https://github.com/canjs/can-set/issues/7
- [x] - https://github.com/canjs/can-connect/issues/37
- [x] - https://github.com/canjs/can-set/pull/9
- [x] - https://github.com/canjs/can-fixture/issues/1

---
### Guide changes
- [ ] - Needs to use jQuery 1.11.x
- [ ] - Need to use "loose mode" when compiling with Babel because of Object.defineProperty
- [ ] - Need to use an XDR transport to make the message posting work

---
### Various
- [x] - Logo doesn't show up because it is a svg.
- [x] - Clicking tabs doesn't change the panel shown.
- [ ] - cannot add messages
  - [ ] - add a crossDomain prefilter
- [x] - messages added from another app aren't updated.
- [ ] - does `this.attr('message')` work?

---
## Releases needed
- [x] can-set patch
- [x] done-autorender patch
- [x] can patch
- [x] done-css patch
- [x] - can-connect patch
- [x] - steal-tools pre

**Comment by alexisabril** [comment]
_Comment by **[matthewp](https://github.com/matthewp)** from Monday Oct 05, 2015 at 15:09 GMT_

---

Need to verify with donejs-chat

**Comment by matthewp** [comment]
I've had this all working locally now, just have some clean-up to do:
1. Push a new version of donejs-chat to Heroku so that the API changes needed are there.
2. Do a new release of CanJS
3. Update the guide to:
   - install jquery 1.11 and the xdr transport
   - Add the prefilter to set crossDomain: true
   - Use loose mode on the build.
