### ISSUE TITLE
Code highlighting is off in Quick Start Guide

### ISSUE THREAD

**Issue by phillipskevin** [donejs/donejs#764]
The code highlighting is off by a couple lines in https://donejs.com/Guide.html:

![image](https://cloud.githubusercontent.com/assets/5851984/21914235/6b05a39c-d8f7-11e6-93a1-25298b6900be.png)

**Comment by phillipskevin** [comment]
I think we just need to update the highlighting lines for any of the templates changed with https://github.com/donejs/donejs/commit/066296635b5c90c08736e351c6006ff11d717e76.

**Comment by matthewp** [comment]
Fixed in the 1.0 guide.
