### ISSUE TITLE
Latest steal-socket.io breaks Chat guide

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#765]
It looks like re-attachment is failing with with latest `steal-socket.io@^4.0.8` on re-attachment on the `/chat` pages.

It works if I use `steal-socket.io@2.0.5`.  

There are two fixes:

1.  Update the guide to point to `2.0.5`.
2.  Make `doneJS@0.9.2` work with `4.0.8`.

cc @matthewp @phillipskevin

**Comment by matthewp** [comment]
Is there an error or does it just never finish?  If it just never finishes it's potentially a can-zone bug.

**Comment by justinbmeyer** [comment]
no errors in the client.  No errors on the server it seems too.  Do you know what is different between 2.X and 4.X?

**Comment by matthewp** [comment]
I have an idea of what it might be, I'll take a look.  Do you have an example repo?

**Comment by justinbmeyer** [comment]
Ok, thanks! In the mean time, I'm going to update the guide to point at 2.X.  If you get a fix, then I'll delete the pull request.

**Comment by matthewp** [comment]
This was fixed in steal-socket.io.
