### ISSUE TITLE
Remove use of can-connect/can/tag/ from guides

### ISSUE THREAD

**Issue by phillipskevin** [donejs/donejs#768]
This might be called out somewhere else, but we should remove this kind of thing from the guides since this is not how 99% of applications will handle retrieving data from models:

```
<restaurant-model get="{ _id=slug }">
```

**Comment by matthewp** [comment]
I think this is a valid way to retrieve data, why do you dislike it?

**Comment by DesignByOnyx** [comment]
I'm kind of with @phillipskevin on this. It's not that we should remove the functionality or remove the examples on the actual `tag` page - but most the time data won't be loaded this way. If you read our docs it feels like there's 15 different ways to do things (exaggerating) and there's no clear indication on which way is "right". Our docs should feel like they were written by the same person and should use examples which can build on each other or appear similar to one another.

**Comment by phillipskevin** [comment]
I'm not saying it's not a valid way to retrieve data, just that most apps won't do it this way and so I don't think we should show it this way 50% of the time in the guides.

**Comment by matthewp** [comment]
This would be a big change in the guides and I don't think it's worth it to block the 1.0 release. I think we should remove this as a 1.0 issue.

**Comment by phillipskevin** [comment]
I think this is actually a duplicate of https://github.com/donejs/donejs/issues/515.

**Comment by phillipskevin** [comment]
Going to close this one.

**Comment by justinbmeyer** [comment]
Why is this a big change?

**Comment by matthewp** [comment]
Any change to the guides that changes code is a big change. It requires at minimum going through each guide on Mac and Windows which is at least a days worth of work. Then there is figuring out what the change should be, updating it on the relevant live apps (donejs/chat and donejs/place-my-order) which is at least another day's work.  

Given that there's nothing wrong with the current approach I don't think that's worth it.

**Comment by phillipskevin** [comment]
I closed this because it was a duplicate of https://github.com/donejs/donejs/issues/515. Do we want to keep both open?

**Comment by justinbmeyer** [comment]
Ah, we can close this for #515, but I still think this is worth it.  This will be a big improvement to the guides and the initial user experience of DoneJS.  I've seen way too much confusion around connect/tags.  I'd rather have this fix over the performance improvements.
