### ISSUE TITLE
Production steal script tag doesn't work both locally and available via CDN.

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#775]
With Steal 1.0 we now have steal.production located inside of the dist folder, so the script tag is:

```js
<script src="/dist/steal.production.js"></script>
```

However once you deploy to the CDN, the dist folder is the root, so it becomes:

```js
<script src="/steal.production.js"></script>
```

In the chat guide I have the user manually change it. Of course that stinks. Need a better solution here.

**Comment by matthewp** [comment]
@phillipskevin if you could, close this one when you do the generator change.

**Comment by phillipskevin** [comment]
Ok, will do.

**Comment by phillipskevin** [comment]
Closed by https://github.com/donejs/generator-donejs/pull/176.
