### ISSUE TITLE
Remove the need for the service-base-url module

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#779]
This is used in the PMO guide but kind of bad for users to have to know about this stuff. Maybe we could do it in a connect behavior instead?  cc @phillipskevin @justinbmeyer

**Comment by justinbmeyer** [comment]
Yes, I'd like to.  But how should it work?  I sort of think this is something linking `stealjs` and `canjs` because things change between `dev` and `prod`.  My guess is the configuration should be in `package.json`.  

Please propose a fix.  This is a very error prone issue in the guides.

**Comment by matthewp** [comment]
We already have a renderingBaseURL, so could have a serviceBaseURL as well like so:

```json
{
  "steal": {
    "envs": {
      "window-production": {
        "renderingBaseURL": "https://firebase.com/place-my-order",
        "serviceBaseURL": "https://www.place-my-order.com"
      }
    }
  }
}
```

Then can-connect/data/url/url would look for this configuration and use it.

steal-socket.io would have to do the same.

**Comment by phillipskevin** [comment]
I like to have a separate config modules for each environment. Something like

```
// config/config.js
const config = {
  serviceBaseURL: "/"
};

export default config;
```

```
// config/production.js
const config = {
  serviceBaseURL: "https://www.place-my-order.com"
};

export default config;
```

This then just gets mapped to the production version in production:
```
{
  "steal": {
    "envs": {
      "window-production": {
        "map": {
          "config/config": "config/production"
        }
      }
    }
  }
}
```

We could have the generators set up this convention (create the files, set up the mapping) and then in the guide the user just has to paste in the values, which is arguably less error-prone.

I'd rather have this done in the app code than couple can-connect with a property that's only going to be available in a steal app.

**Comment by justinbmeyer** [comment]
@phillipskevin  I like the idea, but maybe best for another issue?

@matthewp `can-connect/data/url/url` shouldn't be the behavior that does this directly as it's intended to be very focused on it's one thing of getting data.  It shouldn't know about `stealjs / donejs`. let chat about ideas.

**Comment by justinbmeyer** [comment]
```
1. `donejs add app` 
    - generates `serviceBaseURL: ""` in package.json 

2. `donejs add supermodel`
    - if someone adds `http://chat.donejs.com/api/messages` ??
    
        Option1: - ask if http://chat.donejs.com/ is the serviceBaseUrl, and write that out, and write out:
                `url: steal.serviceBaseURL + "/api/messages"`
        Option2: - -> `url: "http://chat.donejs.com/api/messages"`

    - `/api/messages` -> `url: steal.serviceBaseURL + "/api/messages"`
    - `api/messages` -> `url: steal.serviceBaseURL + "api/messages"`

3. `donejs add cordova`

    - if there's no serviceBaseUrl ... ask for it
```

**Comment by matthewp** [comment]
The approach we decided to go with is to push this onto the generators, so that when you create a new app you'll have configuration like:

```json
{
  "steal": {
    "serviceBaseURL": ""
  }
}
```

Then we you do `donejs add cordova` or `donejs add nw` you'll get updated configuration that looks like:

```json
{
  "steal": {
    "serviceBaseURL": "",
    "envs": {
      "cordova-production": {
        "serviceBaseURL": "http://www.place-my-order.com"
      }
    }
  }
}
```

Turning this into an epic as several changes need to be made to make this all work.

**Comment by matthewp** [comment]
Note to self: Update the guide to remove the nw version, it's not longer needed.
