### ISSUE TITLE
Move documentjs out into a generator

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#784]

**Comment by phillipskevin** [comment]
Steps to do this are:
- [x] remove documentjs from generator-donejs generators (https://github.com/donejs/generator-donejs/pull/186)
- [x] remove documentjs as a devDependency of apps created by donejs-cli (https://github.com/donejs/cli/pull/73)
- [x] create donejs-documentjs
- [x] Add `donejs add documentjs` step to PMO guides in donejs
