### ISSUE TITLE
deprecation warning when running donejs build

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#785]
```
(node:52066) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
```

```
> node -v
v7.4.0
> donejs -V
1.0.0-alpha.0
```

**Comment by phillipskevin** [comment]
I think this was fixed when we moved to yeoman 1.0. Are you still seeing this issue, @matthewp?

**Comment by matthewp** [comment]
I see it when running donejs build.

**Comment by phillipskevin** [comment]
Ok, I do see this still, but only after running `donejs add nw`.

**Comment by phillipskevin** [comment]
Issue moved to [donejs/donejs-nw #8](https://github.com/donejs/donejs-nw/issues/8) via [**ZenHub**](https://www.zenhub.com/)
