### ISSUE TITLE
Guide - Sidebar Heading Consistency

### ISSUE THREAD

**Issue by alexisabril** [donejs/donejs#79]
_Issue by **[atomgroomdesign](https://github.com/atomgroomdesign)** from Friday Oct 02, 2015 at 19:57 GMT_
_Originally opened as https://github.com/donejs/donejs/issues/152_

---

The headings in the Quick Start and Place My Order sidebars are not consistent.

Please match everything up consistently with the Place My Order sidebar.

*\* make sure to leave the features page alone *\* 🔪

**Comment by atomgroom** [comment]
Done.

**Comment by tomgreever** [comment]
"Done" <-- good one @atomgroomdesign

**Comment by atomgroom** [comment]
:+1:
