### ISSUE TITLE
Remove deprecated options

### ISSUE THREAD

**Issue by phillipskevin** [donejs/donejs#798]
`donejs init [folder]` and `donejs plugin [folder]` are deprecated and should be removed in 1.0.
https://github.com/donejs/donejs/blob/major/lib/cli/index.js#L21-L39

**Comment by matthewp** [comment]
Fixed by #809

**Comment by matthewp** [comment]
My previous change removed too much, need to do this again.

**Comment by matthewp** [comment]
Ok, done in bda70e99eb1604b60a80321badf38da75f4b55fd now.
