### ISSUE TITLE
Configure steal.production.js to know the main ~3

### ISSUE THREAD

**Issue by alexisabril** [donejs/donejs#80]
_Issue by **[matthewp](https://github.com/matthewp)** from Sunday Oct 04, 2015 at 22:25 GMT_
_Originally opened as https://github.com/donejs/donejs/issues/153_

---

Correctly production looks like:

``` js
<script src="dist/node_modules/steal/steal.production.js" main="donejs-chat!done-autorender"></script>
```

We could configure this so you don't have to specify the main in the script tag.

**Comment by matthewp** [comment]
This is for the steal.production we copy into the dist folder.

**Comment by matthewp** [comment]
This is done in Steal 1.0
