### ISSUE TITLE
DoneJS 2.0 Release

### ISSUE THREAD

**Issue by phillipskevin** [donejs/donejs#800]
- streaming 
- progressive web app features ([Baseline](https://github.com/donejs/donejs/issues/734), [Exemplary](https://github.com/donejs/donejs/issues/735))
- can-connect  + can-set improvements 
- [improved templates](https://github.com/canjs/canjs/issues/2995)
- use decorators on ES Classes 
- [generator options](https://github.com/donejs/generator-donejs/issues/148) [CJS|ES] [Mocha|QUnit] [tabs|spaces]
- cleanup symbols, operators
- routing 404s
- show off - polyfill | internationalization 
- show off - dev-cache, smaller production loader

**Comment by justinbmeyer** [comment]
- debugger tools
- different styles
- testee?
- documentjs?
- donejs update?

**Comment by matthewp** [comment]
Aside from stuff we have already done or already doing, I think the important things are:

* Better answer for 404s
* debugger tools (not sure what)

**Comment by justinbmeyer** [comment]
Do these have to be part of 2.0? I think we need a 1.1 (or minor) goal/epic.

**Comment by matthewp** [comment]
Probably not. 404s might, depending on what is required there.

**Comment by justinbmeyer** [comment]
Another thing might be adding `can-debug` so it loads only in dev-mode.

**Comment by matthewp** [comment]
How would that work?

**Comment by justinbmeyer** [comment]
@matthewp one of the two ways @m-mujica suggested in CanJS debugging guide:

<img width="691" alt="canjs_-_debugging_guide" src="https://user-images.githubusercontent.com/78602/35313321-542fd0aa-0085-11e8-8f8a-594477f8c5e5.png">

**Comment by matthewp** [comment]
@justinbmeyer I wasn't asking so much how would can-debug be loaded but what does the user experience feel like here. Does merely loading can-debug have some side-effect that is desirable? Do users have to call any methods? If so, do those methods go away when can-debug is not part of the production build? 

Probably better to discuss this idea in a separate issue.

**Comment by phillipskevin** [comment]
`can-debug` sets `window.can` with the `can-namespace` and debug methods.

**Comment by justinbmeyer** [comment]
Yeah, and it warns if people access the global `can` object's properties so people don't mistakingly use them in their modules.

**Comment by matthewp** [comment]
I created https://github.com/donejs/donejs/issues/1074

**Comment by matthewp** [comment]
Packages:

- [x] - done-component
- [x] - done-autorender
- [x] - done-ssr
- [x] - done-ssr-middleware
- [x] - done-serve
- [x] - generator-donejs
- [x] - steal-conditional (release as 1.0)
- [x] - donejs-cli (update steal-conditional)
- [x] - donejs

**Comment by matthewp** [comment]
Just went donejs-chat and it works fine. Will do PMO next.
