### ISSUE TITLE
@root should be %root

### ISSUE THREAD

**Issue by alexisabril** [donejs/donejs#81]
_Issue by **[justinbmeyer](https://github.com/justinbmeyer)** from Tuesday Oct 06, 2015 at 00:10 GMT_
_Originally opened as https://github.com/donejs/donejs/issues/162_

---

**Comment by alexisabril** [comment]
_Comment by **[daffl](https://github.com/daffl)** from Tuesday Oct 06, 2015 at 20:55 GMT_

---

I think currently we're never accessing it through a template. If we want to keep templates encapsulated we might want to prevent access to the root anyway.

**Comment by alexisabril** [comment]
_Comment by **[justinbmeyer](https://github.com/justinbmeyer)** from Tuesday Oct 06, 2015 at 20:56 GMT_

---

I'm not sure what that means.  All I know is can/component has:

initialScopeData = {
                        "@root": componentTagData.scope.attr("@root")
                    },

and that needs to change.

**Comment by alexisabril** [comment]
_Comment by **[matthewp](https://github.com/matthewp)** from Wednesday Oct 07, 2015 at 16:18 GMT_

---

can-ssr: https://github.com/canjs/can-ssr/blob/master/lib/extension.js#L157 - This will be a breaking change and need a 0.10.0 release.

**Comment by daffl** [comment]
Closing since all related PRs are merged.
