### ISSUE TITLE
Create a DoneJS RunKit notebook for debugging issues

### ISSUE THREAD

**Issue by chasenlehara** [donejs/donejs#811]
I’m not sure if this is possible, but it would be great to have something like a DoneJS app in a [RunKit](https://runkit.com/) notebook for debugging issues. It could serve as a template for anyone filing a DoneJS bug.

**Comment by imaustink** [comment]
@chasenlehara I don't think RunKit is quite right for this use-case. I have however successfully set up the place-my-order app on [Cloud9](https://ide.c9.io/imaustink/done-js-playground).

**Comment by chasenlehara** [comment]
@bmomberger-bitovi has been working on a Glitch project that would cover this: https://github.com/donejs/developer-relations/issues/19#issuecomment-298703604

I wonder what the differences between the services are, and if there’s a clear winner. Either way, we should like to all the starter projects so people can take their pick. 😊

**Comment by imaustink** [comment]
I've used both services pretty extensively. For me, I've had a lot better luck with Cloud9. Glitch has some cool collaborative stuff but it usually doesn't work right and causes massive frustration. Cloud9 is more complex than Glitch though, which I could see as a pain-point. So perhaps for this use case Glitch would be better, as it is simpler and collaboration might not be important.

**Comment by chasenlehara** [comment]
@imaustink and I talked about this in person. I don’t think Cloud9 is a good solution because you have to sign in to their service (they have GitHub integration but it requires full access to your account).

As he already mentioned, RunKit is great for testing modules but not for entire apps.

I’m closing this in favor of https://github.com/donejs/developer-relations/issues/19
