### ISSUE TITLE
Add flag for selecting all of the default options

### ISSUE THREAD

**Issue by phillipskevin** [donejs/donejs#819]
@phillipskevin commented on [Thu Jan 26 2017](https://github.com/donejs/cli/issues/71)

It would be nice if you could do something like

```
donejs add app my-app --yes
```

and have all of the default options selected without having to hit enter for every question.

---

@matthewp commented on [Wed Feb 15 2017](https://github.com/donejs/cli/issues/71#issuecomment-280026990)

Shouldn't this be a generator-donejs issue? You couldn't support this universally, I don't think, like `donejs add firebase --yes` wouldn't work. Hopefully the cli flags are passed to the generator some how, and they can interpret them as they wish.

---

@phillipskevin commented on [Wed Feb 15 2017](https://github.com/donejs/cli/issues/71#issuecomment-280047657)

Actually, this is a donejs/donejs issue first, and then a generator-donejs issue. We need to add a command line flag here: https://github.com/donejs/donejs/blob/master/lib/cli/index.js#L15 or commander will exit with `error: unknown option '--yes'`.

**Comment by chasenlehara** [comment]
It’d be neat if we matched `npm init` and had `-f`, `--force`, `-y`, and `--yes`: https://docs.npmjs.com/cli/init

**Comment by matthewp** [comment]
What would `-f` do in this case?

**Comment by chasenlehara** [comment]
Their documentation says those four flags are synonyms to “use only defaults and not prompt you for any options.”

**Comment by phillipskevin** [comment]
Yeah, I think that's fine. NPM is where I got the idea for `--yes`.

**Comment by phillipskevin** [comment]
We're going to add this post-1.0.
