### ISSUE TITLE
Bug: On place-my-order.com, can't select city from the drop-down field 

### ISSUE THREAD

**Issue by AlexGandu** [donejs/donejs#821]
**tested on Edge and Firefox, Windows 10** reproduces all the time

**steps:**
- go to http://www.place-my-order.com/ and click on Restaurant 
- choose a state from the drop-down
- choose a city from the drop down; notice that the city isn't selected
**Expected behaviour:**
- selected city should be displayed and search results are loaded

**There is another issue related:**
if you refresh the page, the buttons aren't responding anymore and you can't do anything, basically, the app freezes.
**steps:**
- refresh the page
- notice that nothing happens when clicking the buttons 
![dropdown](https://cloud.githubusercontent.com/assets/24681052/23001491/6cb3e932-f3dd-11e6-9dfc-f2b309530d98.gif)
![can t select city](https://cloud.githubusercontent.com/assets/24681052/23001490/6cb23fe2-f3dd-11e6-8cb1-e23af12bd6e0.gif)

**Comment by phillipskevin** [comment]
@AlexGandu what browser, browser version, and operating system are you using? 

This is working ok for me:
![pmo](https://cloud.githubusercontent.com/assets/5851984/23002259/7aca352c-f3af-11e6-91a0-498d4788cbbd.gif)

**Comment by AlexGandu** [comment]
i tested on Windows 10, Firefox and Edge using browser-stack

**Comment by phillipskevin** [comment]
Ok thanks, I'll look into this today. I'm going to move it to the place-my-order repo.

**Comment by phillipskevin** [comment]
Issue moved to [donejs/place-my-order #136](https://github.com/donejs/place-my-order/issues/136) via [**ZenHub**](https://www.zenhub.com/)
