### ISSUE TITLE
Bug: On stealjs.com, there is a link redirecting to a unexciting page 

### ISSUE THREAD

**Issue by AlexGandu** [donejs/donejs#822]
Always reproduces on all browsers

**Steps:**
- go to http://stealjs.com/
- click on the CSS icon from the "works with your favourite tech"
- notice that it redirects to a 404 page

**Comment by chasenlehara** [comment]
Hi @AlexGandu, thanks for filing this issue! The StealJS website has it’s own repo, so I’ve created https://github.com/stealjs/stealjs/issues/36 to track this.
