### ISSUE TITLE
Styling proposal

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#830]
This proposes a new project that implements a CSS preprocessor targeted for browsers.

> Note: this assumes some background knowledge on the issues surrounding styling in DoneJS projects. Read [this issue](https://github.com/stealjs/steal-css/issues/16) and [this forum post](http://forums.donejs.com/t/some-disjointed-thoughts-on-styling/513) for a bit of that background.

## Current problems

Styling in DoneJS apps suffers from these primary issue:

* Imported styles are not part of the Steal dependency graph and don't behave like imported JavaScript modules behave. This means that if you import a style multiple times its rules will be applied multiple times.
* Poor performance (with steal-sass, not as much of a problem with steal-less).

Both of these issues are side-effects of an underlying problem; the tools we use for styling were not designed for the type of modlet workflow we know and love. And they were not designed to be run (primarily) in the browser.

The things we like about Sass and Less are:

* The new features they add on top of CSS such as mixins, functions, and nesting.
* The ability to use third-party libraries/frameworks written in these formats.

## Proposed solution

The proposal is to create a new preprocessor that is targeted for browser usage in a development context.

### Goals

* Compatibility with the most popular Sass features. This includes being able to import Sass files and they work.
* The maximum performance possible in the browser.
* Separating out style rules from mixins/variables so that a module can be imported from multiple sources and its style rules are only applied once.

### Design

The design is intended to be completely plugin based. This will allow you to add plugins as you need them for things like:

* nested styles
* mixins
* functions
* `@import` resolution

The goal here is to be able to support popular features (maybe even create things like a Sass "preset" of plugins) while still adding separate plugins of our own as needed.

Additionally performance in the browser is a big goal here so the intent is to:

* Utilize multiple web workers for parsing.
* The parser is streaming so it can begin work as soon as the first line is received.
* Cache the AST so that if a file hasn't changed we can avoid reparsing.

Here's a rough design of how the preprocessor might work:

<img width="675" alt="screen shot 2017-02-17 at 10 17 18 am" src="https://cloud.githubusercontent.com/assets/361671/23070862/71cff7a8-f4fa-11e6-9e36-9fad6db4667b.png">

**Comment by justinbmeyer** [comment]
@matthewp What do you mean by preprocessor? I'm not sure if this is implicit, but I think this has to have a run-time element. This is the big difference vs less / sass .. is that it can't just be a transpiler, we have to have some sort of linkable representation of a __style__ kept in the browser so other styles can use its `functions` without having to re-include the initial __style__.  This is going to be especially important in progressive loading situations.

**Comment by matthewp** [comment]
That's what I meant with this goal:

> Separating out style rules from mixins/variables so that a module can be imported from multiple sources and its style rules are only applied once.

The way I see it is that the style module would be represented as an object where its functions/mixins are exports. This would probably be the realm of the `@import` plugin.

**Comment by matthewp** [comment]
Here's a diagram of the architecture I've been thinking about. [Link](https://docs.google.com/a/jupiterjs.com/drawings/d/1ql6IyhuHv4ww4UjUvL1CysC_ZAxSoNG2MveGk1LCSCk/edit?usp=sharing).

![css stack diagram](https://cloud.githubusercontent.com/assets/361671/23623880/b228182e-0271-11e7-8f42-2e19e64b4e1b.png)

Few potentially interesting points

* The parser will be streaming, in browsers that support streams with fetch. This is so that the Preload scanner can detect `@import` rules and send those to be fetched immediately.
* The linker is what handles assembling a style and its dependencies. For mixins, it will exclude the style rules from being output and only include those in the rules that they are mixed into. This is to prevent the multiple style rule problem that exists with steal-less.
* The loader is a separate process. This library assembles CSS, and is aware of dependencies, but the loader handles inserting `<style>` tags.
* **Parser to AST** and **Generate CSS** are in separate boxes because they *might* happen in separate worker threads. This is because between the parsing and generate steps there needs to be communication with the main thread anyways (as it contains the registry), so it might make sense to put those into different threads.

**Comment by matthewp** [comment]
I still like this idea in theory but don't think it would help generate interest in DoneJS so I don't think it's worth the time investment needed.

**Comment by justinbmeyer** [comment]
What about interest on its own terms?

**Comment by matthewp** [comment]
I personally am interested in such a thing, but I don't think preprocessors where the main advantage is working client-side is much of a selling point in the community, unfortunately.

**Comment by justinbmeyer** [comment]
Do you think this changes with native module loading?

**Comment by matthewp** [comment]
When it's more extensible, maybe.
