### ISSUE TITLE
fetch-newline-delimited-json

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#835]
This proposal is to create a `fetch-newline-delimited-json` package who can be used 
to make a request to a __newline-delimited-json__ service and provide some way of being notified with the stream of objects and its completion.

## Option 1: A promise that returns a CanJS-style event emitter

```js
var fetchNDJSON = require("fetch-newline-delimited-json");

fetchNDJSON("/api/todos.ndjson", {}).then(function(eventEmitter){
  eventEmitter.on("row", function(ev, row){
    
  });
  eventEmitter.on("end", function(ev){
    
  });
  eventEmitter.on("error", function(ev, error){
    
  });
})
```

Pros:
 - lightest weight for CanJS to implement

Considerations:
 - Promise tells us if connection was successful

## Option 2:  A promise that returns a `Kefir` stream:

```js
var fetchNDJSON = require("fetch-newline-delimited-json");

fetchNDJSON("/api/todos.ndjson", {}).then(function(stream){
  stream.onValue(function(row){
    
  });
  stream.onError(function(error){
    
  });
  stream.onEnd(function(){
    
  });
})
```

Pros:

- streams are nice because they more accurately represent a sequence of values.

Cons:

- heavier weight

## Implementation details

This should work like the following CSV example, but use `JSON.parse`:

- [CSV + fetch streaming example](https://jakearchibald.com/2015/thats-so-fetch/) [JSBin](https://output.jsbin.com/gowaze/quiet)
- [NDJson](https://jakearchibald.com/2016/fun-hacks-faster-content/)

**Comment by matthewp** [comment]
Instead of doing it at the fetch level, I wonder if it makes more sense to have it handle Response bodys (which are themselves a stream). Your second link has an example of what we want to do, maybe we just make something that handles that?

```js
var toNDJSON = require("fetch-newline-delimited-json");

fetch('/todos.ndjson').then(function(response){
  var jsonStream = response.body
    .pipeThrough(toNDJSON());

});
```

Where jsonStream is a stream containing each parsed object. This is lower-level than the options you posted, but I think that's ok since it will likely be used by something like a can-connect behavior.

**Comment by justinbmeyer** [comment]
@matthewp I thought about that, but I think `response.body.pipeThrough` isn't available.  Also, I don't think TransferStreams are available.  We might be able to provide our own pipeThrough that works with something that implements both the reader and writer spec.

**Comment by justinbmeyer** [comment]
Links:
- https://jakearchibald.com/2016/streams-ftw/
- Spec: https://streams.spec.whatwg.org/
- Polyfill: https://github.com/pipesjs/core and https://github.com/creatorrr/web-streams-polyfill

**Comment by justinbmeyer** [comment]
Looking into this more, I think we can do this with something more like:

```
ndJSONStream(response.body);
```

The end of this article https://jakearchibald.com/2016/streams-ftw/ has a good example of wiring up one stream into another stream.

**Comment by justinbmeyer** [comment]
So I'm thinking this will be `can-ndjson-stream`

**Comment by justinbmeyer** [comment]
Closing for https://github.com/canjs/can-ndjson-stream/issues/1
