### ISSUE TITLE
Explore solutions for streaming with can-zone, can-compute, and can-view-live

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#837]
## Proposed solution

1.  computes, observations, and maps have a well defined way of traversing their stateful object/event dependency graph.  
  ```js
  var canOperate = require("can-operate");
  
  var cA = compute("A");
  var cB = compute("B");
  var c = compute(function(){
    return cA()+cB();
  })
  canOperate.observableDependencies(c) //-> CIDMAP{ cA: CIDSET["change"], cB: CIDSET["change"] }

  canOperate.observableDependencies(map, "prop")
  ```
  - this already "sort of" exists as `newObserved` on an Observation. However, maps don't flow through correctly. Given some object/event, we need to be able to see what it depends on.

2. Some zone / observation module is able to keep a registry of object/event pairs whose state is remaining to be changed.  At its lowest level, it should return a function that unregisters that object/event.  For example: `observationZone.add( c, "change" ) -> unregister()`.  Apis specific to the type that also set the value can be created for each type.  

3. can-view-live is able to walk through a computes dependency graph, looking for registered object/event pairs, waiting until all object/event pairs for its compute have been removed.

The final result might look like:

```js
var map = new DefineMap({prop: "A"});
var observationZone = require("can-observation-zone");

// Registers this dep as something to wait for.
// This has to happen before `can-view-live` gets it.
// This might be tricky to produce.  
// One issue will be connected view-bindings.  
var doneSettingMapProp = observationZone.add(map, "prop");

setTimeout(function(){
    map.prop = "B"
    // this will reduce the count for setting this property by one
    // if it gets to 0, it will be able to fire off a depsInAllWaitingHaveResolved
    doneSettingMapProp();
},1)

// in can-view-live
var observationZone = require("can-observation-zone");
live.text = function(textNode, compute) {
    // Returns a promise that resolves when the deps within the compute have been
    // resolved
    var depsInAllWaitingHaveResolved = observationZone.getReady(compute);
    textNode[asyncSymbol] = depsInAllWaitingHaveResolved;
}
```

### Specific set state helpers

```js
c = compute(0);

// registers a c/"change"
// returns a function that calls c(newVal) and unregisters
setC = Zone.waitForCompute(c);

setTimeout(function(){
  setC(1);
})
```

## Problem A: async getters

Say there's a template like:

```
{{todos.completed.length}}

{{todos.length}}
```

With a viewModel like:

```js
{
    todosPromise: {
        value: Todo.getList.bind(Todo,{})
    },
    todos: {
        get: function(lastSet, resolve){
            this.todosPromise.then(resolve);
        }
    }
}
```

And `Todo.List` has:

```js
Todo.List = DefineList.extend({
    "#": Todo,
    get completed(){
        var arr = [];
        for(var i = 0; i < this.length; i++) {
        
        }
        return arr;
    }
});
```

The problem is that if `can-view-live.text` passed the compute for `{{todos.completed.length}}` will see there is `async` behavior.  However, `{{todos.length}}` will not.  This is because async computes will only call a bound `async getter` once.  The `{{todos.length}}` will simply read `vm.todos`.

#### Computes are run within a zone and are able to communicate to their parent compute's zone.

This will be similar to `Observation.add`, except with Zone information.  Say there is an async compute like:

```js
var todos = compute.async(function(lastSet, resolve){
    Todo.getList({}).then(resolve);
});
```

This is going to be read by two other comptues:

```js
var todosLength = compute(function(){
  return todos().length
})

var completedLength = compute(function(){
  return todos().completed.length
});
```

When `todosLength()` or `completedLength()` are read ... they will `Zone.waitFor()` their dependencies to finish.

Considerations:

 - It's possible to walk through a compute's dependencies.  This might be faster.  However, the compute might bind on `async`-observable properties.  This must be walked-through.
 - This might be slow to make each compute zone-aware.
 - What if the dependencies change and there's nothing to `.waitFor`?

## Problem B: computes are bound before being passed to `can-view-live`.

Computes are bound here: https://github.com/canjs/can-stache/blob/master/src/mustache_core.js#L339

This is when the __computeFunction__ is first read.  

#### Always zone 

Con:

- slow

### Solution 2 - only  'zone' can-view-live computes

- what if someone binds a compute somewhere else?  Would we pick up on it?

**Comment by justinbmeyer** [comment]
> Random thoughts to be integrated into above:

At it's core ... the problem is the "async" is `memoized` away.  

This doesn't exist for SSR today because we wait on all async behavior and just take the template.

This is really ... what async thing might happen that this depends on ...

The computes above ... depend on another compute that does change as a result of async stuff.

What about other types?  
 - I guess EVERYTHING currently has to be a compute or a list for live binding to work.
 - what if we supported streams or other types?  Would they have to be wrapped in a compute?  How could they declare their "async" dependencies so they "rise to the top"?


Some state is going to be mutated ... a promise is going to resolve, a stream is going to complete.  That state is encapsulated by a compute.

Computes basically have to "run the show".  They represent the final value.  

Computes have values that can change:

```js
var c = compute(0);

setTimeout(function(){
  c(1)
},1)
```

A signal that the state of the compute is going to be done in the future.  This way we can turn something like a Kefir stream into a compute? This might be the onEnd?  

```js
var c = compute(0);

setTimeout(c.waitFor(function(){
  c(1)
  setTimeout(c.waitFor(function(){
    c(2)
  }), 1)
},1)
```

Anything function that could reference or set `c` is suspect.  Ideally, we could track every function and know what's in its closure.  If that function was still accessible from async callback, we'd wait on it.  


```js
var map = new DefineMap({
  prop: 0
});

// how to associate some async setting of `map.prop` ?
setTimeout(map.waitFor("prop",function(){
  map.prop = 1;
}),1)

// given to template ... the compute needs to know that `map.prop` is being 
// waited on.
var c = can.compute(function(){
  return map.prop;
})
```


Could we use `waitFor` with ES `Map`?



```js
var c = compute(0);

var map = new DefineMap({
  prop: 0
});

var setC = Zone.waitFor( c );
var setMapProp = Zone.waitFor( map, "prop");

var viewCompute1 = compute(function(){
  return c();
}),
    viewCompute2 = compute(function(){
      // how does the reading of this alert the zone for this compute?
      // could Zone.waitFor overwrite the getter?
      return map.prop;
    });

setTimeout(function(){
  c(1)
  setTimeout(function(){
    c(2);
    setC();
    map.prop = 1;
    setMapProp();
  }, 1)
},1)
```

basically have to indicate that any zone-able thing `reading` this needs to wait until this associated updating of its state has happened.  Need to tie all `reads` to a future `state change`.  

The `reads` might be:

 - a compute read
 - an observable property read
 - anything else

Could we use `Proxy` or overwrite `Observation.add`?

```js
// tells things reading `map.prop` that there's going to be a particular set.
var setMapProp = Zone.set( map, "prop");


// sets itself up as Observation.add listener.  
// any computes, it's able to check their dependencies against 
// set of things that might need to be set.
// computes are already Observation.add listener
// we just need to be able to walk against "set" registry.  
Zone.run(function(){
  doSomethingThatMightDependOnMapPropsState();
})

setTimeout(function(){
  setMapProp(1);
})
```

- How would the above work with promises that create their object?  
   - `Zone.set` would create the observable on demand. 
- Computes need their hierarchy.

**Comment by matthewp** [comment]
I *think* I follow what you are going for here. You want to create wait promises for events, right? Let's not use waitFor, even for examples, since that already exists for something else. I think what we want is something like:

```js
var registration = Zone.notifyWhen(thing, "event");
registration; // -> { promise, unregister }
```

Then *something else* will attach this registration object to the compute/observation. Then in can-view-live we can do something like:

```js
live.text = function(textNode, compute) {
  // is deps an array of these registration objects?
  var deps = compute.getDependencies();
  var allResolved = Promise.all(deps.map(dep => dep.promise));
  
  textNode[asyncSymbol] = Zone.waitUntil(allResolved);
};
```

Something like that?

**Comment by matthewp** [comment]
I suppose we could overload waitFor to have multiple signatures:

```js
// Waits for a function to be called
var fn = Zone.waitFor(fn);

// Waits for a Promise to resolve
var promise = Zone.waitFor(promise);

// Waits for an event
var registration = Zone.waitFor(object, "event");
```

It feels a little odd to me that the same API would return different things based on overloading though.

**Comment by matthewp** [comment]
*stickying with notifyWhen just for the example*:

```js
var registration = Zone.notifyWhen(thing, "event");
```

Should this actually *wait* on the "event"? Or do we just want to set it up so that *others* can wait on the event? I guess what we want is to create a promise for the event, but that promise doesn't affect the zone it is currently running in.

**Comment by justinbmeyer** [comment]
I think this can be its own package that works with `can-zone`.  I'm not sure what it should be called.  It does __not__ wait on the event, instead it waits on the `unregister` which will typically be associated with a `set` of the state.
