### ISSUE TITLE
Videos for Maintainability section

### ISSUE THREAD

**Issue by alexisabril** [donejs/donejs#84]
_Issue by **[moschel](https://github.com/moschel)** from Tuesday Oct 06, 2015 at 21:30 GMT_
_Originally opened as https://github.com/donejs/donejs/issues/181_

---

Some thoughts on the video boxes in the maintainability section. Disregard this if they're still being worked on:
- The Testing GIF is way too small to see what's going on
- The NPM packaging GIF is very slow, could we speed that up?
- The Live Reload gif is hard to spot the changed header
- In general, I wonder if they should open as a modal pop-in, so users can rewind, pause, etc. Long gifs are annoying because you have no control, and if you miss something, you have to wait for it to loop back around.

**Comment by alexisabril** [comment]
_Comment by **[justinbmeyer](https://github.com/justinbmeyer)** from Tuesday Oct 06, 2015 at 21:48 GMT_

---

Yeah, we probably have to re-cut these videos.

**Comment by phillipskevin** [comment]
@moschel, here is the pull request for the final video: https://github.com/donejs/donejs/pull/193.

**Comment by moschel** [comment]
Thanks @phillipskevin
