### ISSUE TITLE
Verify DoneJS Chat + PMO in donejs@alpha

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#841]
This is a final verification before release.

* [x] - Mac - DoneJS Chat
* [x] - Windows - DoneJS Chat
* [x] - Mac - Place My Order
* [x] - Windows - Place My Order

**Comment by matthewp** [comment]
Holding off on possibly #419

**Comment by chasenlehara** [comment]
…and maybe https://github.com/donejs/donejs/issues/843

**Comment by matthewp** [comment]
I got through donejs-chat today. Plan on going heads-down tomorrow to verify PMO.

**Comment by matthewp** [comment]
BOOOOOOOOOOOM! 💥
