### ISSUE TITLE
Add a Migration Guide to the site

### ISSUE THREAD

**Issue by chasenlehara** [donejs/donejs#842]
The DoneJS migration guide should cover how to upgrade an app or plugin (or generator?) to the same dependencies that are in a DoneJS 1.0 project.

I would expect the guide to frequently refer to the [CanJS](https://canjs.com/doc/migrate-3.html) and [StealJS](http://stealjs.com/docs/guides.Contributing.html) migration guides, while providing info on how to upgrade all of the DoneJS-specific parts.

With a complete migration guide, it should be easy to write this blog post: https://github.com/bitovi/extracurriculars/issues/95

**Comment by matthewp** [comment]
Oops!  I didn't mean to close this.

**Comment by matthewp** [comment]
@chasenlehara the first draft of the guide is [here](https://github.com/donejs/donejs/blob/master/docs/guides/migrate-1.md).  Keeping this issue open as we'll likely revise it some.

**Comment by chasenlehara** [comment]
Assigned this to myself because I plan on going through the migration guide (thanks @matthewp!) when I write that blog post.
