### ISSUE TITLE
Version the install commands

### ISSUE THREAD

**Issue by chasenlehara** [donejs/donejs#855]
Similar to https://github.com/canjs/canjs/pull/3004, the guides should specify version numbers so the correct version is installed.

This depends on https://github.com/donejs/donejs/issues/854

**Comment by matthewp** [comment]
This needs to be done in major and master.

**Comment by phillipskevin** [comment]
Some of this has been done on https://github.com/donejs/donejs/pull/858, but the tests keep failing on AppVeyor with Node 7 so it has not been merged yet.

**Comment by matthewp** [comment]
I filed https://github.com/donejs/donejs/issues/864 for that.

**Comment by matthewp** [comment]
I'm working on the 0.9 versions of this change.

**Comment by matthewp** [comment]
It looks like only the chat guide was updated in #858

**Comment by phillipskevin** [comment]
Both sites have been updated with the versioned guides.
