### ISSUE TITLE
Paragraph Font Weight

### ISSUE THREAD

**Issue by alexisabril** [donejs/donejs#86]
_Issue by **[atomgroomdesign](https://github.com/atomgroomdesign)** from Wednesday Oct 07, 2015 at 15:25 GMT_
_Originally opened as https://github.com/donejs/donejs/issues/191_

---

We have some user feedback that the font weight in the paragraph text is hard to read.  If we remove the anti-aliasing css, it becomes easier to read.  This points more toward font-weight, than the anti-aliasing property.

We should consider making it a bit bolder than it currently is.

**Comment by alexisabril** [comment]
_Comment by **[moschel](https://github.com/moschel)** from Wednesday Oct 07, 2015 at 23:03 GMT_

---

The font in the code samples is still very pixelated and hard to read. The fix you applied didn't affect that text.

**Comment by alexisabril** [comment]
_Comment by **[atomgroomdesign](https://github.com/atomgroomdesign)** from Thursday Oct 08, 2015 at 01:52 GMT_

---

Fixed in https://github.com/donejs/donejs/issues/214

**Comment by alexisabril** [comment]
_Comment by **[justinbmeyer](https://github.com/justinbmeyer)** from Thursday Oct 08, 2015 at 02:45 GMT_

---

@moschel @atomgroomdesign what about making the font 16px instead of bold?  

The reason is that if we were doing our code-highlighting right, JS keywords like `function` would probably be bold.  I'd like to reserve the ability to bold these in the future.  If 16px font looks readable, lets do that.

**Comment by alexisabril** [comment]
_Comment by **[moschel](https://github.com/moschel)** from Thursday Oct 08, 2015 at 04:00 GMT_

---

Yeah I didn't mean make it bold. Code blocks are harder to read now than they were before. 

Remember when we first talked I showed you how just removing that antialiased property made code blocks noticeably more readable?

How they look after your change (can't distinguish syntax highlighting colors):

![2015-10-07_2256](https://cloud.githubusercontent.com/assets/22180/10357371/208de7c4-6d47-11e5-976f-283cf1062a16.png)

How they looked without your change, antialias property on (faded letters):

![2015-10-07_2256b](https://cloud.githubusercontent.com/assets/22180/10357352/eec1ff78-6d46-11e5-9109-0f18520b4207.png)

How they look without your change, and without the antialias property (a lot clearer):

![2015-10-07_2255](https://cloud.githubusercontent.com/assets/22180/10357356/f1b0bb66-6d46-11e5-8080-8909f63fe3d7.png)

**Comment by atomgroom** [comment]
Completed.
