### ISSUE TITLE
IE bug: UI is broken on http://canjs.com/

### ISSUE THREAD

**Issue by AlexGandu** [donejs/donejs#862]
Reproduces only on IE: 
- IE 10: there is a white section in the middle of the page; header links overlap 
- IE 9: only the left section of the page is loaded 
![win 8 ie 10](https://cloud.githubusercontent.com/assets/24681052/23825774/f9a399a2-0687-11e7-9946-cbd0c0805d55.PNG)
![win 7 ie 9](https://cloud.githubusercontent.com/assets/24681052/23825775/fa61d4b2-0687-11e7-97d4-54010bd46fb0.PNG)

**Comment by matthewp** [comment]
Please open this issue in https://github.com/canjs/canjs/issues, thanks!

**Comment by chasenlehara** [comment]
@AlexGandu, thanks for filing this issue! I’ve created https://github.com/canjs/canjs/issues/3100 so you don’t have to open it.
