### ISSUE TITLE
Guides menu

### ISSUE THREAD

**Issue by alexisabril** [donejs/donejs#87]
_Issue by **[moschel](https://github.com/moschel)** from Wednesday Oct 07, 2015 at 20:07 GMT_
_Originally opened as https://github.com/donejs/donejs/issues/203_

---

Right now, the guides menu shows "Quick start" and "place-my-order" as the two options, which semantically doesn't make sense. place-my-order is the application to be built (confusing to someone first visiting the site) and Quick start is more of a user-centric phrase.

To make this consistent, I propose changing "place-my-order" to "Deep dive tutorial" to show that the first one is for a quick intro, the second a deeper look.

**Comment by justinbmeyer** [comment]
If you make this change, update the guides page: http://donejs.com/Guides.html

**Comment by moschel** [comment]
@daffl already did that
