### ISSUE TITLE
Change "In depth guide" to "In-depth guide"

### ISSUE THREAD

**Issue by rlin415** [donejs/donejs#879]
<img width="1259" alt="screen shot 2017-03-28 at 5 09 48 pm" src="https://cloud.githubusercontent.com/assets/8172613/24432807/641fbe88-13d9-11e7-9326-2a6d945528a0.png">

"In depth" should be changed to "In-depth".

**Comment by leoj3n** [comment]
It needs to be updated in a couple places:

https://github.com/donejs/donejs/search?utf8=%E2%9C%93&q=%22In+depth%22&type=

**Comment by andrejewski** [comment]
Fixed by #913
