### ISSUE TITLE
DoneJS support for Debian/Ubuntu

### ISSUE THREAD

**Issue by alexisabril** [donejs/donejs#88]
_Issue by **[tracer99](https://github.com/tracer99)** from Wednesday Oct 07, 2015 at 20:14 GMT_
_Originally opened as https://github.com/donejs/donejs/issues/205_

---

The NodeJS package in Debian/Ubuntu creates a /usr/bin/nodejs executable as node is already taken by an older package.
DoneJS is hardcoded to look for /usr/bin/node which on these systems doesn't exist.

a simple simplink makes it work, but ideally donejs should detect and support the different path.

**Comment by alexisabril** [comment]
_Comment by **[daffl](https://github.com/daffl)** from Wednesday Oct 07, 2015 at 20:21 GMT_

---

The binary is looking for `#!/usr/bin/env node`. So if you environment is set up properly it should work. This is what pretty much every other Node package binary does too.

**Comment by alexisabril** [comment]
_Comment by **[tracer99](https://github.com/tracer99)** from Wednesday Oct 07, 2015 at 20:22 GMT_

---

So this is a bug with the nodejs package in debian?

Edit: this was a fresh Install of Debian Stable. node was installed through debians package manager.

**Comment by alexisabril** [comment]
_Comment by **[matthewp](https://github.com/matthewp)** from Wednesday Oct 07, 2015 at 20:25 GMT_

---

It's not really a bug I would say. Lots of code expects a `node` in the PATH.  Debian installs it as `nodejs`.  You'll find that most scripts in npm look for node.

The fix it to create a symlink:

``` shell
sudo ln -s $(which nodejs) /usr/local/bin/node
```

**Comment by alexisabril** [comment]
_Comment by **[matthewp](https://github.com/matthewp)** from Wednesday Oct 07, 2015 at 20:27 GMT_

---

@daffl actually we could probably make this be a normal .js file and get rid of the shebang.  npm will run it as an executable anyways I think.

**Comment by alexisabril** [comment]
_Comment by **[daffl](https://github.com/daffl)** from Wednesday Oct 07, 2015 at 20:30 GMT_

---

I think we should do it the way literally every other Node binary does it which is the way it is set up at the moment.

**Comment by alexisabril** [comment]
_Comment by **[phillipskevin](https://github.com/phillipskevin)** from Wednesday Oct 07, 2015 at 20:31 GMT_

---

This talks about the issue with Debian and how different package managers install the node binary as nodejs: https://github.com/nodejs/node-v0.x-archive/issues/3911#issuecomment-12798913

**Comment by alexisabril** [comment]
_Comment by **[tracer99](https://github.com/tracer99)** from Wednesday Oct 07, 2015 at 20:31 GMT_

---

Maybe add a note in the documentation for debian/ubuntu users then? As without creating that symlink, it will not work.

**Comment by tracer99** [comment]
So yes, after installing nodejs-legacy, everything seems to work fine. So this is less of an issue with Node/DoneJS and more an issue with Debian/Ubuntu. Seeing as these are really popular distros though, I suggest making this a documentation item.

**Comment by matthewp** [comment]
We might want to have Platforms page that goes over the various quirks on different platforms (this, stuff you have to install on Windows, etc).

**Comment by matthewp** [comment]
@tracer99 I'm adding a page that goes over these things, which version of Node do you get when you install nodejs-legacy?  You can find out with `node -v`.

**Comment by matthewp** [comment]
Nm, going to suggest using a PPA.

**Comment by tracer99** [comment]
@matthewp node-legacy is not a node package. You need nodejs installed, which is v0.10.29
The node-legacy package just sets up the symlink for node -> nodejs

**Comment by matthewp** [comment]
@tracer99 I've added a page on using with Ubuntu/Debian, thanks for your suggestion on this.  http://donejs.com/OperatingSystems.html#section=section_Debian_Ubuntu
