### ISSUE TITLE
Correct sentences in graph image on home page

### ISSUE THREAD

**Issue by rlin415** [donejs/donejs#880]
I think there are a few grammatical errors in some sentences.

<img width="287" alt="screen shot 2017-03-28 at 5 53 59 pm" src="https://cloud.githubusercontent.com/assets/8172613/24433737/9079824c-13df-11e7-9558-0a7bf07647bf.png">

For this one, I think it should be changed to something like:

"Using progressive loading, only the highly optimized bundles of JS and CSS needed for the page are downloaded ."

I also think it's kind of weird how the text is aligned to the right side.

<img width="589" alt="screen shot 2017-03-28 at 6 13 20 pm" src="https://cloud.githubusercontent.com/assets/8172613/24434096/444cb10c-13e2-11e7-869c-a4e7d4c34f30.png">

This should be changed to "All JS and CSS are downloaded for the entire application. JS and CSS are hosted on the application server."

<img width="599" alt="screen shot 2017-03-28 at 6 15 49 pm" src="https://cloud.githubusercontent.com/assets/8172613/24434149/97d2e9c2-13e2-11e7-93b0-e60454f07449.png">

There is period before "but". It should be changed to a comma.

**Comment by chasenlehara** [comment]
@Rlin415, for such small issues, please feel free to submit a PR that fixes them. I know sometimes it takes just as long or longer to create the issues[1] than it does to fix them, so if it’s more convenient, please feel free to just submit a PR.

GitHub makes this really easy with their editing tools. You can search for the file that includes the text in this repo, then click the “Edit this file” (pencil icon) button in the top right. From there you can make a new branch and submit the change as a PR.

[1] You’re doing an awesome job of being specific and including screenshots!

**Comment by andrejewski** [comment]
@Rlin415 was actually more right to submit an issue instead of a PR @chasenlehara , this text is not searchable because it is an image. I can't track down the original assets (at the moment, help pls), but that is where the change should be made.

**Comment by matthewp** [comment]
Check here: https://github.com/donejs/bit-docs-donejs-theme

**Comment by andrejewski** [comment]
Fixed by https://github.com/donejs/bit-docs-donejs-theme/pull/38
