### ISSUE TITLE
Strange behaviour when using can-import tags (opening and closing) v/s just one tag

### ISSUE THREAD

**Issue by nriesco** [donejs/donejs#887]
__How often can you reproduce it?__ 

- [ ] Always
- [x] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__

When importing a component using opening and closing tags something goes wrong. It's hard to explain but somehow the first load (non ssr) just ignores it or does not really import it. But if you are running your app using live-reload and change a file causing a reload then it will work.

this works:

    <can-import from="path/to" />

this fails (partially as mentioned above):

    <can-import from="path/to"></can-import>

__Steps to reproduce:__

1. Start donejs in develop mode `donejs develop` in order to have live reload
1. Create a component (either a myFile.component file or a full component)
1. Include it using `<can-import from="path/to" />`
1. Instance it using `<my-tag />`
1. reload the page it won't show anything
1. modify something in your app and save the file, you'll see the correct contents

__Expected results:__

__Actual results:__

__Environment:__

| Software                | Version
| ------------------ | -------
| donejs -V               | 0.9.2
| node -v                  | v4.6.2
| npm -v                   | 2.15.11
| Browser                 | Chrome 56.0.2924.87 (64-bit)
| Operating system | OSX 10.12.4

**Comment by matthewp** [comment]
When using opening and closing tags the import is a dynamic import as [described here](http://canjs.com/doc/can-view-import.pages.dynamic.html).  Does this knowledge resolve things for you?

**Comment by nriesco** [comment]
Yes my bad.

**Comment by matthewp** [comment]
No need to apologize, these types of issues illustrate that self-closing vs. open/closing tags don't convey that they do different things. We should find a different mechanism for dynamic imports in stache.

**Comment by matthewp** [comment]
One possibly solution is in [this issue](https://github.com/canjs/can-view-import/issues/9).  Going to close as we can discuss more there (or open another issue in that repo if you have a different idea). Thanks! 🤡
