### ISSUE TITLE
place-my-order guide restaurant/list test fails w/ DoneJS 1.0

### ISSUE THREAD

**Issue by nlundquist** [donejs/donejs#896]
When running through the DoneJS Place-My-Order guide with 1.0 the list component test fails on the 'setting state and city loads a list of its restaurants' test.

```
restaurantStore.getList({
    "address.city": "Alberny"
  }).data
```

Ends up returning a list with both restaurants in the fixture instead of the one restaurant that has the city as "Alberny".

```vm.restaurants``` promise ends up returning an empty list.

The lists returned from these two are supposed to match. I believe something is broken with the can-set algebra filtering.

I've attached a sample project that produces the issue. Start the server via 'donejs develop' or 'http-server' and navigate to http://localhost:8080/src/restaurant/list/test.html. The 4th test will fail.

[place-my-order.zip](https://github.com/donejs/donejs/files/903952/place-my-order.zip)

| Software                | Version
| ------------------ | -------
| donejs -V               |  1.0.0
| node -v                  |  7.8.0
| npm -v                   |  4.2.0
| Browser                 |  Chrome 56.0.2924.87
| Operating system |  OS X 10.12.3

**Comment by nlundquist** [comment]
I don't think that this issue is due to DoneJS 1.0. I think can-set just isn't working as expected. In the [current place-my-order example](https://github.com/donejs/place-my-order) this test ends up comparing the complete set of restaurants rather than a filtered set of restaurants with ```city: "Alberny"```.

In the can-set algebra that was added mid-Feb we added two comparators:
```
    "address.city": function(restaurantValue, paramValue, restaurant){
      return restaurant['address.city'] === restaurantValue;
    },
    "address.state": function(restaurantValue, paramValue, restaurant){
      return restaurant['address.state'] === restaurantValue;
    }
```
After reading the can-set docs these seem redundant. The 'restaurantValue' argument is always going to be equal to the property from the 'restaurant' argument. The 'restaurant' argument is the source of the 'restaurantValue'. 

Also the naming here seems misguided, I don't think we can expect the first argument to be the value from the model and the second argument to be the parameter from the query. Sometimes these are switched.

From what I understand this function should be doing a comparison between paramValue and restaurantValue however one of them is always undefined. I believe this is because can-set isn't doing a dot-aware lookup of ```model.address.city``` as expected and is instead returning ```model["address.city"]```.

**Comment by nlundquist** [comment]
AFAIK we'd have to make our algebra comparators similar to the following: 
```
    "address": function(aAddress, bAddress, a, b){
      if ((bAddress === undefined && aAddress !== undefined) ||
           (aAddress === undefined && bAddress !== undefined)) {
        return false;
      }

      for (let prop of Object.keys(aAddress)) {
        if (bAddress[prop] && bAddress[prop] != aAddress[prop]) {
          return false;
        }
      }
      return true;
    }
```

And adjust the queries accordingly: 
list.js
```
Restaurant.getList({address:{state,city}})
```
list-test.js
```
restaurantStore.getList({address: {city: "Alberny"}})
```

Using code like the above gets the test to work as expected in the existing place-my-order example app, comparing two filtered lists instead of the whole set. However when using the same change in my DoneJS 1.0 project the test still fails. The ```vm.restaurants``` promise is still returning an empty list.

Seems likely there is a 1.0 specific issue with the empty list being returned and and the can-set algebra issue may have been unrelated.

**Comment by nlundquist** [comment]
The error in my project was in the fixture ```/api/restaurant/{_id}``` instead of ```/api/restaurants/{_id}```. Typo missing the 's' during model creation and hadn't corrected it in the fixture.

After correcting that (and using the above changes to the can-set comparator) my test works as expected.

I'm going to talk to @phillipskevin about the change to the comparator and if there's a better way to implement it. I'll open a PR to the guide based on that.

Closing this issue since the problem was just in my project.

**Comment by matthewp** [comment]
Can you file an issue about the comparator possibly being wrong just so we can track this?

**Comment by nlundquist** [comment]
Sure! I've created: https://github.com/donejs/donejs/issues/900

If you change the syntax for the queries the set comparators aren't required and the results are as expected. Wondering why we were using them and that syntax in the first place.
