### ISSUE TITLE
Quick Start Guide

### ISSUE THREAD

**Issue by christopherjbaker** [donejs/donejs#898]
Went through the [Quick Start Guide](https://donejs.github.io/donejs-next/Guide.html) and ran into a few things.

When changing src/index.stache, the browser updates as expected. When reloading the page, however, I see the old version of the page while the new one is loading. It seems the server is rendering the old copy. Restarting `donejs-develop` fixes this. (This should perhaps be its own issue?)

Under Messages page / Use the connection, the given template is:

```html
{{#if messagesPromise.isResolved}}
  {{#each messagesPromise.value}}
    <div class="list-group-item">
      <h4 class="list-group-item-heading">{{name}}</h4>
      <p class="list-group-item-text">{{body}}</p>
    </div>
  {{/each}}
{{else}}
  <div class="list-group-item">
    <h4 class="list-group-item-heading">No messages</h4>
  </div>
{{/if}}
```

This renders "No messages" while the result is loading, but will render nothing if the result is empty. I believe it should be (an else "loading..." could be added as well):

```html
{{#if messagesPromise.isResolved}}
	{{#each messagesPromise.value}}
		<div class="list-group-item">
			<h4 class="list-group-item-heading">{{name}}</h4>
			<p class="list-group-item-text">{{body}}</p>
		</div>
	{{else}}
		<div class="list-group-item">
			<h4 class="list-group-item-heading">No messages</h4>
		</div>
	{{/each}}
{{/if}}
```

**Comment by matthewp** [comment]
@christopherjbaker 

> When changing src/index.stache, the browser updates as expected. When reloading the page, however, I see the old version of the page while the new one is loading. It seems the server is rendering the old copy. Restarting donejs-develop fixes this. (This should perhaps be its own issue?)

I wasn't able to reproduce this bug when editing src/index.stache. Is there a particular point in the guide where you noticed this?

**Comment by christopherjbaker** [comment]
@matthewp I'm actually getting this with every donejs project I create. Once I start `donejs develop`, the server rendered version never updates, though the browser sets itself correct once it has all the code. I just tested on my in-depth final by adding a space to a word in home.component. The view-source does not have the space, and when I refresh the page it shows the non-space, then updates about a second later with the spaced version.

Edit: `donejs --version` shows 1.0.0

**Comment by matthewp** [comment]
@christopherjbaker if you check out this project: https://github.com/matthewp/blank-donejs-project

And edit the index.stache file, do you still see this problem?  if so please give me your `node -v` and `npm -v`.

**Comment by christopherjbaker** [comment]
I added "hello" right after the h1 and get the same behaviour. My addition does not show up in view-source, and shows up after a delay upon refresh.

node: 6.10.1
npm: 3.10.10
donejs: 1.0.0
[output of `npm ls`](https://gist.github.com/christopherjbaker/24d04f95a943f4233f61e3d3e15f8501)

**Comment by matthewp** [comment]
Ok, I installed the same versions but didn't experience the bug.

![screen shot 2017-04-12 at 3 11 38 pm](https://cloud.githubusercontent.com/assets/361671/24975061/61ef3d86-1f92-11e7-832c-4b5c05b55f01.png)

Which OS version are you using?

**Comment by matthewp** [comment]
Moving this over to https://github.com/stealjs/steal/issues/1163
