### ISSUE TITLE
Compression can't handle "class" property when passing data to $.View

### ISSUE THREAD

**Issue by mindscratch** [donejs/donejs#9]
In an .ejs file I have:

``` html
<%= $.View('//myapp/controllers/widgets/crud/views/_button', {id: 'add-item', url: $.myapp.make_url("test"), text: "Add " + this.type}) %>
```

The _button.ejs looks like this:

``` html
<div id="<%= this.id %>">
   <a href="<%= this.url %>"><%= this.text %></a>
</div>
```

When I run the build script (e.g. ./js myapp/scripts/build.js) I get the "SyntaxError: invalid property id" problem that had been reported [way back when](http://code.google.com/p/javascriptmvc/issues/detail?id=48). Just as was reported in that old bug, everything works fine for me in development mode. It only fails when I try to compress it using the build script.

I tried changing the "id" to something else, such as "buttonId", but I still have the problem.

I'm using javascriptmvc v3.0.5.

**Comment by mindscratch** [comment]
...i thought I had some problem with passing an "id", but it turns out it's the "class" property. Once I changed it from "class" to something else, such as "buttonClass", the compression/build worked fine.

**Comment by justinbmeyer** [comment]
this works in development mode?  It shouldn't.  Class is a reserved word in JS.  There's nothing we can do about this.
