### ISSUE TITLE
Had to add system config to get production working.

### ISSUE THREAD

**Issue by Alfredo-Delgado** [donejs/donejs#9]
- [package.json](https://github.com/bitovi/levis/blob/b6341132862a86264e9e52540b56c823748367fb/package.json#L41-L43)
- [system-config.js](https://github.com/bitovi/levis/blob/b6341132862a86264e9e52540b56c823748367fb/system-config.js)

**Comment by justinbmeyer** [comment]
@matthewp pretty sure this is closed.  Please re-open if I'm wrong.

**Comment by matthewp** [comment]
Not totally fixed, I need to redo the envs config as described in #57 and then put the vdom config in can's package.json.

**Comment by matthewp** [comment]
Fixed by #57
