### ISSUE TITLE
Live-reload not working when updating .component syles

### ISSUE THREAD

**Issue by alexisabril** [donejs/donejs#90]
_Issue by **[daffl](https://github.com/daffl)** from Thursday Oct 08, 2015 at 00:20 GMT_
_Originally opened as https://github.com/donejs/donejs/issues/215_

---

In the guide, when changing the styles of `home.component` it does not live reload in the browser. It does on the server.

**Comment by matthewp** [comment]
Couple of issues here:
- [ ] - https://github.com/stealjs/live-reload/issues/21  orphan checking code cause unintended teardown of css modules.
- [ ] - https://github.com/donejs/css/issues/23 CSS always appends a style when live-reload is enabled, even if there is already one in the page.

**Comment by matthewp** [comment]
This is a hard problem. The .component css is not supposed to be reloaded because the module that actually changes is the parent module (the .component module). That's the actual file that's changing.  So the teardown never happens for the style virtual module.

I think live-reload needs to expose it's teardown function so that done-component can do something like:

``` js
// When a component is disposed also teardown these child virtual modules
reload.dispose("some.component!", function(){
  reload.teardown("some.component!styles.less!$less");
  reload.teardown("some.component!template.stache!can/view/stache/system");
});
```

**Comment by justinbmeyer** [comment]
I'm not sure how live-reload works exactly.  How are you matching paths and modules?  

Could the mapping of path to module have multiple modules at that path address?

``` json
{
  "/some/path/my.component": ["some.component!template.stache!can/view/stache/system", "some.component!styles.less!$less", ...]
}
```

**Comment by matthewp** [comment]
.components have a fake path so they all show up in the devtools

**Comment by justinbmeyer** [comment]
Then another map of real paths to fake paths?

**Comment by matthewp** [comment]
That wouldn't work though, we would then be doing `System.import("some.component!done-component/styles.less! $less")` and that's a virtual module so there'd be a 404. 

The less is already being reloaded as a result of the .component being reloaded, we just need a way to make sure the virtual modules are torn down at the same time the .component module is torn down.  We already have the `dispose` callback, so I think exposing a teardown method gives done-component what it needs.

**Comment by matthewp** [comment]
## Issues
- [x] - https://github.com/stealjs/live-reload/issues/21
- [x] - https://github.com/stealjs/live-reload/issues/22
- [x] - https://github.com/stealjs/steal/issues/498
- [x] - https://github.com/donejs/css/issues/23
- [x] - https://github.com/donejs/done-component/issues/4

## Other
- [x] - Update donejs package.json

**Comment by matthewp** [comment]
![lrcss](https://cloud.githubusercontent.com/assets/361671/10468504/64ba509c-71cd-11e5-9175-7179732c1a50.gif)
