### ISSUE TITLE
donejs-next place-my-order restaurant set comparator doesn't work as expected

### ISSUE THREAD

**Issue by nlundquist** [donejs/donejs#900]
In the [updated place-my-order guide](https://donejs.github.io/donejs-next/place-my-order.html#create-a-test) the restaurant set comparators don't appear to work as expected. They express a statement that will always return true - checking if the ```restaurantValue``` is equal to property on the ```restaurant``` object where ```restaurantValue``` has been read from:

```
  {
    "address.city": function(restaurantValue, paramValue, restaurant){
      return restaurant['address.city'] === restaurantValue;
    },
    "address.state": function(restaurantValue, paramValue, restaurant){
      return restaurant['address.state'] === restaurantValue;
    }
  }
```

This ends up returning the complete set of restaurants when making a request that should be filtered by address.

The request is being made like:
list.js
```
Restaurant.getList({
    'address.state': state,
    'address.city': city
});
```

and against the fixtures in the test like:
list-test.js
```
restaurantStore.getList({"address.city": "Alberny"})
```

Both those end up returning the complete set of restaurants. When using different syntax:

```
Restaurant.getList({address: {state, city});
...
restaurantStore.getList({address: {city: "Alberny"}})
```

These requests end up returning the filtered list as expected during the test, without ever hitting either can-set comparator. Wondering why we were using the previous syntax at all.

**Comment by nlundquist** [comment]
To answer my question of why we were using this syntax, it's because the backend expects the query to be of the form: ```"/api/restaurants?address.state=IL&address.city=Peoria"``` and when using the ```{address:{state:'IL', city:'Peoria'}}``` query syntax this ends up getting sent as ```"/api/restaurants?address[state]=IL&address[city]=Peoria"``` which returns an empty list.

**Comment by nlundquist** [comment]
It seems in [previous versions of the place-my-order guide](http://donejs.com/place-my-order.html#section=section_Createatest) when these comparators were used only on the fixture, you could predict that the query param would always be the second argument:

```
{
  "address.city": function(restaurantValue, paramValue, restaurant){
    return restaurant.address.city === paramValue;
  },
  "address.state": function(restaurantValue, paramValue, restaurant){
    return restaurant.address.state === paramValue;
  }
}
```

However when you move the above to the model it will fail since sometimes the query param is passed as the first argument and the restaurant as the fourth. If instead you use can-set comparators like:

```
"address.city": function(aValue, bValue, a, b){
  let restaurantValue, paramValue;

  // one of the values being set means its the query parameter, since the model itself doesn't have obj['address.city']
  if (aValue != undefined) {
    paramValue = aValue;
    restaurantValue = b.address && b.address.city;
  } else if (bValue != undefined) {
    paramValue = bValue;
    restaurantValue = a.address && a.address.city;
  }

  return paramValue === restaurantValue;
},
"address.state": function(aValue, bValue, a, b){
  let restaurantValue, paramValue;

  // one of the values being set means its the query parameter, since the model itself doesn't have obj['address.state']
  if (aValue != undefined) {
    paramValue = aValue;
    restaurantValue = b.address && b.address.state;
  } else if (bValue != undefined) {
    paramValue = bValue;
    restaurantValue = a.address && a.address.state;
  }

  return paramValue === restaurantValue;
}
```

Queries like ```getList({'address.state': state, 'address.city': city});``` will then work as expected. There are likely simpler ways to express comparators that don't expect the query parameter in a  specific position, but it will still be somewhat unclear to novices why we need to do that.

I wonder if it's worth it for an example app to change the comparators to work like this or for the sake of clarity in we'd be better off making the backend accept queries in the form ```?address[city]=Peoria```?

**Comment by nlundquist** [comment]
So the answer to why we can't make queries of the form `{address: {city: 'Peoria', state:'IL'}}` work is because that query form has a special behaviour inside of MongoDB. That form looks for records where the address object is exactly equal to the provided one. Should a record's address object have any properties missing from the query address object, the record will not match. 

The form `{'address.city': 'Peoria', 'address.state': 'IL'}` is required by Mongo to restrict matching to just those properties rather than doing a match on the entire provided address object.

This begs the question, if someone wanted to use can-set with Mongo, how could they avoid having to add set comparators like above for every property they query in the 'object.property' form? Doing it in the way we have would quickly become unsustainable for any complex project.

**Comment by nlundquist** [comment]
From my perspective the conversion of queries from 'object form' to 'dot form' might make most sense as an additional can-connect behaviour, but in the current implementation of can-connect superMap the user can't add any additional behaviours. Maybe we should consider the ability of a user to append the mixed in behaviours on superMap.

**Comment by phillipskevin** [comment]
@nlundquist can we add a [hook](https://github.com/donejs/place-my-order-api/blob/master/src/hooks.js) that would convert the query format?

**Comment by nlundquist** [comment]
@phillipskevin that seems possible, but would we want to prevent a valid (and likely more efficient) style of query on the service layer to make the client work as expected? Or should we make the can-connect client do the conversion since it's the client whose expectations don't quite match up with the backends query format?

I know I previously suggested we should change the backend to play nice with the front end, but that was before I knew the 'object form' query style has a special significance to Mongo.

**Comment by phillipskevin** [comment]
I think converting it on the backend is the solution that works best for the guide.

**Comment by phillipskevin** [comment]
Just going to paste here what we talked about, we want to make something like this work and then use it in the guide:

![image](https://cloud.githubusercontent.com/assets/5851984/24919146/4929fa9c-1ea8-11e7-84cd-df921c8620d4.png)

**Comment by nlundquist** [comment]
just had a talk about this with @justinbmeyer and @phillipskevin - agreed to add a new can-set prop to make the sort of comparator listed above easy.

**Comment by nlundquist** [comment]
can-set 1.2.0 has the new set.prop.dotNotation so I'll update the guide to include it's use

**Comment by nlundquist** [comment]
Guide update and project update PRs have been merged and can-set has been updated. This issue is closed.
