### ISSUE TITLE
In Depth Guide

### ISSUE THREAD

**Issue by christopherjbaker** [donejs/donejs#904]
Went through the In Depth Guide and ran into a few things.

* setting up routing
	* creating a loading indicator
		* `leak-scope` not explained
* creating a unit-tested view model
	* create a test
		* guide page says `'*': Restaurant` but generated code is `'#': Restaurant`
		* What purpose does it serve to add the algebra to the frontend? Shouldn't this behaviour already be handled by the backend? (both asking, and suggesting it be addressed)
* creating data:
	* creating the order model
		* ItemsList is specified with `'*': Item` (see above). Based on the docs and generated code, I believe it should be `'#': Item`.
	* write the template
		* The checkbox under the dinner menu uses `($change)="order.items.toggle(this)"`, whereas the lunch uses `($change)="order.items.toggle(.)"`. It seems to work fine both ways, though the inconsistency is a bit confusing.

**Comment by justinbmeyer** [comment]
@christopherjbaker `set.Algebra`'s allow things like real-time, request combining and some caching strategies.  

Yeah, everything should be `#`.
