### ISSUE TITLE
menu items on donejs-next guides have janky animation

### ISSUE THREAD

**Issue by nlundquist** [donejs/donejs#910]
The sub-menus on the DoneJS-next guides expand, contract and then expand again when navigating between them:

![bouncing_menu](https://cloud.githubusercontent.com/assets/2623867/25026552/264d3120-2064-11e7-89d9-48ac0d7d4a69.gif)

This is always reproducible in OSX Chrome 56. This error doesn't exist on the current version of the DoneJS website. To reproduce visit https://donejs.github.io/donejs-next/place-my-order.html and click between top-level menu items. The menus should open smoothly instead of rapidly opening, closing and then opening again.

**Comment by chasenlehara** [comment]
Issue moved to [donejs/bit-docs-donejs-theme #37](https://github.com/donejs/bit-docs-donejs-theme/issues/37) via [**ZenHub**](https://www.zenhub.com/)
