### ISSUE TITLE
DoneJS chat API server is misconfigured for https

### ISSUE THREAD

**Issue by bmomberger-bitovi** [donejs/donejs#935]
`http://chat.donejs.com/api/messages` is fine as an AJAX endpoint if users are running from `http://localhost:8080` as in the guide.  However, trying to run the code on JSBin, which uses HTTPS, causes a failure due to disallowed insecure/secure mixing.  

Simply changing the `http` to `https` isn't enough to make it work, since `chat.donejs.com` is really `donejs-chat.herokuapp.com` and is served with an SSL certificate that's only valid for `*.herokuapp.com`.  We should set up a cert for `chat.donejs.com` on our heroku instance, as detailed in this guide: https://devcenter.heroku.com/articles/ssl-endpoint

**Comment by chasenlehara** [comment]
The CanJS chat guide is currently broken because of this issue: https://canjs.com/doc/guides/chat.html#Result

**Comment by phillipskevin** [comment]
https://chat.donejs.com/api/messages is working now. Just need to update the JSBins to use `https`.

**Comment by chasenlehara** [comment]
Thanks @phillipskevin!

**Comment by phillipskevin** [comment]
@matthewp helped me finish it off also, so thanks @matthewp. And thank you, @chasenlehara, for fixing the JSBins.
