### ISSUE TITLE
PMO - Route helpers not imported in home.component

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#943]
log.js:102 WARN: can-stache/src/expression.js: Unable to find helper "routeUrl".

**Comment by phillipskevin** [comment]
Is this in the PMO guide?

**Comment by justinbmeyer** [comment]
yes

**Comment by andrejewski** [comment]
We should be explicitly adding `<can-import from="can-stache/helpers/route" />` to the code blurb in https://donejs.com/place-my-order.html#creating-a-homepage-element is all.

**Comment by phillipskevin** [comment]
I missed that the highlighting also needs to be updated: 
![image](https://cloud.githubusercontent.com/assets/5851984/26357097/da049f7a-3f93-11e7-8f14-12d466ed50be.png)
