### ISSUE TITLE
donejs/donejs hardcoded in the tests

### ISSUE THREAD

**Issue by chasenlehara** [donejs/donejs#951]
These two files have this repo hard-coded, so submissions from forks fail:

- https://github.com/donejs/donejs/blob/b6879cbdd98d2665871f1f50173ecdc15dcc822e/guides/guide/test.js#L31
- https://github.com/donejs/donejs/blob/b6879cbdd98d2665871f1f50173ecdc15dcc822e/guides/place-my-order/test.js#L44

**Comment by morrme** [comment]
what would be the best way to write it ? would `"/donejs#"` work?

**Comment by andrejewski** [comment]
We'll use `TRAVIS_PULL_REQUEST_SLUG` and `TRAVIS_REPO_SLUG` from https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables

**Comment by morrme** [comment]
@andrejewski Ah, awesome. Do you plan to do this or may I give it a try?

**Comment by andrejewski** [comment]
@morrme I did plan to, but by all means give it a shot. I wasn't gonna do it until Monday anyway. Please add me as a reviewer on the PR.

**Comment by morrme** [comment]
Thanks @andrejewski ... I do not have the rights to add you as a reviewer but here's the PR https://github.com/donejs/donejs/pull/952
