### ISSUE TITLE
donejs add firebase@1 does nothing in bitballs root folder

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#962]
bitballs root folder is not a donejs project.  it's public folder is.  If someone runs `donejs add firebase` we should probably give them a warning.

**Comment by matthewp** [comment]
Shouldn't this be in donejs/bitballs?

**Comment by justinbmeyer** [comment]
No, I think `donejs`'s CLI should warn if its not running in a donejs app.  I believe some generators already do. But probably not `donejs add firebase`.  It probably belongs in that generator.

**Comment by matthewp** [comment]
Can you update the issue description for what change you are proposing to donejs?

**Comment by frank-dspeed** [comment]
donejs cli can't warn if on command add in general if not executed in a donejs project as donejs add command creates a donejs project or plugin also.

way to go is to warn only if command is not add app or add plugin 

i think in general it should warn only if it trys to execute a donejs-Generator module outside of a donejs project

**Comment by frank-dspeed** [comment]
I think this issue is also related and can be closed after this it would fix that https://github.com/donejs/donejs/issues/995

**Comment by matthewp** [comment]
Issue moved to [donejs/donejs-firebase #21](https://github.com/donejs/donejs-firebase/issues/21) via [**ZenHub**](https://www.zenhub.com/)
