### ISSUE TITLE
Proposal: Handle socket.io SSR Incompatiblity 

### ISSUE THREAD

**Issue by frank-dspeed** [donejs/donejs#971]
can't use SSR with steal-socket.io and NODE_ENV=production
because steal-socket.io then exports the ssr variant in production builds
so this would only work with a nativ http server like npm http-server

## Question 
1. should we document that in steal-socket.io?
2. should we change the npm start command of a default donejs app to http-server
and not done-serve
3. should we add a donejs production command to npm that uses NODE_ENV=production http-server
4. should we document and check in done-serve that it don't gets runned with NODE_ENV=production?
5. should steal-socket.io detect if it runs in NODE_ENV=production under done-serve?

## Alternative
5. done-server in production mode disables ssr but currently production.html and development.html also don't render when using donejs-feathers
Also disable SSR in Production is probally not always wanted? not sure

**Comment by frank-dspeed** [comment]
# I vote for:
options 1,2,3,4 together

**Comment by matthewp** [comment]
I don't understand the problem. Why is it that you can't use steal-socket.io in production mode?

> because steal-socket.io then exports the ssr variant in production builds

Do you mean that the client build contains the ssr variant? And what is the "ssr variant", exactly?

**Comment by frank-dspeed** [comment]
https://github.com/feathersjs/feathers-socket-commons/issues/44

**Comment by frank-dspeed** [comment]
@matthewp the client build contains the right variant it contains steal-socket.io that will return wrong object the same that it would return on ssr.

**Comment by matthewp** [comment]
Ok, that sounds like a bug in steal-socket.io then. I'm not sure why it returns the wrong object...

**Comment by matthewp** [comment]
I just tested with donejs-chat and the socket.io stuff works in production. What scenario are you seeing this problem? Can you reduce it down maybe?

**Comment by frank-dspeed** [comment]
https://github.com/direktspeed/prove-bugs/issues/1

**Comment by frank-dspeed** [comment]
the reduce of the issue reduces it to use with feathersjs no feathers no cry :)

**Comment by frank-dspeed** [comment]
# Conclusion 
if you want to run a socket.io based donejs app with NODE_ENV=production npm start you need to use socket.io-client with steal-socket.io it fails when using feathers-socketio

plus the error is 100% some how related production.html don't renders and development.html don't renders when using donejs-feathers

## example app
@matthewp https://github.com/direktspeed/prove-bugs/issues/1

**Comment by matthewp** [comment]
So this is a bug in donejs-feathers? I took a quick look and it looks like the problem is that the Zone never completes, probably something in a dependency is not clearing a timeout or is doing some type of asynchronous recursion thing.

**Comment by frank-dspeed** [comment]
@matthewp this are 2 bugs i think first bug is related to steal-socket.io it returns the wrong object if used like NODE_ENV=production npm start 

secund bug is that if you bypass that bug and use socket.io-client/dist/socket.io directly wich returns always right. 

we enter the next bug production.html and development.html are not rendering.

this is some how related to anything in can-connect-feathers i think and or any dependency of that.

and only happens if the promise gets Resolved.


the magic here is that done-serve works in development and production so SSR works without any issues. only the steal-socket.io issue when used in production donejs develop works

**Comment by frank-dspeed** [comment]
@matthewp and can-zones i readed about it sounds like a good buggy place for me as it trys to magic do promises :D without a callback this could be the error.

we could need something like zone-debug

**Comment by matthewp** [comment]
The issue is Zone related. The reason it is not rendering is because the Zone never completes and done-autorender waits for the Zone to complete. You can use Zone.ignore to ignore functions:

```js
var Zone = require("can-zone");
var someFunctionThatCallsSetInterval = require("dep");

var ignored = Zone.ignore(someFunctionThatCallsSetInterval);

// Now you can safely call ignored()
ignored()
```

**Comment by matthewp** [comment]
@frank-dspeed there is such a thing, but it's not so easy to use with done-autorender.

**Comment by frank-dspeed** [comment]
@matthewp but i don't understand why it don't gets resolved in any case its doing the request and returns the promise i have console.log in code to prove that.

i don't think that it uses setInterval

**Comment by matthewp** [comment]
If you're not using ssr you might consider not using done-autorender.  This completely avoids the problem as there are no Zones then. You can just create a `head.stache` file and a `body.stache` file, and then a `main.js` that renders each of those into the `<head>` and `<body>`.

**Comment by frank-dspeed** [comment]
https://github.com/donejs/bitcentive/issues/309 i think this is 100% related and here the same solutions got suggested

**Comment by frank-dspeed** [comment]
@matthewp the only problem that i have with this is that this would brake donejs develop and npm start

it will fix my issue but i am not happy out of donejs project view this needs to get addressed i think using websockets is a general use case that will even expand over next years.

i am now fully understanding what happens but no normal donejs user will and he will run into such issus while he will follow receips and so he will blame donejs for that.

this will result in a large community loose its importent core main importent that new developers can use this receips and even use the canjs receips in donejs.

i found out i waisted probally over 1 year only because i was not really knowing about can-zones and that this is such a main importent part of the donejs project.

**Comment by matthewp** [comment]
Just for clarity, there's no problem with websockets that I'm aware of. There's a problem with socket.io, but it's not because of websockets, it's because it uses a recursive setTimeout to do some polling and since can-zone overrides setTimeout to do counting, there is a conflict.  I'm not aware that this is a fixable problem, at least I haven't thought of anything, and is an inherit problem with the goal of can-zone. That's why Zone.ignore exists, for cases such as this.

**Comment by frank-dspeed** [comment]
@matthewp i don't think its really the same issue i opened this only for fixing docs of steal-socket.io and or done-serve because many users will run into that and stop using donejs befor even understanding what can-zone is or done-autorender for example if they copy a receipe using socket.io with steal-socket.io they are doomed

**Comment by frank-dspeed** [comment]
@matthewp this is about the bug of done-serve with steal-socket.io that it don't exports the right object and so the feathers-socketio don't gets connection

**Comment by frank-dspeed** [comment]
@matthewp i don't think its really the same issue i opened this only for fixing docs of steal-socket.io and or done-serve because many users will run into that and stop using donejs befor even understanding what can-zone is or done-autorender. For example if they copy a receipe using socket.io with steal-socket.io they are doomed !

example receips from canjs that get ported to donejs using socket.io exist :) even the tip to use steal-socket.io exists in guides.

the only fact why bitballs and other examples work are the usage of ssr via donejs middelware for express. so you can't even deploy production builds on diffrent servers


- #972 is more about can-zone can't be used with socket.io https://github.com/canjs/can-zone/issues/108
- #971 is about steal-socket.io https://github.com/stealjs/steal-socket.io/issues/27

but your right now as i know about can-zone we need to document that also! ASAP!

both demonstrated via https://github.com/direktspeed/prove-bugs/issues/1

**Comment by matthewp** [comment]
We just don't need so many redundant issues. There are individual issues in can-zone and done-autorender, I think 1 donejs/donejs issue about "what to do about socket.io" is enough.  So let's make this that issue.

**Comment by frank-dspeed** [comment]
@matthewp i aggree with you we need to asap find a solution for the documentation i am already satisfied i understand it now and know what to do but that was blocking me probally over 1 year without regonizing it because i then simply switched frameworks when things start to don't work because i have deadlines but i am 100% sure many people runned into this.

**Comment by frank-dspeed** [comment]
# Update
https://github.com/donejs/donejs/issues/976

At the end @matthewp sayed its our issue but i think it is a feathers-socket.io issue because the reasons at end of https://github.com/donejs/donejs/issues/976

#976 got closed by the fact that the problem really don't exist when using steal-socket.io without feathers-socketio

matth:
Yes, it's definitely a bug with donejs and can trivially be reduced down to not needing feathers or socket.io, so there's no reason to bother than with this.

frank:
wait thats now impossible without socket.io and feathers there is no bug lol how do you reduce it with steal-socket.io there is also no bug standalone only with steal-socket.io + feathers-socketio + done-serve + NODE_ENV=production

without NODE_ENV=production there is also no bug. only the can-zone bug wich is our bug
the only bug that is left is really only feathers-socketio related as its connection don't gets setup right if using steal-socket.io

steal-socket.io standalone without feathers works writed complet test app
