### ISSUE TITLE
Replace all receips using socket.io with primus

### ISSUE THREAD

**Issue by frank-dspeed** [donejs/donejs#976]
__How often can you reproduce it?__ 

- [X] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__

__Steps to reproduce:__

known accepted can-zone bug with recursiv usage of setTimeout in socket.io

__Expected results:__
All works loads all is good

__Actual results:__
Some Conditions it works but not all and it needs to work in production with and without ssr as also development

__Solution___
We Replace socket.io usage all over with primus even feathers is primus ready and we get it all up and running for canjs and donejs

**Comment by frank-dspeed** [comment]
Alternativ if this gets merged https://github.com/donejs/autorender/pull/68 we can update docs to inform about need to use that option with socket.io explicit.

**Comment by matthewp** [comment]
Using steal-socket.io will cause its async tasks to be ignored. There's no issue with our guides that I'm aware of if using steal-socket.io. There might be when using 3rd party libraries that use socket.io though, I'm not sure.

**Comment by frank-dspeed** [comment]
@matthewp ok let me hunt that down i will remove feathers from my example and look if nativ socket.io things work!

**Comment by frank-dspeed** [comment]
@matthewp your right i will create that bug in feathers-socketio

**Comment by matthewp** [comment]
Please don't create an issue there. They are not doing anything to cause the bug. It's not their bug, it's our bug.

**Comment by frank-dspeed** [comment]
@matthewp but it can't be the bug of us because it works standalone the function how they set connection looks wirred any way.

**Comment by matthewp** [comment]
Yes, it's definitely a bug with donejs and can trivially be reduced down to not needing feathers or socket.io, so there's no reason to bother than with this.

**Comment by frank-dspeed** [comment]
@matthewp wait thats now impossible without socket.io and feathers there is no bug lol how do you reduce it

**Comment by frank-dspeed** [comment]
@matthewp and with steal-socket.io there is also no bug standalone lol only with steal-socket.io + feathers-socketio + done-serve + NODE_ENV=production

**Comment by frank-dspeed** [comment]
wait thats now impossible without socket.io and feathers there is no bug lol how do you reduce it with steal-socket.io there is also no bug standalone only with steal-socket.io + feathers-socketio + done-serve + NODE_ENV=production

without NODE_ENV=production there is also no bug. only the can-zone bug wich is our bug
the only bug that is left is really only feathers-socketio related as its connection don't gets setup right if using steal-socket.io 

steal-socket.io standalone without feathers works writed complet test app

**Comment by frank-dspeed** [comment]
anyway this can be closed
