### ISSUE TITLE
Proposal: Rename donejs-* repos that are not a donejs generator!

### ISSUE THREAD

**Issue by frank-dspeed** [donejs/donejs#998]
i found out that many repos here are sharing name space with the reserved donejs-* name space thats used for donejs-* generators 

my suggestion rename them if they are not generators to done-

Current findings so far.
- https://github.com/donejs/donejs-streaming-test-comparison - documentation
- https://github.com/donejs/donejs-streaming-product-page - demo
- https://github.com/donejs/donejs-number-input - plugin component
- https://github.com/donejs/donejs-cli - Offical Local CLI

**Comment by phillipskevin** [comment]
can you give examples?

**Comment by frank-dspeed** [comment]
@phillipskevin 

don't know if exist more need to look first in every donejs-* repo takes some more time

**Comment by matthewp** [comment]
We're not going to restrict the names people can use for donejs repositories, nor do github repository names interfere with generators.

**Comment by frank-dspeed** [comment]
@phillipskevin but you remember that the donejs binary will auto install and download packages called donejs-* ? 

but ok its fine for me as i don't rellay on that tooling feel free
